### ISSUE TITLE
Ping -  Resolve PTR

### ISSUE THREAD

**Issue by SovernT13** [BornToBeRoot/NETworkManager#105]
On the Ping tab - A checkbox when checked (or maybe separate button when pressed) tries to resolve the hostname of an IP address similar to ping -a.

**Comment by BornToBeRoot** [comment]
The PTR (IP -> Host) is resolved in the background. The ping is not affected or delayed. The hostname will be displayed as soons as it is available. If no hostname is resolved, the field stays empty.

![image](https://user-images.githubusercontent.com/16019165/41940690-ea969dde-7999-11e8-933a-2d2f92783b05.png)

If you enter a hostname, it is passed and will be displayed in the result.

![image](https://user-images.githubusercontent.com/16019165/41940887-8f53c1bc-799a-11e8-9b5b-819c5cf24ef5.png)

If a wrong hostname is entered, an error is displayed.

![image](https://user-images.githubusercontent.com/16019165/41940919-abbd5d22-799a-11e8-9be6-16f6ce4e0c56.png)

**Comment by BornToBeRoot** [comment]
Feature will be available in the next release!

**Comment by SovernT13** [comment]
Awesome! Thanks!!
