### ISSUE TITLE
Resolving hostname of users connected via VPN in IP Scanner

### ISSUE THREAD

**Issue by PCAssistSoftware** [BornToBeRoot/NETworkManager#1254]
Hi

When using the IP Scanner to scan the IP range used by my VPN users how can I get it to populate the hostname column? currently it is blank but I want to be able to see all the computer names connected and it is easier if I can see names rather than just IP addresses?

Is this a NETworkManager issue or a configuration issue with VPN/DNS etc

I can ping the clients via IP or name

All suggestion gratefully received

![image](https://user-images.githubusercontent.com/10872799/132554033-3bc5cbf1-ce33-440a-b200-062615bd21d9.png)

**Comment by BornToBeRoot** [comment]
@wingers999 Hi, I just tested it and it worked (at least with my vpn connection). Maybe it's because of the order of the DNS servers (local + vpn). The library uses the first server by default.

You could try to set the dns server in the settings for the ip scanner (this dialog may change in future versions, because i want to set the dns global).
![image](https://user-images.githubusercontent.com/16019165/132501166-3ffa7eb8-acdd-4d8c-b2fb-7656e734aa68.png)

**Comment by PCAssistSoftware** [comment]
@BornToBeRoot - thank you so much for testing, I did try it with Use custom DNS server turned on and the IP filled in for my internal Windows Server 2012 DNS server but still doesn't work.

Any other thoughts or tests I could run as everything else works perfect, just need to sort the name resolution

Thanks

**Comment by BornToBeRoot** [comment]
@wingers999 you could try the DNS Lookup tool to resolve a singel ip (Type PTR). This is the same libary but you may get a better error message if it cannot connect to the dns server.

**Comment by PCAssistSoftware** [comment]
@BornToBeRoot - turns out that there is more to the problem than just the tool not working, had done some further testing with nslookup etc and was not getting any results, looks like site I was testing on / trying to fix didn't have DNS reverse lookup zone for VPN DHCP range - adding this seems to have partially resolved it - thanks for replying, will close now and come back if have any future issues.  Thanks also for such a great project.

**Comment by BornToBeRoot** [comment]
It's always DNS! 😄
