### ISSUE TITLE
App UI size is not fit with Windows resolution when Windows task bar is docked to left/right side

### ISSUE THREAD

**Issue by directmemory** [BornToBeRoot/NETworkManager#1275]
**Describe your issue**:
When i set my task bar on Windows left and open this app, part of the app is placed outside of Windows screen.
**Steps to reproduce the issue**:
On any time when you open this app.
1.
2.
3.

**NETworkManager version**: 

**Windows version**:
Windows10 home 2004
**.NET-Framework version**:
5.0.401
**Screenshots**
![图片](https://user-images.githubusercontent.com/34593920/136640274-e3d5cfb3-8a60-4e4a-a04a-5ab20a20ed8f.png)
![图片](https://user-images.githubusercontent.com/34593920/136640281-ae2e9e9f-4eb7-4f20-81da-a66d9ad7035b.png)

<details>
<summary>Eventlog (if application crashes)</summary>

</details>

**Comment by BornToBeRoot** [comment]
Hi @directmemory

what screen size / resolution do you have? I can't reproduce this on my screen with the taskbar on the left/right.

The main window has a min size of 1280x768, otherwise most dialogs and some views are unusable.

Greetings

**Comment by directmemory** [comment]
Hi @BornToBeRoot 
Resolution is 1920x1080, zoom-in 150%, which is recommended by Windows.

When i set it to 1920x1080, zoom-in 100%, the app seems good. So i think this is the root cause.

**Comment by BornToBeRoot** [comment]
Hi @directmemory,

i reduced the size of the main window. Hopefully this is enough to work with your resolution.

Fix is in the next release!

**Comment by BornToBeRoot** [comment]
PR: https://github.com/BornToBeRoot/NETworkManager/pull/1366
