### ISSUE TITLE
Chinese - Unable to set the language, select the target language, restart the application does not take effect

### ISSUE THREAD

**Issue by BornToBeRoot** [BornToBeRoot/NETworkManager#1281]
Unable to set the language, select the target language, restart the application does not take effect

_Originally posted by @itholl in https://github.com/BornToBeRoot/NETworkManager/discussions/453#discussioncomment-1505730_

**Comment by BornToBeRoot** [comment]
@itholl I cannot reproduce this in the current master. Maybe the files were not fully translated in the last release.

**Comment by zh-or** [comment]
是因为安装包里面没有中文语言包.
![image](https://user-images.githubusercontent.com/12293174/138835084-7f6ffc99-002a-49ab-ace0-d593dbaf0f25.png)

**Comment by BornToBeRoot** [comment]
@zh-or The language folders are available in the next release.

**Comment by BornToBeRoot** [comment]
@zh-or new version with chinese translation is released
