### ISSUE TITLE
Improve the discover protocols tab showing all protocols

### ISSUE THREAD

**Issue by samalkah** [BornToBeRoot/NETworkManager#1293]
Windows 10 has a built-in tool called pktmon.
The actual "Discover protocols" tab could directly use this tool so that we can see all packets et not only LLDP and CDP.

**Comment by BornToBeRoot** [comment]
pktmon is a win32 / command line application and not easy to integrate into an .NET application. I have already thought about a package capture (with PCAP), but there are other tools like wireshark which are much better (performance, fitlering, etc.) and are maintained by a large community.

The Discovery Protocol is meant to find out which switch a client is connected to (for e.g. if you go through a building with your notebook and check the network socket for each office).

Like this: https://borntoberoot.net/NETworkManager/Documentation/Application/DiscoveryProtocol

**Comment by samalkah** [comment]
Ok fine, that's interesting! Thanks
