### ISSUE TITLE
Add preset DNS

### ISSUE THREAD

**Issue by MS-PC** [BornToBeRoot/NETworkManager#130]
Add preset DNS, example:
Google Public DNS: 
IPv4: 8.8.8.8, 8.8.4.4
Cloudflare Public DNS: 
IPv4: 1.1.1.1, 1.0.0.1
And some more.

To show a "list of pre-established DNS", and put them easily with a click.

**Comment by BornToBeRoot** [comment]
I redesigned the dns lookup view...

![image](https://user-images.githubusercontent.com/16019165/46609300-c5e30800-cb07-11e8-8b59-3768a9d15ab3.png)

The list can be edited in the settings (add/edit/delete)

I think i will publish an update next weekend.
