### ISSUE TITLE
[New App] SNTP/NTP/NTPSec Client

### ISSUE THREAD

**Issue by MovGP0** [BornToBeRoot/NETworkManager#1300]
**Describe your feature request**:

There should be an SNTP client integrated to check the times of multiple servers and compare with the local time. 

Support should include IPv4 and IPv6 endpoints. 

**Stretch goals**:

Support NTPSec also.

**Comment by BornToBeRoot** [comment]
WIP #1821

**Comment by BornToBeRoot** [comment]
@MovGP0 the SNTP/NTP will be available in the next release! 🚀 Not sure if it make sense to implement NTPSec at this time (does not seem to be widely used) 

![image](https://user-images.githubusercontent.com/16019165/219219739-f801fb0b-2e38-4bed-9c04-44cd4ee66152.png)

![image](https://user-images.githubusercontent.com/16019165/219219821-d056f9b7-7ed4-43ca-9a80-46e2657ecc32.png)

![image](https://user-images.githubusercontent.com/16019165/219219872-8f356fd9-f572-48d9-a0cd-a4f0c5e3fb94.png)
