### ISSUE TITLE
Web Console : How to create profile in for Web Portals

### ISSUE THREAD

**Issue by pcsalim** [BornToBeRoot/NETworkManager#1301]
- I would like to know how we can create profile for web portals.
- I have added multiple hosts for monitoring with ping monitoring tool, but I am not able to select those profiles to the web console.
- If I try to add a new profile for the webpage then the save option fades out as per the below snapshot.

![image](https://user-images.githubusercontent.com/94428479/141935421-d9cfca60-dea6-40d7-9f4e-114d91d81d8a.png)
- But the save option is highlighted when I select the same for Ping Monitor

![image](https://user-images.githubusercontent.com/94428479/141935501-e1204385-8061-48f5-9baf-4c697972df5c.png)

- Please let me know if it is possible to create profile for the same or is that a feature which would be coming in the future versions.

**Comment by BornToBeRoot** [comment]
Hi, in the general tab you enter the hostname
![image](https://user-images.githubusercontent.com/16019165/142063162-ecb378f4-647f-43c4-b5ef-2af69294bdf8.png)

And in the WebConsole the URL (http://, https://)
![image](https://user-images.githubusercontent.com/16019165/142063228-7ce33b71-f18c-4c75-ba1a-ca64003afbbf.png)

**Comment by BornToBeRoot** [comment]
Then you can also use the hostname for ping, traceroute, dns etc... 

Webseite is special and has to be overwritten with an URI
