### ISSUE TITLE
Is it possible to build NetWorkManager for .NET 6 ?

### ISSUE THREAD

**Issue by mirogl** [BornToBeRoot/NETworkManager#1314]
Hi,
i wanted to test NetWorkManager on my Windows Arm64 machine. Therefore I tried on a x68 machine to build the current NetWorkManager  with Visual Studio 2022 and changed every project dependency from .NET 5 to .NET 6.
I got a lot of build errors.
Is is planned to have a .NET 6 release sometime ?

Thanks
Miro

**Comment by mirogl** [comment]
Hi,
I was able to compile it with .NET 6 by additionally changing the TargetFramework to

<TargetFramework>net6.0-windows10.0.22000</TargetFramework>

in NETworkManager.Converters.csproj

I can start the application with 
`dotnet NETworkManager.dll`
but just clicking NETworkManager.exe does nothing. Is this normal ?

Thanks
Miro

**Comment by BornToBeRoot** [comment]
Hi, 

The current master branch is on .NET 6 and now the first build with .NET 6 is released 
https://github.com/BornToBeRoot/NETworkManager/releases/tag/2021.11.30.0

You can run the `.\build.ps1` script to compile the solution. Currently the chinese translation is missing there due to a bug #1316 
If you compile it with VS everthing is ok.

You need to have .NET 6 Desktop Runtime installed to run the application. The NETworkManger.exe should work. Maybe it crashes (maybe there is something in the eventvwr --> application)

**Comment by mirogl** [comment]
Hi,
Thanks - yes there is a event viewer - also with this version:

```
`Description: A .NET application failed.
Application: NETworkManager.exe
Path: C:\Program Files\NETworkManager\NETworkManager.exe
Message: Failed to load the dll from [C:\Program Files\dotnet\host\fxr\6.0.0\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from C:\Program Files\dotnet\host\fxr\6.0.0\hostfxr.dll failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306
```
` 
also after reinstalling .NET.

But i can live with startting the application with dotnet 

Thanks
Miro

**Comment by BornToBeRoot** [comment]
Maybe a problem with the SDK? https://github.com/dotnet/sdk/issues/4240

Did you install 32 and 64 bit? My app is compiled as x64

I use this runtime: https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-6.0.0-windows-x64-installer

**Comment by mirogl** [comment]
Hi,
I compiled it myself for Windows arm64 with Visual Studio 2022 on a x64 pc - everything works, when started with dotnet - yes - perhaps a problem with the SDK. Many thanks

**Comment by BornToBeRoot** [comment]
Would be good to know if everthing works on ARM (wifi, remote desktop, putty, discovery protocol - i think the rest should work). Maybe i can provide binaries in a future release for it

**Comment by mirogl** [comment]
Hi, 
Mostly everything works, what i needed / tested - for your special requests

wifi - works
remote desktop - "connect" button is greyed out, even if i fill out hostname / username / password. 
putty - works - but the window is messed up, resized ok, if i resize NetWorkMAnager
discovery protocol - as administrator - no packets found - don´t know, if there should be any

Since i use putty / Remote Desktop as a seperate app - this is not really an issue für me.

Thanks#Miro
