### ISSUE TITLE
Unable to start the application

### ISSUE THREAD

**Issue by lordlightman** [BornToBeRoot/NETworkManager#1321]
Hello.

I want to try out your application, so I downloaded a portable version NETworkManager_2021.11.30.0_Portable. When starting the app for the first time I was greeted with this window:

![изображение](https://user-images.githubusercontent.com/88287379/146643234-7570e005-819d-45f1-af9c-9439fae0f51f.png)

where clicked yes, and got redirected to the page that offered me to [download .NET 6.0 Runtime](https://dotnet.microsoft.com/en-us/download/dotnet/6.0/runtime). So, I did download a 64-bit version and installed it.

After trying to start the app again I got another error message:

![изображение](https://user-images.githubusercontent.com/88287379/146643243-39bed0ba-0074-4f13-8318-b5b978e493cc.png)

where I clicked Yes, and got redirected to the same page with .NET 6.0 Runtime download. I tried installing x86 version as well, but still got the same error message.

Am I missing something here? Do I have to download some other runtime too?

**Comment by BornToBeRoot** [comment]
Hi @lordlightman ,

you need the desktop runtime (x64)

https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.1-windows-x64-installer

**Comment by lordlightman** [comment]
Thanks, that worked. Now I can use the app.
