### ISSUE TITLE
Ability to stop SNMP walk

### ISSUE THREAD

**Issue by chvvkumar** [BornToBeRoot/NETworkManager#135]
**Describe your issue or feature request**:
Stopping an ongoing SNMP walk (for example, when a host is not alive) so that a new scan can be run without having to wait for timeout.

**Steps to reproduce the issue**:

1. Initiate a SNMP walk 

**NETworkManager version**:

1.7.0.0

**Windows version**:

Wondows 10, build 17134.191

**Comment by BornToBeRoot** [comment]
Hi, i already opened an issue in the library i use.

https://github.com/lextm/sharpsnmplib/issues/74


Maybe i will find a workaround...

**Comment by chvvkumar** [comment]
Thank you!

**Comment by NickNiebling** [comment]
Are you considering adding a Cancellation Token to the Async methods?

@ncsurfus suggested an implementation in the (now deleted) "issue 74: How to cancel (async)?". The implementation can still be found here (not a pull request, but does show something that seems feasible):
https://gist.github.com/ncsurfus/b1b8dc14c1659e4acbc321a2e5b6ef48

The gist of that really being, that we can use register a second Task (internally) that will "complete" upon cancellation - and then just wait for the first task to complete (the cancellation token task vs the snmp request task) - effectively making us able to dispose the socket before we get a reply:
```
            var tcs = new TaskCompletionSource<bool>();
            using (var cancel = cancellationToken.Register(() => tcs.SetCanceled()))
            using (var socket = receiver.GetSocket())
            {
                var response = request.GetResponseAsync(receiver, socket);
                var result = await Task.WhenAny(tcs.Task, response);
                if (result == tcs.Task)
                    throw new TaskCanceledException(response);
                return await response;
            }
```

Above seems pretty straight forward (even though I haven't tried it yet). Is there a reason you don't do something like this? Will it not perform optimal or why was this suggestion disregarded?

**Comment by BornToBeRoot** [comment]
Maybe possible in .NET 6 with the latest #SNMPlib...

**Comment by BornToBeRoot** [comment]
It's possible with the library now 🚀 Will be available in the next release!
