### ISSUE TITLE
Install / Missing Frameworks 10.0 Desktop Runtime

### ISSUE THREAD

**Issue by rafaelsabino** [BornToBeRoot/NETworkManager#1364]
**Describe your issue**: 

**Steps to reproduce the issue**:

1. Install the program
2. Execute the program
3. Error .Net even being installed

**NETworkManager version**: NETworkManager_2021.11.30.0_Setup

**Windows version**: Windows 11

**.NET-Framework version**: Net-Framework Version 6.0

**Screenshots**

The screenshots are attached.
![Issue_001](https://user-images.githubusercontent.com/12975702/148770984-2bc4cf71-9af7-4fe3-a389-fd39e711b8f2.png)
![Issue_002](https://user-images.githubusercontent.com/12975702/148771007-f03f6900-51e1-4c6f-8cc8-c2bf22c53120.png)

<summary>Eventlog (if application crashes)</summary>

</details>

**Comment by RafalNiewinski** [comment]
Are you sure you have installed desktop applications runtime?
There are separate downloads for console and gui runtimes.

**Comment by BornToBeRoot** [comment]
Hi,

you need to install the .NET 6.0.x Desktop Runtime

See: https://github.com/BornToBeRoot/NETworkManager/issues/1321

 Direct link: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.1-windows-x64-installer

I can deliver a portable version of the framework with the app, but i would always have to distribute udpates as soon as a security update is provided by microsoft. When you install it, it updates itself via windows update.

**Comment by BornToBeRoot** [comment]
This one https://dotnet.microsoft.com/en-us/download/dotnet/6.0/runtime

![image](https://user-images.githubusercontent.com/16019165/148838159-fa3d42dc-4b36-4857-9c14-6563174d1366.png)

**Comment by BornToBeRoot** [comment]
Migrated from .NET 6.x to .NET 8.x

Link to the latest runtime: https://dotnet.microsoft.com/en-us/download/dotnet/8.0/runtime

![image](https://github.com/BornToBeRoot/NETworkManager/assets/16019165/164c9b1b-e09f-463a-ab70-7408a981ed7b)

**Comment by BornToBeRoot** [comment]
Migrated from .NET 8 to 10

Download / Install: https://dotnet.microsoft.com/en-us/download/dotnet/10.0/runtime
