### ISSUE TITLE
Magic packet successful sended!

### ISSUE THREAD

**Issue by TechRemedies** [BornToBeRoot/NETworkManager#137]
https://github.com/BornToBeRoot/NETworkManager/blob/3b1056039394e3dc1a0b11edd8013c6a45762562/Source/NETworkManager/Resources/Localization/Strings.resx#L946

Proper english would be "**Magic packet successfully sent!**" 

p.s. Thank you for all your work and a great tool!

**Comment by BornToBeRoot** [comment]
Thanks for the info!! My native language is german 😄 

Will be fixed in the next release!
