### ISSUE TITLE
Can not find lib AxMSTSCLib and MSTSCLib

### ISSUE THREAD

**Issue by aprilyush** [BornToBeRoot/NETworkManager#138]
I have download the code,when i  compile the code in vs ,can not pass, can not find the two libs

**Comment by BornToBeRoot** [comment]
Hi, there is a PowerShell script for the VS PreBuildCommandLine: 
https://github.com/BornToBeRoot/NETworkManager/blob/master/Scripts/PreBuildEventCommandLine.ps1

that should already be present / set

![image](https://user-images.githubusercontent.com/16019165/44926644-6ba99700-ad52-11e8-9061-1504de0f8860.png)

The script generates the `MSTSCLib.dll` and `AxMSTSCLib.dll` with the `aximp.exe` from the `mstscax.dll` in the `System32` folder, when you debug/build the solution in vs.


You need to download the whole source from github, not only the source-folder with the `NETworkManager.sln`


As alternative: You can copy the 2 dlls from one of the releases into the `bin\Debug` and `bin\Release` folder. Or use this command (cmd/powershell) to generate them: `aximp.exe C:\Windows\System32\mstscax.dll` 
The dlls are generated in the folder where you currently are. Then copy them into the Debug/Release folder....

The aximp.exe is somewhere in the `%ProgramFiles...%\Microsoft SDKs\Windows`

**Comment by BornToBeRoot** [comment]
@jasonyush could i help you?

I close the issue for now...
