### ISSUE TITLE
I have more device 

### ISSUE THREAD

**Issue by windsOne** [BornToBeRoot/NETworkManager#140]
Excuse me, if I have more than 50 devices
Get data through snmp
Determine online status by ping
What plans do you have to ensure that the device data can be updated at a certain frequency?
Or do you have any good framework to recommend to me? I am using Quartz now.

**Comment by windsOne** [comment]
This is a consultation
If you can give a reply, I will thank you very much.
Of course you can choose not to answer
I sincerely hope that you can give me some advice.
Because I am using 10 devices to get data, I should use a lot of cpu and memory.

**Comment by BornToBeRoot** [comment]
I do not know if I understand your question correctly. You want to monitor and/or make changes to multiple devices at once?

If you want to monitor (ping, snmp), maybe you should use something like nagios or centreon.
https://www.nagios.org/
https://github.com/centreon/

To update snmp data on many devices, you could write a script (PowerShell, Python) and run this as task... i use this libary (.NET) to perform snmp operations... 
https://github.com/lextm/sharpsnmplib

My tool was never designed to monitor devices, nor i have any plans to do so in future. Maybe i will add profiles for SNMP, but i dont know when.
