### ISSUE TITLE
installer garbled characters

### ISSUE THREAD

**Issue by ted423** [BornToBeRoot/NETworkManager#1413]
**Describe your issue**:
![image](https://user-images.githubusercontent.com/7042766/156166062-e16e2103-4ae2-4779-b0bf-2928b5c4b0e5.png)

**Steps to reproduce the issue**:

1.
2.
3.

**NETworkManager version**: 

**Windows version**:
win 10 (Chinese)
**.NET-Framework version**:

**Screenshots**

<details>
<summary>Eventlog (if application crashes)</summary>

</details>

**Comment by ted423** [comment]
There is no problem with the program itself

**Comment by BornToBeRoot** [comment]
Hi, this seems to be a problem of the installer "Inno-Setup" (or the language file). I can try to report it to them.

**Comment by lvzhenbo** [comment]
> Hi, this seems to be a problem of the installer "Inno-Setup" (or the language file). I can try to report it to them.

What is your text encoding environment?
Chinese requires utf-8 or utf-8 bom

**Comment by lvzhenbo** [comment]
I tried. You seem to use GBK, but you have to use utf-8 @BornToBeRoot

**Comment by BornToBeRoot** [comment]
@lvzhenbo thanks!

I use utf-8. After i downloaded the inno setup files again, they are now UTF-8 bom (according to vs code).

I am not sure if everything is correct, but here are some screenshots:

![image](https://user-images.githubusercontent.com/16019165/207965898-bb7a6822-8490-4f48-8cd2-ea810fb65173.png)

![image](https://user-images.githubusercontent.com/16019165/207965923-6b52f65d-be7a-44b5-82fc-871d4238f475.png)

![image](https://user-images.githubusercontent.com/16019165/207965939-d6981a41-a226-405b-96e6-39ba77b79729.png)

![image](https://user-images.githubusercontent.com/16019165/207966025-801cdfd1-2fb6-45da-923b-313e0e73bc46.png)

**Comment by lvzhenbo** [comment]
yes that is the correct character

**Comment by ted423** [comment]
thanks

**Comment by BornToBeRoot** [comment]
OK. Will be available in the next release!
