### ISSUE TITLE
Unable to start the application

### ISSUE THREAD

**Issue by NoFear23m** [BornToBeRoot/NETworkManager#1419]
Hello

I have tried the portable and also the Setup Version.
Version: 2022,2,22,0
Both wont start on my neu Maschine. On my Mashine a have also installed the Newest VisualStudio and the newest .Net 6 Framework.
I mean thats the problem. (Versioning) 

I start the app and..... nothing.
At the eventlog i get the following entry:

`Application: NETworkManager.exe
CoreCLR Version: 6.0.121.56705
.NET Version: 6.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException: Could not load file or assembly 'PresentationFramework, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'PresentationFramework, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'`

I Have tried to install the .Net 6.0.1 but without changes.

Thx
Sascha

**Comment by BornToBeRoot** [comment]
Hi, you need the .NET 6.0.2 Desktop Runtime (or later): https://github.com/BornToBeRoot/NETworkManager/issues/1364

There is currently an issue with .NET 6.0.0/6.0.1: https://github.com/dotnet/wpf/issues/6109
