### ISSUE TITLE
Eternally asking for already installed dependencies.

### ISSUE THREAD

**Issue by CaliburNS** [BornToBeRoot/NETworkManager#1420]
**Describe your issue**:
Installed NETWorkmanager and asked to fullfill .net dependencies by installing .net, even after it´s installed.

**Steps to reproduce the issue**:

1. Installed NETworkmanager
2. Start NETworkmanager
3. Asks for dependencies and to install them.
4. Install dependencies
5. Start NETworkmanager
6. Asks for dependencies and to install them.

**NETworkManager version**: 
Last one available to download.

**Windows version**:
10 20h2

**.NET-Framework version**:
Last available to download (6 and something, the one NETwork manager sent me URL to install)
**Screenshots**

<details>
<summary>Eventlog (if application crashes)</summary>

</details>

**Comment by BornToBeRoot** [comment]
Did you install the .net 6 Desktop Runtime or the normal runtime?

see: https://github.com/BornToBeRoot/NETworkManager/issues/1364

**Comment by Ghislain1** [comment]
.Net 6 Desktop Runtime
