### ISSUE TITLE
Cannot detect local IPv6 address 

### ISSUE THREAD

**Issue by Ghislain1** [BornToBeRoot/NETworkManager#1423]
**Describe your issue**:
Detect local IPv6 address throws Exception on runtime
**Steps to reproduce the issue**:

1. Clone or pull repro
2. Open Solution in Visual Studio (here 2022)
3. Start Application (F5) ---:> **System.NullReferenceException**: 'Object reference not set to an instance of an object.'

**NETworkManager version**: last commit 

**Windows version**: Windows 10 Enterprise

**.NET-Framework version**:

**Screenshots**

<details>
<summary>Eventlog (if application crashes)</summary>

</details>

**Comment by Alphabet85** [comment]
I added a MessageBox where the exception happens to give a little more information.

![image](https://user-images.githubusercontent.com/1330483/165333534-f8cb6323-6a59-418b-b684-2f6ec1598845.png)

It seems that the IPAddress parameter that gets passed through DetectGatewayBasedOnLocalIPAddress is null during start up.

**Comment by BornToBeRoot** [comment]
Hi @Alphabet85 & @Ghislain1 

this is fixed in the next release.

Code will be merged once the pipeline is completed if you want to test.

Greetings
