### ISSUE TITLE
Add NIC/MAC vendor column to IP Scanner

### ISSUE THREAD

**Issue by nicolafarina** [BornToBeRoot/NETworkManager#143]
Hi there,

I highly suggest to add a column to IP scanner section to resolve NIC/MAC vendor name, like many other ip scanners around: it's a very useful feature!

**Comment by BornToBeRoot** [comment]
You can enable it in the settings...

![image](https://user-images.githubusercontent.com/16019165/47267888-e1a7ce80-d549-11e8-9c67-4569362990a3.png)

![image](https://user-images.githubusercontent.com/16019165/47267909-2f243b80-d54a-11e8-8db9-b3fdb2bd05c1.png)

**Comment by nicolafarina** [comment]
Thank you very much for the answer.

Well, can be a "Show NIC vendor name" a more intuitive option label? Personally, I skipped that option thinking was related to scanning cache optimization.

Thanks.

**Comment by BornToBeRoot** [comment]
I will rename the setting. Thanks for your feedback!!

**Comment by nicolafarina** [comment]
It's a pleasure, a very good started project. As a sysadmin, I'm interested in switching to your app instead of some others. Please let me know if I can help more in testing.
