### ISSUE TITLE
Web console URL bar toggle button, hidden by default

### ISSUE THREAD

**Issue by VelliusG** [BornToBeRoot/NETworkManager#1438]
The web console URL bar is sort of a waste of interface real estate considering the fact that tabs keeps showing the original profile name even if you change websites.

The bar should be hidden by default and toggled on via an arrow button.

These web consoles are REALY nice when used to open embedded content like dashboards and monitoring interfaces.

**Comment by BornToBeRoot** [comment]
I agree with you. I could add an option in the settings to hide it completly or display just the url at the bottom. In some cases it makes sense to see on which url you are and maybe you need to edit it manually or go back. 
The View also needs a re-design and sometimes the url is not updated -.-

I don't have much time at the moment, but i'll take a look at it sometime.

**Comment by BornToBeRoot** [comment]
@VelliusG you can now hide the address bar in the settings

![image](https://user-images.githubusercontent.com/16019165/226191663-73d3c261-302c-4547-8a98-b3fcf2924abe.png)

![image](https://user-images.githubusercontent.com/16019165/226191700-7e35c64e-cbaa-438d-8571-3f48b7ddb5db.png)
