### ISSUE TITLE
Visual traceroute

### ISSUE THREAD

**Issue by nicolafarina** [BornToBeRoot/NETworkManager#144]
Would be great having a graphical map representation of hops around the world.

**Comment by BornToBeRoot** [comment]
Any idea how to do this? Are there public services available where i can check the geolocation of an ip address?

**Comment by RafalNiewinski** [comment]
GeoLite2 is one of possible solution

https://www.maxmind.com/en/open-source-data-and-api-for-ip-geolocation

**Comment by nicolafarina** [comment]
No idea, sorry.

**Comment by BornToBeRoot** [comment]
Visual traceroute might not be possible at this moment, but at least the geolocation of an ip would be nice.

I could implement a function to check an ip agains ipify.org (this is the same i use to determine the public ip).

The user needs to get an api key (1k request free / month) and can store it in the settings.
https://geo.ipify.org/pricing

@nicolafarina  @RafalNiewinski would this be an option?

**Comment by nicolafarina** [comment]
Thanks for considering @BornToBeRoot but I suppose that, if no free full database, this can be much less useful than what we though. I honestly think that development in this feature is not meaningful.

**Comment by RafalNiewinski** [comment]
I also think that this is not crucial. Maybe someday there will be idea with a better solution.

**Comment by BornToBeRoot** [comment]
@RafalNiewinski @nicolafarina better late than never. Here is a preview of the Geo-IP API in Traceroute (no graphic map, but all infos):
![Traceroute_Geo_Preview](https://github.com/BornToBeRoot/NETworkManager/assets/16019165/babf466a-1026-40af-9708-7f7549417f4e)

Will be available in the next release 🥳

**Comment by nicolafarina** [comment]
Great!

Thanks!

**Comment by BornToBeRoot** [comment]
@nicolafarina @RafalNiewinski In the next (pre) release there will be a map for the hops:
<img width="1200" height="800" alt="Image" src="https://github.com/user-attachments/assets/f0010868-7483-4427-a59c-30c0cc69d0ad" />

**Comment by nicolafarina** [comment]
Sounds great!!!!

**Comment by RafalNiewinski** [comment]
Nice, few years later and idea is still alive.. lovely
