### ISSUE TITLE
Settings not saved

### ISSUE THREAD

**Issue by BornToBeRoot** [BornToBeRoot/NETworkManager#1443]
Same for restarting forced by the change in the settings. If the app asks for the restart, settings lost. Spent few hours defining custom ports, DNS etc - all lost.

_Originally posted by @gitthangbaby in https://github.com/BornToBeRoot/NETworkManager/issues/33#issuecomment-1129266796_

**Comment by BornToBeRoot** [comment]
Hi @gitthangbaby

i can't reproduce this issue. 

Can you describe step by step what you did or show a video/gif?

**Comment by BornToBeRoot** [comment]
Hi @gitthangbaby,

i think i found an issue with the forced restart. 
Maybe this also fixes also your issue. Fix will be in the next release.

**Comment by gitthangbaby** [comment]
> Hi @gitthangbaby,
> 
> i think i found an issue with the forced restart. Maybe this also fixes also your issue. Fix will be in the next release.

thanks!  i thought i posted reply, i actually was testing it on 2022.2.22.0 and had an issue to reproduce it.. i found 2 ways only to restart: language change, and discovery protocol, but no "luck". i forgot the original steps. glad that you found something.
