### ISSUE TITLE
Add Possibility to change the language on the fly

### ISSUE THREAD

**Issue by Ghislain1** [BornToBeRoot/NETworkManager#1448]
**Describe your feature request**:
The end-user should be able to switch app language on the fly ( Not need to restart the app)

**Comment by BornToBeRoot** [comment]
This is only possible for dynamic ressources (e.g. labels/textboxes in the ui), but not for some ressources like lists who are generated when the app/view starts. Then the UI is in two languages until the next start.

The effort to implement this for all resources is for me in no relation to the one-time restart. There are still some features to implement that I would prioritize here.

The language should also be initially set to the windows language (if available - fallback is always english).

I can look at it again sometime. Currently I have little time. (PRs are welcome)

**Comment by BornToBeRoot** [comment]
Hello @Ghislain1 , 

after thinking about it further, the effort is very small compared to the benefit. I would like to take care of new / more important feature that bring real added value.
Also, the application needs to be restarted once to load static strings (e.g. in lists, etc.) correctly. WPF can do this on the fly, but if you use strings in the code behind it, you need to implement a lot of checks / refresh / etc.
At first startup the language of the operating system should be adopted. If this is not the case, the application will be restarted at most one more time when the language is chosen.
If there is a problem here, we can look at it. 

But thanks for the suggestions!

Greetings
