### ISSUE TITLE
Status icon and notifications for ping 

### ISSUE THREAD

**Issue by nicolafarina** [BornToBeRoot/NETworkManager#145]
Would be great having a status icon and notifications when ping goes up and down. Very useful when simply monitoring an host.

Take a look at: EMCO Ping Monitor (https://emcosoftware.com/ping-monitor)

**Comment by BornToBeRoot** [comment]
How about this? A notification will follow: #194

![image](https://user-images.githubusercontent.com/16019165/67151680-bfb26a80-f2c9-11e9-884c-46f2bec37d74.png)

**Comment by BornToBeRoot** [comment]
Here is a pre version with this feature: https://github.com/BornToBeRoot/NETworkManager/releases/tag/v2.0.0-pre001

**Comment by nicolafarina** [comment]
Sorry for delay. It seems very good. A systray icon would be great for reporting if one pinged host is down (red/green f.e.).
