### ISSUE TITLE
open solution build out of the box runtime fails

### ISSUE THREAD

**Issue by foxjazz** [BornToBeRoot/NETworkManager#1450]
**Describe your issue**:

**Steps to reproduce the issue**:

1.open solution run
2.         string computerIPv6 = Models.Network.NetworkInterface.DetectLocalIPAddressBasedOnRouting(IPAddress.Parse(SettingsManager.Current.Dashboard_PublicIPv6Address)).ToString();
 
vs 2022

**Comment by BornToBeRoot** [comment]
You can click on `continue` (F5). This might be fixed with #1423 

Edit: Exception is catched with a try/catch.
