### ISSUE TITLE
PowerShell - Improvements

### ISSUE THREAD

**Issue by BornToBeRoot** [BornToBeRoot/NETworkManager#1457]
ToDo
- [x] Resize embedded windows (like putty)
- [x] Restart embedded PowerShell (like putty)
- [x] Profile - Check inherit from default by default

**Comment by hpmillaard** [comment]
what about different credentials?

**Comment by BornToBeRoot** [comment]
Hi @hpmillaard,

the problem with credentials is, that you have to pass them as variable and they will be exposed in the task manager (command line for the process). This is the same problem with PuTTY.
