### ISSUE TITLE
Status icon IP configuration popup window

### ISSUE THREAD

**Issue by nicolafarina** [BornToBeRoot/NETworkManager#147]
Would be great having a systray icon on which you can mouse hover to raise a popup window containing NICs IP configuration.

Take a look: https://www.netsetman.com/en/freeware

**Comment by BornToBeRoot** [comment]
There is already a status window... it will appear, when the network has changed... but you can also open it via context menu, when the tray icon is enabled in the settings.

![image](https://user-images.githubusercontent.com/16019165/67151749-80384e00-f2ca-11e9-997d-a90014033c57.png)

![image](https://user-images.githubusercontent.com/16019165/67151751-89291f80-f2ca-11e9-8cc9-e75ac2989010.png)

**Comment by nicolafarina** [comment]
Great, thanks!
