### ISSUE TITLE
Port scan automatically when scanning IP

### ISSUE THREAD

**Issue by nicolafarina** [BornToBeRoot/NETworkManager#148]
An option to execute a port scan on each scanned alive IP would be great instead of port scan each.

Taka a look: https://www.advanced-ip-scanner.com/

**Comment by BornToBeRoot** [comment]
The port scanner allows multiple hosts as input. Maybe i can add support for subnets like the ip scanner does `192.168.0.0/24`

**Comment by nicolafarina** [comment]
Could be an idea. I think that having a sub-list of each scanned ip would be more intuitive (opened with a plus icon next to them).

Thanks for considering.

**Comment by BornToBeRoot** [comment]
The port scanner now allows input like `192.168.178.0-192.168.178.100` or `example.com/24`. (same strings as the IP Scanner)

Dev branch: https://github.com/BornToBeRoot/NETworkManager/tree/develop-v1.9.0.0
Will be available in the next release...

I would like to keep the IP scanner separated from the Port scanner.

**Comment by nicolafarina** [comment]
Sorry for returning on this, but consider that when using ip scanner for finding specific devices (f.e. NAS, switch, firewall, etc.) having an indication of which ports are opened is a killing feature. Obviously, with a selection of which ports (80, 443, 22 can be a default).

Having this within scanner feature instead of specific port scan one is crucial because MAC address vendor resolution.

This feature is the only one why I'm using Advanced Network Scanner (https://www.advanced-ip-scanner.com/) instead of your much more capable software for network scanning.

Really thanks for considering and sorry to bother you but I hope to help improve for many sysadmins.

**Comment by BornToBeRoot** [comment]
Maybe with this: #245

**Comment by nicolafarina** [comment]
I suppose that using "nmap -p 80 xxx.xxx.xxx.xxx" (f.e.) could be viable way. Maybe an option directly near ip range textbox like "scan default management ports also" could be added, with relative ports settings in settings pane to specify whic "management ports" to consider (default could be 80, 443, 22).
