### ISSUE TITLE
Export data from IP-Scanner, Port-Scanner, etc. 

### ISSUE THREAD

**Issue by stmanuel** [BornToBeRoot/NETworkManager#150]
When trying to copy data, NetworkManager does not copy all data to clipboard. It was missing most of the IP's and hostnames and only had the response time

Would be awesome if there was an Export to file option (Text, CSV, or Excel)

Steps to reproduce the issue:

1. Scan subnet
2. Ctrl+A to select all results
3. Ctrl+C to copy to clipboard
4. Paste into Excel /notepad

**NETworkManager version**:
1.8.0.0

**Windows version**:
10 

**.NET-Framework version**:
4.7

**Screenshots**

<details>
<summary>Eventlog (if application crashes)</summary>

</details>

**Comment by BornToBeRoot** [comment]
Ctrl+A and paste this in Excel works for me fine.

An export function would be better, I think ... It's already on my ToDo list...

**Comment by BornToBeRoot** [comment]
Current progress in dev branch:

- [x] IP Scanner
- [x] Port Scanner
- [x] Ping
- [x] Traceroute
- [x] DNS Lookup
- [x] SNMP
- [x] HTTP Headers
- [x] Whois
- [x] Subnet Calculator - Subnetting
- [x] Lookup - OUI
- [x] Lookup - Port
- [x] Connections
- [x] Listeners
- [x] ARP Table

Context menu
![image](https://user-images.githubusercontent.com/16019165/48022109-92ad8c00-e13a-11e8-9331-f4767592d3de.png)

Export dialog
![image](https://user-images.githubusercontent.com/16019165/48022163-ba045900-e13a-11e8-8e47-b9e3765cae0d.png)

**Comment by BornToBeRoot** [comment]
@stmanuel Export feature will be available with the next update.
