### ISSUE TITLE
[New App/Extension] Whois IP

### ISSUE THREAD

**Issue by hpmillaard** [BornToBeRoot/NETworkManager#1522]
Could you create the possability to do a whois query for an IP from RIPE?

**Comment by Sahnreis** [comment]
I looked into the API docs for the RIPE REST Api - i think i could implement this feature. Can i go ahead?

**Comment by BornToBeRoot** [comment]
Sure :)

**Comment by BornToBeRoot** [comment]
Query for IP Geolocation is now available: https://borntoberoot.net/NETworkManager/Documentation/Application/IPGeolocation

**Comment by BornToBeRoot** [comment]
Closed for now. There is no freely usable data for the IP addresses. 

The RIPE API only provides data for some of the address ranges.

The Geolocation IP was implemented and is available in the latest release!
