### ISSUE TITLE
IP-Scanner: Sort results by hostname does not work

### ISSUE THREAD

**Issue by EaranMaleasi** [BornToBeRoot/NETworkManager#155]
**Describe your issue or feature request**:
Clicking on "Hostname" in the result list of the IP-Scanner results in a list, that isn't sorted at all. Names are all over the place, and a second click does not reverse that order, or do anything at all.

**Steps to reproduce the issue**:
1. Open IP-Scanner
2. Scan so that multiple devices are shown
3. Klick on Hostname to see some weird results
4. Klick on Hostname again to see that nothing changed

**NETworkManager version**:
1.8.1.0

**Windows version**:
Windows 10 Pro 1803 (Build 17134.345)

**.NET-Framework version**:
.NET 4.7.2

**Comment by BornToBeRoot** [comment]
Thanks for your bug report!

Fix is in dev branch. (https://github.com/BornToBeRoot/NETworkManager/commit/2b01797a4bc9c1c6db48fbe26b44ca1db0eebd3e)

I also fixed the sort by **MACAddress** and **Vendor**.

Will be available in the next release!
