### ISSUE TITLE
Installer issue - License showed with too many CR/LF

### ISSUE THREAD

**Issue by bovirus** [BornToBeRoot/NETworkManager#1561]
**Describe your issue**:

Please check screenshot.
GNU license is formatted probably for 80 chars and there is an empty area not used.

**Steps to reproduce the issue**:

1.
2.
3.

**NETworkManager version**: 

**Windows version**:

**.NET-Framework version**:

**Screenshots**

![image](https://user-images.githubusercontent.com/1262554/190893456-958942b5-006f-46e0-a453-7f46078c9b8b.png)

<details>
<summary>Eventlog (if application crashes)</summary>

@BornToBeRoot 

Please format doc to use all space available.

</details>

**Comment by BornToBeRoot** [comment]
Hi @bovirus,

this is because the installer (InnoSetup) uses the default license file from GitHub (and also displays it the same): https://github.com/BornToBeRoot/NETworkManager/blob/main/LICENSE

I don't see any advantage to fix that now. Most of the people click here anyway to continue.

**Comment by bovirus** [comment]
@BornToBeRoot 

The issues is related about very very old (2007 - 15 yers ago - many ages ago) format (text 80 charcaters for each line) of license file.

I believe that the author of this file should update it using automatic wordwrap and new line for each paragraph.

less old format.

**Comment by BornToBeRoot** [comment]
@bovirus file updated.
