### ISSUE TITLE
Editable DNS textbox in "DNS Lookup" section

### ISSUE THREAD

**Issue by nicolafarina** [BornToBeRoot/NETworkManager#158]
Would be useful to instantly customize the DNS server (making the drodown textbox editable) for lookup instead of precompiled ones only.

Thanks.

**Comment by BornToBeRoot** [comment]
You can add/delete dns servers in the settings. 

![image](https://user-images.githubusercontent.com/16019165/48713896-b9c38d80-ec11-11e8-97fb-cc8cb2e73a61.png)

**Comment by nicolafarina** [comment]
Sure, but I think that for random checking against specific servers would be much more rapid to edit (and not saving) the dropdown textbox instead of edit the general setting.

Thanks.
