### ISSUE TITLE
Export IPScanner/PortScanner/Traceroute/etc. not working for some paths

### ISSUE THREAD

**Issue by thongor77** [BornToBeRoot/NETworkManager#1606]
**Describe your issue**:
after doing a port scanner , i wanted to export the list

**Steps to reproduce the issue**:

1. do a network scan
2. select all lines, right click and select export
3. select the format you want and select the location
4.  Export button not available

**NETworkManager version**: 
2022.8.18.0
**Windows version**:
10 -21H2
**.NET-Framework version**:
6

**Screenshots**
![image](https://user-images.githubusercontent.com/91029540/195332565-041f4def-22f4-40b7-af23-35c8294266f7.png)

**Comment by BornToBeRoot** [comment]
@thongor77 can you try a path without the `&`? I think there is a bug in the validator -.-

**Comment by BornToBeRoot** [comment]
Line with the "bug": https://github.com/BornToBeRoot/NETworkManager/blob/f8887737b450ae6d3cb308eddeefcfdfef409a43/Source/NETworkManager.Utilities/RegexHelper.cs#L87-L88

Possible fix: https://www.codeproject.com/Tips/216238/Regular-Expression-to-Validate-File-Path-and-Exten?msg=4515001#xx4515001xx

**Comment by thongor77** [comment]
> 

you right it works when the is no special characters in the path

**Comment by BornToBeRoot** [comment]
Thanks for the feedback. I fix this ASAP for the next release.
