### ISSUE TITLE
[New App] calculator/converter for bits to kilobits, megabits, etc.

### ISSUE THREAD

**Issue by odoolantel** [BornToBeRoot/NETworkManager#1620]
**Describe your feature request**:
Hi, is het possible to add a converter for bits to megabits, kilobits, etc.

like this website: https://www.matisse.net/bitcalc/

This would be very welcome.

Thank you in advance.

**Comment by BornToBeRoot** [comment]
@odoolantel - This feature will be in the next release!

![image](https://user-images.githubusercontent.com/16019165/201445409-c372ef56-5023-44d0-8420-f035087110bc.png)

![image](https://user-images.githubusercontent.com/16019165/201445428-d69b091b-5902-4004-a2cc-04ecc8ad7269.png)
