### ISSUE TITLE
Show disabled interfaces

### ISSUE THREAD

**Issue by delirium26** [BornToBeRoot/NETworkManager#169]
Unfortunately GetAllNetworkInterfaces() function doesn't list disabled interfaces.
I almost done this feature with wmi Query. Soon I`ll can do pull request.
Also, did we need ability to enable/disable interface in Interface Configuration tab? It seems pretty usefull for me.

**Comment by BornToBeRoot** [comment]
Disable/Enable a network adapter would be great. 

Changing a network adapter (disable/enable) requires administrative rights. I would call a PowerShell as Admin with a command to enable/disable the adapter. (like the interface configuration)

Thus NETworkManager itself does not have to be started as admin.

https://github.com/BornToBeRoot/NETworkManager/blob/99f7a44ccf76827200110992a84dd97b99536c82/Source/NETworkManager/Utilities/PowerShellHelper.cs

Via `netsh.exe` or Windows 10 has build in PowerShell commands to do this: 
`Get-NetAdapter` 
`Enable-NetAdapter` 
`Disable-NetAdapter` 

---
Once .NET Core 3 (or .NET Framework 4.8) is released, i want to migrate the project (there is already a pull request) and start with Version 2.0.0.0

This has the advantage that we can use the Windows 10 API (aka WinRT).
- NativeWiFi --> Show/Configure WiFi Networks

Maybe there are new functions for the network adapters...

But... Windows 7, 8.1 are no longer supported then...

**Comment by delirium26** [comment]
> Changing a network adapter (disable/enable) requires administrative rights. I would call a PowerShell as Admin with a command to enable/disable the adapter. (like the interface configuration)
Thus NETworkManager itself does not have to be started as admin.
https://github.com/BornToBeRoot/NETworkManager/blob/99f7a44ccf76827200110992a84dd97b99536c82/Source/NETworkManager/Utilities/PowerShellHelper.cs

I just thought about it yesterday, thanks for the tip.

> But... Windows 7, 8.1 are no longer supported then...

It's a pity. I use Windows 10 almost everywhere. But according to this http://gs.statcounter.com/windows-version-market-share/desktop/worldwide  the percentage of windows 10 usage is slightly above 50%.
Also it will impossible to run on Windows Server 2008 R2?

Anyway, long time I wanted develop tool like NetworkManager, but a little bit lightweighted. So it another cause to do it.

**Comment by BornToBeRoot** [comment]
It won't run on Server 2008 R2... but you can still download the latest version 1.9.x.x which can run under Windows 7 / 2008 R2.

Only newer features requires Windows 10...

**Comment by BornToBeRoot** [comment]
@delirium26 

I added a button "Network connections..." which opens **Control Panel > Network and Internet > Network Connections**

![image](https://user-images.githubusercontent.com/16019165/55266970-ed798880-527f-11e9-8cdc-9a26aedee292.png)

If no adapter is enabled, this message is shown on all tabs:

![image](https://user-images.githubusercontent.com/16019165/55267069-5a8d1e00-5280-11e9-8b00-4082bc3ab17e.png)

The status of this pages are changing as soon as a network adapter is enabled/disabled.


If you want, you can still add the feature to disable/enable a adapter...
