### ISSUE TITLE
Unable to edit NetworkInterfaceView.xaml in VS under certain circumstances

### ISSUE THREAD

**Issue by delirium26** [BornToBeRoot/NETworkManager#170]
**Describe your issue or feature request**:
It is not possible to edit the NetworkInterfaceView.xaml in VS under certain circumstances.

**Steps to reproduce the issue**:

1. Enable disconnected network interfaces(not sure)
2. Try to open NetworkInterfaceView.xaml
3. NullReferenceException error

**NETworkManager version**:
1.8.3.0
**Windows version**:
Microsoft Windows 10 Pro N 10.0.17763
**.NET-Framework version**:
4.7.03190
**Screenshots**
![screenshot 2019-01-30 18 27 36](https://user-images.githubusercontent.com/3222850/51992237-b3794980-24bd-11e9-94e2-4da1c1b82669.png)
![screenshot 2019-01-30 18 28 02](https://user-images.githubusercontent.com/3222850/51992238-b3794980-24bd-11e9-8baa-1c890005ebd8.png)

But this does not interfere with building project. So it not critical, but sometimes annoying. I'll try discover circumstances of bug later.

**Comment by BornToBeRoot** [comment]
I will take a look... The "IPAddressArrayToStringConverter" throws the exception.

If you develop... please use the [current dev-branch](https://github.com/BornToBeRoot/NETworkManager/tree/develop-v1.9.0.0). It will be easier for me to merge pull requests.

**Comment by BornToBeRoot** [comment]
Can you try this fix: https://github.com/BornToBeRoot/NETworkManager/commit/3c949047833f5c36f8fe1fab343d4187f4517b99

You need to restart VS and maybe delete the /bin and /obj folder.

**Comment by BornToBeRoot** [comment]
Fix is in current dev branch.

https://github.com/BornToBeRoot/NETworkManager/pull/171
