### ISSUE TITLE
Dragablz - Tab is locked / unable to switch tabs

### ISSUE THREAD

**Issue by sunilkalra123** [BornToBeRoot/NETworkManager#1702]
**Describe your issue**:
since the latest update that fixed the focusing issues when using terminal/powershell, i have not been able to switch tabs.

Eg, if i open ssh 1 and ssh2, focus is automatically in ssh2. i cant now click on the ssh1 tab to give it focus, i can only do this by closing ssh2

**Steps to reproduce the issue**:

1.
2.
3.

**NETworkManager version**: 
2202.10.31.0
**Windows version**:
10 21h2
**.NET-Framework version**:
4.8
**Screenshots**

<details>
<summary>Eventlog (if application crashes)</summary>

</details>

**Comment by BornToBeRoot** [comment]
Hi @sunilkalra123,

i think this is a bug in the library which occurs under certain circumstances:
https://github.com/ButchersBoy/Dragablz/issues/132

I can reproduce it and see if I can fix it.

Greetings.
