### ISSUE TITLE
i cant run it on windows11,  when i double click it ,but  nothing happen

### ISSUE THREAD

**Issue by PeroPer0** [BornToBeRoot/NETworkManager#1728]
**Describe your issue**:

**Steps to reproduce the issue**:

1.
2.
3.

**NETworkManager version**: 
2022.10.31.0
**Windows version**:
windows 11 pro
**.NET-Framework version**:

**Screenshots**

<details>
<summary>Eventlog (if application crashes)</summary>

</details>

**Comment by BornToBeRoot** [comment]
Hi @PeroPer0,

is there an error in `%LocalAppData%\NETworkManager\NETworkmanager.log` or in the `windows event log \ application` (2 entries if the app crashes)?

If yes, can you send it to me.

**Comment by PeroPer0** [comment]
I try to reinstall with the binary installer and now I can  run it ,thanks

**Comment by BornToBeRoot** [comment]
Great!
