### ISSUE TITLE
Save Settings/Profiles/Credentials in background every x minutes

### ISSUE THREAD

**Issue by BornToBeRoot** [BornToBeRoot/NETworkManager#173]
Save automatically settings/profiles/credentials in the background...

With a timer every 5 Minutes?

**Comment by RafalNiewinski** [comment]
Maybe when change occurs?

**Comment by BornToBeRoot** [comment]
Some settings (like window size, expand profile view etc.) don't need to be saved on every change.

This background job could also be used to run other things...

For profiles/credentials this would be a good idea. They are currently only saved when closing the application or when the settings/import-export tab in the settings is opened.

I think my application is stable enough to cache profiles/credentials and save them every x-minutes to the file system. 

Currently the default value is 15 minutes.
