### ISSUE TITLE
The name is misleading, maybe NetworkViewer would be more appropriate

### ISSUE THREAD

**Issue by lost22git** [BornToBeRoot/NETworkManager#1730]

**Comment by BornToBeRoot** [comment]
Why is it misleading?

You see a lot of informations about your client and you network, but you can also use it to connect via RDP, SSH, VNC, PowerShell, AWS SSM to your server/clients/network devices/etc. to manage them.

Edit:
At this point, however, I will not change the name either. Thanks for the feedback anyway!
