### ISSUE TITLE
GUI issue: DNSLookup - Column named 'Results': unable to display long value

### ISSUE THREAD

**Issue by jbvernejoux** [BornToBeRoot/NETworkManager#182]
**Describe your issue or feature request**:
Bug in GUI : DNS lookup / Results column's Width not automatically sized to max length of the text content.

**Steps to reproduce the issue**:
1. launch Network Manager in a low windowed size ( NOT in a maximized windows size or Fullscreen mode)
2. switch to DNS lookup pane
3. launch a query for MX record (or ANY type) for gmail.com or any DNS domain with long value in MX DNS record
4. The text shown in Result column is truncated AND the column's width is not RESIZABLE to display all the content.  See attached image

**Workaround**
You had to change the size of the app (enlarge the window) to force a gui refresh and to have a good width and the whole text .

**NETworkManager version**:
1.9.0.0
**Windows version**:
Windows 10 x64 , v1809 , build 17763.379
**.NET-Framework version**:
4.7.x
**Screenshots**
![NETworkManager_2019-03-29_15-05-38](https://user-images.githubusercontent.com/26932664/55238802-a8306900-5235-11e9-8afd-28bd45d9f9c5.png)

<details>
<summary>Eventlog (if application crashes)</summary>

</details>

**Comment by BornToBeRoot** [comment]
Thanks for the detailed report.

Fixed in the next version!
