### ISSUE TITLE
[New App] UPNP/Bonjour explorer

### ISSUE THREAD

**Issue by si458** [BornToBeRoot/NETworkManager#1837]
**Describe your feature request**:
it would be amazing to have an option to browse UPNP devices and also Bonjour 

browse bonjour objects: https://hobbyistsoftware.com/bonjourbrowser
show upnp ports: https://www.xldevelopment.net/upnpwiz.php
show upno devices: https://apps.microsoft.com/store/detail/upnp-analyser/9NBLGGH69PDN?hl=en-us&gl=us

**Comment by BornToBeRoot** [comment]
Thanks @si458 for the feature request.

At this point i have no plans to implement this.

1) UPNP shouldn't be enabled in any network and fortunately my router does not support this function either.
2) I don't have any apple devices and therefore no environment for Bonjour to test.

If someone wants to implement these features, they can send a pull request at any time.
