### ISSUE TITLE
Request for RDP experience settings

### ISSUE THREAD

**Issue by Jogai** [BornToBeRoot/NETworkManager#187]
![image](https://i.stack.imgur.com/ZHv7Y.png)

Image found on superuser. I usually untick most of the options, but with NETworkManager I cant.

**Comment by BornToBeRoot** [comment]
This should be possible. But I have to add some settings...

It also lookt different on Windows 10

![image](https://user-images.githubusercontent.com/16019165/55500642-0059d780-5649-11e9-8a70-69316059d243.png)

**Comment by Jogai** [comment]
True, the request is mostly for adding the different checkboxes to the settings. The presets arent that important to me, and it might be easier to just do the toggle because there is a list of toggles already.

**Comment by BornToBeRoot** [comment]
@Jogai 

Remote audio
![image](https://user-images.githubusercontent.com/16019165/56474628-9761c480-647c-11e9-82ed-0b8980f3472a.png)


Performance settings
![image](https://user-images.githubusercontent.com/16019165/56474631-ac3e5800-647c-11e9-986c-6bad24e2297c.png)
