### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Getr3ktbyMe** [BornToBeRoot/NETworkManager#188]
Hey,
I started to write a documentary, at first only in German. Can I somehow send them to you in the next few weeks?

**Comment by BornToBeRoot** [comment]
Hi,

du kannst mir gerne einen Pull Request senden. Wenn die erstmal nicht öffentlich sein soll, kann ich dir auch gerne einen Link zum Hochladen über meine cloud geben.

Ich hab auch gesehen, dass du eine neue Sprache auf Transifex angefordert hast. Da dein Profil auf privat gestellt ist, kann ich dich nicht hinzufügen. Du kannst aber eine Anfrage über Transifex stellen um dem Team nl_NL beizutreten oder du änderst deine Profil Einstellungen.

Ich kann dich auch via E-Mail-Adresse hinzufügen, dazu müsstest du mir diese aber schicken. Eventuell via Nachricht in Transifex oder via Twitter (https://twitter.com/BornToBeRoot_DE) als private Nachricht.


Edit:
Die Deutsche Programm-Überstzung auf Transifex wollte ich vorerst selbst machen. Manche Übersetzungen ergeben erst Sinn, wenn man den Kontext kennt. 
Du kannst dich aber gerne um die Sprache nl_NL kümmern.
