### ISSUE TITLE
Whether "IP monitoring" can be added in bulk?

### ISSUE THREAD

**Issue by msglog** [BornToBeRoot/NETworkManager#1904]
Whether "IP monitoring" can be added in bulk?
<img width="755" alt="pic_2023-02-11_16-40-24" src="https://user-images.githubusercontent.com/34530046/218248928-1d79a9bb-1a02-4d0f-af2d-f7f93d616f4b.png">

**Comment by BornToBeRoot** [comment]
@msglog would it make sense to allow multipe IPs / Hosts as input like the IP Scanner: https://borntoberoot.net/NETworkManager/Documentation/Application/IPScanner

Something like `Host1;  Host2; Host3` and maybe `10.[1-10].0.1.`.
Then you can also save this in the profiles like `All DNS servers` or `All DCs`.

I think it doesn't make sense to run a ping agains a whole subnet (like `/24`). Then you could also use the IP scanner to check if something is online.

**Comment by msglog** [comment]
> 

Not a subnet，see  sample：   192.168.21.15;    172.15.15.15;   230,15.15.15
A number of different IP network segment
----
Sorry, my“Previous example” is not normal

**Comment by BornToBeRoot** [comment]
Should be easy to implement. I will try to add it for the next release. Thanks for the feedback!

**Comment by BornToBeRoot** [comment]
![PingMonitor](https://user-images.githubusercontent.com/16019165/219905544-09ea02bb-5f36-4673-8c51-860e5078c8a4.gif)
