### ISSUE TITLE
Migration to .net core 3 WPF

### ISSUE THREAD

**Issue by ktngoykalolo** [BornToBeRoot/NETworkManager#197]
**Describe your feature request**:
Hi,
great tool,
gotta think about moving the tool to .net core 3 and WPF support.

Looking forward to it!!

**Comment by BornToBeRoot** [comment]
Hi,

here is a branch for .net core 3:

PR: https://github.com/BornToBeRoot/NETworkManager/pull/160
Branch: https://github.com/BornToBeRoot/NETworkManager/tree/netcore3-example


Microsoft already announced .NET 5 (combinding .NET-Framework and .NET-Core), i think it doesn't make sense at this point migrating the project to .NET-Core 3... I will wait for .NET 5

Greetings
