### ISSUE TITLE
Anti-virus blocking the software

### ISSUE THREAD

**Issue by ktngoykalolo** [BornToBeRoot/NETworkManager#198]
**Describe your issue**:
Hi,
got the software removed by anti-virus.
how can we ensure the software is clean ?
**Steps to reproduce the issue**:

1.
2.
3.

**NETworkManager version**: 

**Windows version**:

**.NET-Framework version**:

**Screenshots**

<details>
<summary>Eventlog (if application crashes)</summary>

</details>

**Comment by BornToBeRoot** [comment]
Would be interesting which anti-virus you are using and what the exact message is... maybe a false positive?


Here is a virustotal scan from the latest release:

* [Portable / Binaries](https://www.virustotal.com/gui/file-analysis/MWJjYjQzNzIwYjdmOWY0N2I4ZjUxMWFmN2NlZWI2OWE6MTU2MDc1OTg5MQ==/detection)
* [MSI](https://www.virustotal.com/gui/file/ca3c88b20a044d4652b4622557238240ea805546827fa5286c2b86bd05ffe5d0/detection)

I test my program agains Windows Defender and Kaspersky.

If you don't trust my binaries, you can download the source code and build the solution by yourself, that's the good thing about open source :)

**Comment by BornToBeRoot** [comment]
Feel free to open this issue again, if you can give me more informations (e.g. which anti virus program)
