### ISSUE TITLE
WiFi

### ISSUE THREAD

**Issue by a44281071** [BornToBeRoot/NETworkManager#204]
**Describe your feature request**:
feature:
1. show WIFI list and details, and connect.
2. create and open visual router in windows. like win10 share network.

**Comment by BornToBeRoot** [comment]
Hi,

1. It's on the road map... but i don't know when it will be available.
2. You mean something like a hotsport feature?

Greetings

**Comment by a44281071** [comment]
yeah, not only Ethernet, but also Wireless。
like wifi manager. virtual AP.

**Comment by BornToBeRoot** [comment]
OK. I plan this feature for version 2... i need to drop Windows 7 support, to use the Windows.Devices.WiFi API. Maybe at the end of the year...

-- note to my future self -- 
API: https://docs.microsoft.com/en-us/uwp/api/windows.devices.wifi
Package: https://www.nuget.org/packages/Microsoft.Windows.SDK.Contracts
Docs: https://www.thomasclaudiushuber.com/2019/04/26/calling-windows-10-apis-from-your-wpf-application/

**Comment by BornToBeRoot** [comment]
Here is a preview... i plan to add a separate view to show the wifi channels.

![WiFi](https://user-images.githubusercontent.com/16019165/63124103-c6abbc80-bfaa-11e9-914d-eef04055c3df.PNG)

![WiFi_Channel](https://user-images.githubusercontent.com/16019165/64206000-9b293d00-ce99-11e9-9389-a82d1be054e0.PNG)

ToDo:

- [x] Show note if no wifi adapter is available
- [x] Show note if no wifi network is available
- [x] Convert "Phy types" to 802.11??
- [x] Fix scrollbar margin
- [ ] Fix "System.Threading.Tasks.TaskCanceledException: 'A task was canceled.'"
- [ ] ~~Show Mbit/s (if possible)~~
- [x] WiFi channels view
- [ ] ~~Connect network (right click / context menu)~~
- [x] Auto refresh (like ARP table, etc.)
- [x] Wiki
- [x] Hide channel view if no adapter / network is available

**Comment by BornToBeRoot** [comment]
The wifi feature will be available with the next (pre) release.

I think i will not add a hotspot/virtual ap feature... Other features like LLDP or a Ping monitor are more important to me.
