### ISSUE TITLE
Add an IPScanner button to Network Interface View

### ISSUE THREAD

**Issue by cesaryuan** [BornToBeRoot/NETworkManager#2043]
**Describe your feature request**:

As shown below, could you add an IPScanner button to the Network Interface view which will redirect to the IP Scanner view with the selected interface's IPv4 address?

![image](https://user-images.githubusercontent.com/35998162/224976479-e53c44c6-92cb-49f0-b281-384bd12c1326.png)

PS: I have done this in my fork. If you need it, I can create a pr. But I cannot guarantee the code quality haha.

**Comment by BornToBeRoot** [comment]
If you want to get the current network you can also click this button:

![image](https://user-images.githubusercontent.com/16019165/225034067-8a20f3d2-d4b5-4b67-b54f-8a48d31a2da3.png)

But I can also add a button.

**Comment by cesaryuan** [comment]
> If you want to get the current network you can also click this button:
> 
> ![image](https://user-images.githubusercontent.com/16019165/225034067-8a20f3d2-d4b5-4b67-b54f-8a48d31a2da3.png)
> 
> But I can also add a button.

Thanks for your reply. But the button in your image only gets the default interface. In my situation, there is more than one interface, one for the internet and the other for the local net. 🥰

**Comment by BornToBeRoot** [comment]
Ahh ok. Makes sense. I will implement it.

**Comment by BornToBeRoot** [comment]
Available in the next release. #2046
