### ISSUE TITLE
Cant resolve hostnames

### ISSUE THREAD

**Issue by WattsC-90** [BornToBeRoot/NETworkManager#209]
**Describe your issue**:
I was using version 1.6.1 for a long time, with no issues (mainly used it for the IP scanner to see which hostnames/IPs were active. I thought I would update to version 1.10.0 (and now 1.11.1), but it seems like the hostname resolution has stopped working, I can no longer resolve any  hostnames for IP addresses that are found in the specified ranges.

![image](https://user-images.githubusercontent.com/10712792/62954077-acc17c80-bde6-11e9-8ea0-9d8c32fee6d0.png)

Version 1.6 (which I had downloaded and run standalone) shows the hostnames correctly when scanning.

If I right click and use DNS Lookup menu, then IPAddress is available, but Hostname is grayed out:
![image](https://user-images.githubusercontent.com/10712792/62953718-ec3b9900-bde5-11e9-9f0b-83942877d6dc.png)

Running on Windows Enterprise 1809, i dont know what other info you need.. please ask and ill update this question.

**Comment by BornToBeRoot** [comment]
Since version 1.6.3, i am using Heijden.DNS instead of the .NET default method to resolve the hostname from an ip address.

Can you check these settings:

![image](https://user-images.githubusercontent.com/16019165/62975790-7eaa5f80-be1b-11e9-9bc7-4ac0f111befc.png)

This should automatically detect the dns server configured in windows... Try to set the dns server manually with `Use custom DNS server`.

**Comment by WattsC-90** [comment]
So neither seem to do anything? I had configured the custom dns already but not added the other network (in this case 192.168.4.1 is my router.. so added that one), but its not changed anything.. it was already pointing at the right corporate DNS servers, but not showing the Hostnames (different ip range to the one being shown above). Any other ideas?

**Comment by BornToBeRoot** [comment]
You could check with `nslookup.exe 192.168.4.1` if a PTR is resolved for this IP address, when you query your corporate DNS server.

Edit: You could reset the settings by deleting the file %appdata%\NETworkManager\Settings\Settings.xml

**Comment by ghost** [comment]
Hello all, 
I to can not get hostnames to apear on the list.
Every other IP Scanner i have tried works.
![Capture](https://user-images.githubusercontent.com/55743125/65506900-f5cc1c80-decc-11e9-92d3-0a29fc2c0d72.JPG)

**Comment by BornToBeRoot** [comment]
@brucechaser 

Can you test the "DNS Lookup" in the NETworkManager if you can resolve the PTR record for one of these ip addresses...

By default, the tool detects the windows dns server (you can overwrite this option in the settings)

Which DNS server are you using (Router like FritzBox or Netgear, Windows Server, etc.)???

**Comment by WattsC-90** [comment]
@borntoberoot , i never got this to work, the settings you mentioned in your comment were already configured to the right dns settings for my network. I just used the old version instead, takes a bit longer but it works

**Comment by ghost** [comment]
In DNS Lookup when i use the host name I do get results but when I enter the IP address a get nothing.
We use Windows Server as DNS Server.
Version 1.6.2.0 works fine.
Actually it does not resolve all the host names as Advanced IP Scanner

**Comment by BornToBeRoot** [comment]
> Actually it does not resolve all the host names as Advanced IP Scanner

Advanced IP Scanner also resolves NETBIOS.

I try to replace Heijden.DNS with DnsClient in the next version. Heijden.DNS won't get any updates and i added some custom fixes to make it work with IPv6 dns servers... 

I post a preview version here, once i have it implemented... so you can test it in your environment.


https://github.com/MichaCo/DnsClient.NET
https://www.nuget.org/packages/DnsClient/

**Comment by ghost** [comment]
Thank you man, really appreciate it.
The app is bad ass btw, design and all.
Excellent work.

**Comment by BornToBeRoot** [comment]
@brucechaser @WattsC-90 Can you test this version and give me feedback? It should use the default windows dns server... user settings are ignored.

[NETworkManager_v2_2019_09_28_DnsClient_Portable.zip](https://github.com/BornToBeRoot/NETworkManager/files/3664903/NETworkManager_v2_2019_09_28_DnsClient_Portable.zip)

**Comment by WattsC-90** [comment]
Thanks! Ill give it a go on monday as it struggles on the work network architecture, ill try give it a go at home too just to make sure its working in a more basic environment! Thanks again for your work on this.

**Comment by BornToBeRoot** [comment]
does it work?

**Comment by WattsC-90** [comment]
I had forgotten.. trying it now..

**Comment by WattsC-90** [comment]
@BornToBeRoot  It appears not.. seems to hang up for me..
clicking cancel just causes it to hang up cancelling for ages, not sure if that will help you determine where the issue is..

its just sat at 347 for a while now and still cancelling.. Ill have to kill the app

![image](https://user-images.githubusercontent.com/10712792/66036697-d3a65000-e505-11e9-87fd-131aa18814c5.png)

## NOTE

If i switch off Hostname resolution in the settings it pops all of the IPs up and breezes through the entire range. So definitely something with the hostname resolution!

**Comment by BornToBeRoot** [comment]
I could reproduce the issue... i upload a new version this evening...

**Comment by BornToBeRoot** [comment]
@WattsC-90 @brucechaser can you test this version and give me feedback? Thanks!

[NETworkManager_Issue209_v2.zip](https://github.com/BornToBeRoot/NETworkManager/files/3682322/NETworkManager_Issue209_v2.zip)

**Comment by WattsC-90** [comment]
So I feel like were getting somewhere... still getting errors but its failing fast.
Fortunately these are all private networks so I can share the screenshots!! 

![image](https://user-images.githubusercontent.com/10712792/66116964-8a203880-e5cb-11e9-9729-888f464225cb.png)

Which source file has your DNS lookup code? I was trying to find it but couldnt find the type LookupClient? I want to see what youre doing and if I can find a solution that works.. or a better idea why its not working..

**Comment by BornToBeRoot** [comment]
Here is the LookupClient for the IP scanner
https://github.com/BornToBeRoot/NETworkManager/blob/da82a019212d44d04b69e0d784742a1c8bc56dc7/Source/NETworkManager/Models/Network/IPScanner.cs#L81

This is the query:
https://github.com/BornToBeRoot/NETworkManager/blob/da82a019212d44d04b69e0d784742a1c8bc56dc7/Source/NETworkManager/Models/Network/IPScanner.cs#L144


The DNS server 160.100.160.254 Port 53 and 162.118.144.233 Port 53 are correct?

**Comment by WattsC-90** [comment]
@BornToBeRoot  Ta, saw the query line, cant find the LookupClient object/type is it in a nuget? or in the repo?

**Comment by BornToBeRoot** [comment]
Nuget: https://www.nuget.org/packages/DnsClient/
Doc: http://dnsclient.michaco.net/
Source: https://github.com/MichaCo/DnsClient.NET

**Comment by WattsC-90** [comment]
Ta, had a look.. no idea why it throws these errors.. its intermittent between `ServerFailure` and the shown `Error: No connection could be established to any of the following name servers...` issue..

Can I ask, whats the downside with `DNS.GetHostEntry(ip)`?

**Comment by BornToBeRoot** [comment]
With `DNS.GetHostEntry(ip)?` you can't set a custom dns server... it always use the windows dns.

I can add an option that `DNS.GetHostEntry` can be used as fallback.

Edit: At least i replaced the Heijden.DNS... it's not suported anymore...

**Comment by WattsC-90** [comment]
...~~https://www.codeproject.com/Articles/23673/DNS-NET-Resolver-C~~ <uses Heijden DNS :(
maybe?
pain to write your own, but it looks like it would be versatile.. didnt realise you couldnt specify your own dns servers, hadnt tried before.. 

not sure if WMI would allow you to

**Comment by BornToBeRoot** [comment]
I think it doesn't make sense to write my own dns resolver, when there are well tested libaries available. DnsClient.NET has 7 million downloads on nuget, so the most bugs are fixed and it is stable. And then i still can't test agains your dns server...

With WMI you can query / set windows specific settings.

The best to make it work, would be a fallback option to use DNS.GetHostEntry... But with the default .NET dns resolver, you can't set custom dns, timeout, retries...

**Comment by MichaConrad** [comment]
Hey, jumping in here out of the blue, trying to help ^^

The error `No connection could be established to any of the following name servers` really means what it says, the DnsClient's LookupClient couldn't connect to the server on port 53 via UDP.
Maybe that's blocked by your local firewall or the server is dead or not reachable from your network...

There are a couple of things you can try, for example dig or nslookup

Doing a reverse lookup via dig would look like this: ```dig @160.100.160.254 -x <ip>```
If that fails, then its your network having issues to access that server and there is no problem with the code.

**Comment by WattsC-90** [comment]
@MichaCo Thanks for the jump in, im stuck! As you know from my question on DNSclient.net project it just doesnt work where the windows one does.. our DNS servers work.. theyre just corporate versions.. if DNS didnt work we would be stuffed! what I cant find any information out on is how the windows version differs to yours/others?

**Comment by MichaConrad** [comment]
@WattsC-90 did you try to query your DNS servers with tools like dig or nslookup via command line? 
The windows subsystem for linux is pretty handy for those kind of tests because you can use dig
