### ISSUE TITLE
Application NOT SAVE selected option 'Automatically updates every xxx minut'.

### ISSUE THREAD

**Issue by JadranR** [BornToBeRoot/NETworkManager#2090]
**Describe your issue**:
Program not save selected option 'Automatically updates every xxx minut'.
After reboot System state isn't saved. I must newly select it.

**NETworkManager version**: NETworkManager 2022.12.20.0 Desktop

**Windows version** (like 10.0.x.x): Windows 10 Pro 22H2

**.NET version** (like 6.0.x):  Versioon 6.0
![sshot-1](https://user-images.githubusercontent.com/53031490/226249356-538ae358-d8c7-4051-beac-48046473782e.jpg)

**Screenshots**

<details>
<summary>Eventlog (if application crashes)</summary>

</details>

**Comment by BornToBeRoot** [comment]
Saving this options in the settings is not implemented. I will add it.

**Comment by JadranR** [comment]
Big thanks

Jadran

V V pet., 31. mar. 2023 ob 00:16 je oseba mergify[bot] <
***@***.***> napisala:

**Comment by BornToBeRoot** [comment]
Here is a preview with the fix: https://github.com/BornToBeRoot/NETworkManager/releases/tag/2023.4.3.0

**Comment by JadranR** [comment]
Hi,
I send you now 'clear' Slovenian translation for NETWork Manager
2023.4.3.0, from Transifex.
Now I am in Slovenian After 12.04. I come back in Germany where I have
Wi-Fi connection for testing saving options.

Best regards,
Jadran

V V pon., 3. apr. 2023 ob 12:52 je oseba BornToBeRoot <
***@***.***> napisala:

**Comment by BornToBeRoot** [comment]
Great! Thank you 😄
