### ISSUE TITLE
IP Switcher

### ISSUE THREAD

**Issue by ghost** [BornToBeRoot/NETworkManager#210]
Hey it would be nice to have  IP Profiles or a way to preset IP´s.

I work a lot with different static IP´s and Networkconfigurations....
And it would make my live so much easyer if i´m able to preset some profiles and just by sellecting Profile A for Networkinterface 1 and Profile B for Networkinterface 3.... 

It is a PIA always go to windows settings>properties>IPv4> Enter IP, SN, GW and DNS by hand all the time.

**Comment by BornToBeRoot** [comment]
This is already possible... you can select the interface in the dropdown and then apply a profile.

![image](https://user-images.githubusercontent.com/16019165/63099423-5e8eb380-bf75-11e9-8041-91956e447d1a.png)
![image](https://user-images.githubusercontent.com/16019165/63099451-6a7a7580-bf75-11e9-8126-9f713733a215.png)

**Comment by BornToBeRoot** [comment]
Does this answer your question? If not, please open the ticket again.
