### ISSUE TITLE
WiFi - Connect to network / access point

### ISSUE THREAD

**Issue by HowlingLabs** [BornToBeRoot/NETworkManager#2125]
**Describe your feature request**:

Could there be a feature to connect to a specific access point like with the application WifiInfoView. as this would be handy for setings specific access points.

And maybe an snmp browser or integrated mib files to make looking for specified oid`s easier.

I absolute love your Application it  simplified my live immensely. Thank you and keep it going

**Comment by BornToBeRoot** [comment]
Thanks for the feedback!!

I try to add it for the next release.

**Comment by BornToBeRoot** [comment]
@OfficialWhiteOcean here is a preview with the WiFi connect feature https://github.com/BornToBeRoot/NETworkManager/releases/tag/2023.4.10.0

You can connect to an SSID (not an Access Point BSSID, because this is not supported by windows -.-) with PSK, WPA Enterprise, Open or WPS.
