### ISSUE TITLE
Show IP addresses and subnet masks side by side

### ISSUE THREAD

**Issue by Sympatron** [BornToBeRoot/NETworkManager#213]
At the moment IPv4 addresses and sub net masks are shown as to seperate lists below each other. This makes it quite hard to see which IP address belongs to which subnet. I think it would be better to show them together either as "192.168.1.1 - 255.255.255.0" or even better as "192.168.1.1/24".

**Comment by BornToBeRoot** [comment]
Sorry, i won't change it for now. IP and Subnet will be displayed in separate fields/columns.

**Comment by Sympatron** [comment]
> Sorry, i won't change it for now. IP and Subnet will be displayed in separate fields/columns.

Don't you want it to be change or don't you have enough time? If it is the latter I could try to implement it myself and submit a pull request.

**Comment by BornToBeRoot** [comment]
I don't have enough time 😄  PRs are always welcome 👍 

You can try to implement it in the view without problems (maybe bind the original values to a converter).
If you change the code behind, you need to adjust classes like the ExportManager.

Please use the dev branch for .NET5 --> https://github.com/BornToBeRoot/NETworkManager/tree/net5-develop

**Comment by BornToBeRoot** [comment]
I will not implement this for now, as there are other features that are more of a priority for me.

PRs are still welcome.
