### ISSUE TITLE
IP Address changer

### ISSUE THREAD

**Issue by mem16421** [BornToBeRoot/NETworkManager#2152]
A useful additional tool would be the ability to change your interfaces IP address, which would keep you in NETworkManager.  I tool like https://simpleipconfig.sourceforge.io/ where you can setup IP profiles would be perfect.  I roam around to different customers networks each week, so I have the constant need to change my IP to match my customers

**Comment by BornToBeRoot** [comment]
This is already implemented. See:
https://borntoberoot.net/NETworkManager/Documentation/Application/NetworkInterface#configure

**Comment by mem16421** [comment]
Sure is!  Guess I never tried to make a profile from that screen! :)
