### ISSUE TITLE
Notification keeps popping up - no idea what causes it or how to disable it

### ISSUE THREAD

**Issue by MeikTranel** [BornToBeRoot/NETworkManager#222]
![image](https://user-images.githubusercontent.com/6466560/70740743-237d7080-1d1a-11ea-9cc4-931fa9ed2033.png)

I am not sure how i can fix it,  but i have noticed that NetworkManager keeps refreshing the NIC-List in the Bandwidth display making the bandwidth graph pretty useless for me.

Here's my NIC list. Maybe it has something to do with WSL/HyperV and all that... maybe not. I don't know.

![image](https://user-images.githubusercontent.com/6466560/70741236-20cf4b00-1d1b-11ea-942e-8d7a6e827183.png)

**Comment by BornToBeRoot** [comment]
Hi,

you can disable the status window in the settings:

![issue222](https://user-images.githubusercontent.com/16019165/70856728-1ca15a00-1ee2-11ea-9816-93d31b887683.png)

I can reproduce this issue on a windows 10 when i use windows remote assistance... the status window should only appear when the network address or network availability changes.

**Comment by MeikTranel** [comment]
Well, the toggle works.
I'm still curious what kind of status change it is detecting. Part of me thinks this could be something related to Windows 10 "Your Phone", which does some funny stuff with connections i think. Is there any chance we could get more verbose information on what changed here?

**Comment by BornToBeRoot** [comment]
I use two events to detect if the network has changed:

https://docs.microsoft.com/de-de/dotnet/api/system.net.networkinformation.networkchange.networkavailabilitychanged?view=netframework-4.8

https://docs.microsoft.com/de-de/dotnet/api/system.net.networkinformation.networkchange.networkaddresschanged?view=netframework-4.8

**Comment by BornToBeRoot** [comment]
Should be fixed in most cases after redesigning the status window. There is now a delay before the window is displayed when multiple network events are triggered.

I have also seen the "bug" when starting e.g. WSL... 
Something changes in the network configuration of Windows and then the event is triggered to show the status.

Alternatively, the window can be disabled completely in the settings if it is too annoying.
