### ISSUE TITLE
Block wifi users`

### ISSUE THREAD

**Issue by Chin0p** [BornToBeRoot/NETworkManager#223]
@BornToBeRoot This is not a issue, it's a request to add an option to block or limit users connected to your wifi...

**Comment by BornToBeRoot** [comment]
How? I think it is not possible... Please correct me if i am wrong. 

The tool only scans for available networks, but it has no hotspot function, where you can create your own network. 

If you want the block users from **your** wifi, set a PSK (Pre-Shared-Key) in the router/access point or enable 802.1x (user with password/certificates) if you have an enterprise wifi with multiple users.
