### ISSUE TITLE
Ping - visualization for different packet sizes

### ISSUE THREAD

**Issue by RedstoneFuture** [BornToBeRoot/NETworkManager#2235]
What do you think about extending the port scan functionality with distributed scan for different exemplary packet sizes (e.g. 32Byte, 64Byte, 1kByte, 6kByte)? I could imagine that this would better clarify e.g. ping fluctuations in the WLAN.

Reference: https://www.the-sz.com/products/portscan/PortScanPing.png ([PortScan by sz](https://www.the-sz.com/products/portscan/))

This must be optional, of course. The current minimalistic display is sufficient for many situations. However, the current ping output does not even show which packet sizes are being sent. Shouldn't this be visible somewhere?

**Comment by BornToBeRoot** [comment]
The default size is 32 bytes (same as windows ping command). You can change this in the settings: 

![image](https://github.com/BornToBeRoot/NETworkManager/assets/16019165/2e88e335-bae3-498c-9ae4-451a13c0b869)

I'm not sure if the feature really adds much value compared to the effort of rewriting the ping function.

I will leave the feature request open, perhaps there are several people who also need this feature (Please vote this comment  with👍 👎).

**Comment by BornToBeRoot** [comment]
I do not currently plan to implement this. PRs are welcome
