### ISSUE TITLE
Add dhcpstaticipcoexistence functionality

### ISSUE THREAD

**Issue by mdv2000** [BornToBeRoot/NETworkManager#2264]
In Windows 10 1703 and newer editions, dhcpstaticipcoexistence property gives the opportunity to add static IP adress(es) to an interface set as DHCP.
Unfortunately Windows gives this function available only from netsh console utility. 

Could you add a switch to enable this feature and the possibility to add/remove additional IPs from your utility?

Function reference can be found here (it's not a Microsoft page, but description matches and described procedure works correctly):
[https://superuser.com/questions/679134/add-a-static-ip-alias-to-a-dhcp-interface-on-windows-8-and-above/1250941#1250941](url)

Thanks
Mauro

**Comment by BornToBeRoot** [comment]
@mdv2000 done via #2656, you can test this option in the next (pre-)release.

The option dhcpstaticipcoexistence will be enabled when you add an additional static ip to an adapter that is configured to use DHCP.
