### ISSUE TITLE
The theme follows the system to automatically switch

### ISSUE THREAD

**Issue by pedoc** [BornToBeRoot/NETworkManager#2321]
**Describe your feature request**:

I hope the theme can be synchronized with the system theme.

**Comment by BornToBeRoot** [comment]
There is a function in Mahapp.Metro, but only the theme (light/dark) is synchronized and not the accent.

https://mahapps.com/docs/themes/thememanager#theme-sync-mode

I will not implement the feature. Most users don't change their theme every day.... The effort is in no relation to the benefit. If you want to change the application to light, you can do it manually in the settings.
