### ISSUE TITLE
5Ghz Wi-Fi

### ISSUE THREAD

**Issue by PCAssistSoftware** [BornToBeRoot/NETworkManager#233]
Hi

For some reason WiFi section is not showing any 5Ghz networks, and for certain my router has both 2.4 and 5ghz.

Anything I can try to get it showing them all?

Thank you

**Comment by BornToBeRoot** [comment]
Does your PC / WiFi adapter supports 5 GHz? Are the networks visible in Windows (Settings > Network and Internet)?

**Comment by PCAssistSoftware** [comment]
Yes definitely, and tested it on a desktop and laptop both of which support 5Ghz, and the router shows 2.4Ghz and 5Ghz networks

**Comment by BornToBeRoot** [comment]
Are the networks listed in the "WiFi" tab and is the 5 GHz checkbox enabled?

![image](https://user-images.githubusercontent.com/16019165/71636529-0a3d5500-2c32-11ea-997e-f210a6d8d396.png)

In the channels tab, the line is sometimes not visible for networks on the same channel... only the latest.

![image](https://user-images.githubusercontent.com/16019165/71636647-2beb0c00-2c33-11ea-8873-2e1ab1626866.png)

Which channel (channel center frequency) do you use for 5 GHz? Maybe some are missing... Currently i have only implemented the allowed channels for europe... Maybe there is the issue... 

https://github.com/BornToBeRoot/NETworkManager/blob/faef9c43131ca2495170f282fffac28e05701861/Source/NETworkManager/Models/Network/WiFi.cs#L113-L188

**Comment by PCAssistSoftware** [comment]
YES the 5Ghz check box is ticked, and NO they are not showing on the WiFi tab either, but router definitely showing as 5Ghz enabled on channel 36 (I am in UK so should be fine with you adding Europe channels)

![image](https://user-images.githubusercontent.com/10872799/71636718-01498500-2c2c-11ea-8e25-ab81749d6d6d.png)

I will try it on another computer tomorrow as I do wonder if the issue may be the card on this computer, as sometimes they show in Windows wi-fi windows and sometimes it is only showing 2.4ghz ones, so could be some oddity with me rather than your app.

Happy new year to you!! and keep up the great work with this project :)

**Comment by BornToBeRoot** [comment]
Any update?

**Comment by PCAssistSoftware** [comment]
Sorry had forgotten to come back to you on this.  I think it is this particular router, as despite showing as above screenshot as having separate 2.4 and 5ghz channels none of the devices seem to show them separately, which I think is why the issue.  At some point I will find and try and alternative router and make sure it picks up 5ghz okay.  Consider closed for now - and thanks
