### ISSUE TITLE
OUI.XML, Ports.XML and WhoisServers.XML

### ISSUE THREAD

**Issue by PCAssistSoftware** [BornToBeRoot/NETworkManager#234]
Could I please ask where you obtain your XML files for OUI, Ports and the list of WhoIsServers?

Did you do them yourself or is there a handy website you can download them in correct format?

Thank you

**Comment by BornToBeRoot** [comment]
There are 3 Scripts: https://github.com/BornToBeRoot/NETworkManager/tree/master/Scripts

**Comment by PCAssistSoftware** [comment]
Excellent - thank you very much - I hadn't noticed those :)  - should have guessed you would have it all sorted !!
