### ISSUE TITLE
Network Usage showing on Bandwidth graph page - incorrect/misleading labels and format

### ISSUE THREAD

**Issue by PCAssistSoftware** [BornToBeRoot/NETworkManager#235]
Hi

Is it just me or are the captions incorrect for some of the items in this section, and also the result for Total bytes sent / received need to be converted in same was as Current Bytes sent / received

See attached image where I have marked in red what I think captions should be going on output I see on my screen and from analyzing the values in the variables

![image](https://user-images.githubusercontent.com/10872799/71599112-67a5a900-2b41-11ea-83a9-4658e4ccbc55.png)

**Comment by BornToBeRoot** [comment]
1) I will change the labels `Current download speed` and `Current upload speed` 

2) Then labels `Total bytes received` and `Total bytes sent` are the network statistics from the network adapter ... if i convert it to a larger unit (MB, GB), you don't see if you currently sending or receiving packages: 

![image](https://user-images.githubusercontent.com/16019165/71636734-90f33180-2c34-11ea-8924-a4e8ae5ae175.png)

3) The labels `Total download` and  `Total upload`, shows the amount of data since the start time shown above... Any ideas how to name these labels?

**Comment by PCAssistSoftware** [comment]
2. In tools I have done in the past I convert it depending on size, so shows bytes, kb, mb, or gb depending on value - then it works whatever the size

3. From my testing one set of values show the total sent/received by the selected network card since last rebooted (hence calling them TOTAL) and the other shows the sent/received amount during this current session of "measured time"

**Comment by BornToBeRoot** [comment]
1. I swaped the values MBit/s and MB/s in the `Current download speed` and `Current upload speed`. The first value is also displayed in the graph. 

2. I still think that it is good to see changes in the packages (bytes sent/received)... if you convert it to GB and only receive a few bytes, you don't see changes. But i added the MB/GB/etc. to the label.

3. I changed the labels to `Currently downloaded` and `Currently uploaded`.


I would arrange the labels differently ... but the following areas are interdependent:
![image](https://user-images.githubusercontent.com/16019165/71637409-1f6eaf80-2c43-11ea-9087-e15efeb42818.png)

I close the issue with the commit... feel free to open it again, if you suggest changes.

**Comment by PCAssistSoftware** [comment]
Okay thanks

As for point 2, if it is only a few bytes received then it would show as bytes, it is only if over 1024 bytes it shows as kb, over 1024 kb shows as mb and so on - so would show right anyway

In image above the green area will always be the higher values as shows total downloaded/uploaded since computer rebooted - the one which could have smaller values would be the currently downloaded/uploaded in the read area, surely?

Only my thoughts of course.  It is your great app, so only giving input, which may be useful sometimes and not others :)
