### ISSUE TITLE
speeds showing wrong on Network Interface > Information tab

### ISSUE THREAD

**Issue by PCAssistSoftware** [BornToBeRoot/NETworkManager#236]
Seems to be issue with "Speed" shown on this page - e.g. my gigabit ethernet shows as 1 Tbit/s

And my WiFi shows as 72.2 Gbit/s

They should be 1 Gbit/s for ethernet and 72.2 Mbits/s for the wireless

**Comment by BornToBeRoot** [comment]
Can you run this powershell command: 

```
 [System.Net.NetworkInformation.NetworkInterface]::GetAllNetworkInterfaces() | Select-Object Name, Speed
```

![image](https://user-images.githubusercontent.com/16019165/71636833-54283a00-2c36-11ea-87e4-07b47e7244b8.png)

The `speed` value are bits per second... the only thing i do is to convert it to MBit/s or GBit/s (by dividing it by 1000). 
https://docs.microsoft.com/en-us/dotnet/api/system.net.networkinformation.networkinterface.speed?view=netframework-4.8#System_Net_NetworkInformation_NetworkInterface_Speed

However... The value is the max link speed of the device... but not the actual link speed...

![image](https://user-images.githubusercontent.com/16019165/71636950-905c9a00-2c38-11ea-8f2b-c78f34038112.png)

This could be a workaround to get the current link speed for wifi interfaces (there is no API in .NET or WMI):
https://stackoverflow.com/questions/17516548/determining-the-current-link-speed-of-wifi-in-c-sharp

IPIntertop: https://pastebin.com/1rxEYdnM

![image](https://user-images.githubusercontent.com/16019165/71637119-bb94b880-2c3b-11ea-84ea-6e0c82712035.png)

I haven't seen any problems with physical network adapters yet ...

**Comment by PCAssistSoftware** [comment]
Name                                 Speed
----                                 -----
Ethernet                        1000000000
VirtualBox Host-Only Network #2 1000000000
Local Area Connection* 3                -1
Local Area Connection* 5                -1
WiFi 2                            72200000
Bluetooth Network Connection       3000000
Loopback Pseudo-Interface 1     1073741824

**Comment by PCAssistSoftware** [comment]
The below example is VB rather than C# but what I use to convert bytes (size) or bits (speed) to relevant values depending on size

`Private Shared Function ConvertBytes_Size(bytes As Long) As String
        ' used to convert Bytes into KB/MB/GB etc depending on size - as it is size we used 1024 - and we use capital letters
        Dim stringToReturn

        If bytes < 1024 Then
            stringToReturn = bytes.ToString("n1") & " Bytes"

        ElseIf bytes < (1024 * 1024) Then
            stringToReturn = (bytes / 1024).ToString("n0") & " KB"

        ElseIf bytes >= (1024 * 1024) AndAlso bytes < (1024 * 1024 * 1024) Then
            stringToReturn = (bytes / (1024 * 1024)).ToString("n1") & " MB"

        ElseIf bytes >= (1024 * 1024 * 1024) AndAlso bytes < 1099511627776 Then
            stringToReturn = (bytes / (1024 * 1024 * 1024)).ToString("n2") & " GB"

        Else
            stringToReturn = (bytes / 1099511627776).ToString("n1") & " TB"
        End If

        Return stringToReturn
    End Function

    Private Shared Function ConvertBytes_Speed(bits As Long) As String
        ' used to convert bits into kb/mb/gb etc depending on size - as it is speed we use 1000 - and we use lower case letters
        Dim stringToReturn

        If bits < 1000 Then
            stringToReturn = bits.ToString("n1") & " bits"

        ElseIf bits < (1000 * 1000) Then
            stringToReturn = (bits / 1000).ToString("n0") & " Kb"

        ElseIf bits >= (1000 * 1000) AndAlso bits < (1000 * 1000 * 1000) Then
            stringToReturn = (bits / (1000 * 1000)).ToString("n1") & " Mb"

        ElseIf bits >= (1000 * 1000 * 1000) AndAlso bits < 1000000000000 Then
            stringToReturn = (bits / (1000 * 1000 * 1000)).ToString("n0") & " Gb"

        Else
            stringToReturn = (bits / 1000000000000).ToString("n1") & " Tb"
        End If

        Return stringToReturn
    End Function`

**Comment by wingers999** [comment]
so my way of showing it would be like this

![image](https://user-images.githubusercontent.com/10872799/71637200-49b97080-2c35-11ea-9054-c2b71a6cd1be.png)

**Comment by BornToBeRoot** [comment]
This is the converter:

https://github.com/BornToBeRoot/NETworkManager/blob/d0442472c5694dac92ddfc26fac728b37c37c50d/Source/NETworkManager/Converters/Bytes1000ToSpeedConverter.cs#L7-L24

With your values:

![image](https://user-images.githubusercontent.com/16019165/71637530-7b3a3800-2c45-11ea-83d4-4ed447a61f7f.png)

And this is the function  in the code (same as the powershell command...):

https://github.com/BornToBeRoot/NETworkManager/blob/265121f8f1b3da3cbe2920398c1ac2413f264bd4/Source/NETworkManager/Models/Network/NetworkInterface.cs#L35

https://github.com/BornToBeRoot/NETworkManager/blob/265121f8f1b3da3cbe2920398c1ac2413f264bd4/Source/NETworkManager/Models/Network/NetworkInterface.cs#L139


I have no idea whats wrong... It looks like the index (`sizeCount`) in the converter is +1... Maybe you can set a break point and debug this: 
 https://github.com/BornToBeRoot/NETworkManager/blob/d0442472c5694dac92ddfc26fac728b37c37c50d/Source/NETworkManager/Converters/Bytes1000ToSpeedConverter.cs#L9

https://github.com/BornToBeRoot/NETworkManager/blob/d0442472c5694dac92ddfc26fac728b37c37c50d/Source/NETworkManager/Converters/Bytes1000ToSpeedConverter.cs#L23

**Comment by PCAssistSoftware** [comment]
Went to sleep, rebooted PC (which in turn installed some Windows 10 updates), turned back on, debugged and it is now showing correct values..... really not sure what happened here, but seems my PC was the cause rather than your code.

Sorry, consider this issue closed
