### ISSUE TITLE
Add sniffer, for blocking clients

### ISSUE THREAD

**Issue by marvellz** [BornToBeRoot/NETworkManager#2389]
There is an abandoned [NetStalker](https://github.com/hmz777/NetStalker) project, in which there is a cool function of client blocking in the same network. The lock works very well, some firewalls and AV do not see it. Add this tool, it would be very useful for testing.
**I think this function would be very useful in NETworkManager** 🙏

**Comment by BornToBeRoot** [comment]
I am not exactly sure what this tool does and how many users need this feature. I myself also have no use case.

There is a [newer version](https://github.com/hmz777/NetStalkerAvalonia) available and it looks like it's maintained.

I will not implement the feature.
