### ISSUE TITLE
DiscoveryProtocol - Add button to fix "NetEventSession"

### ISSUE THREAD

**Issue by BornToBeRoot** [BornToBeRoot/NETworkManager#241]

**Comment by BornToBeRoot** [comment]
Move this to the online help?! Show a link in the error message...

**Comment by lahell** [comment]
You could make a checkbox to set the new `-Force` switch. [https://github.com/lahell/PSDiscoveryProtocol/commit/2fa708b4d03c5cf12bbca2254bff6087578586e4](https://github.com/lahell/PSDiscoveryProtocol/commit/2fa708b4d03c5cf12bbca2254bff6087578586e4)

**Comment by BornToBeRoot** [comment]
Thanks, i will take a look.

I totaly forgot to mention your script in the about page. Here it is: https://github.com/BornToBeRoot/NETworkManager/commit/5baf4cd07a19af8a32a0fef19500c333a54babc0

**Comment by BornToBeRoot** [comment]
Fixed in the next release (no button, just the "-force" switch 😄  )

**Comment by BornToBeRoot** [comment]
Test build

URL: https://cloud.borntoberoot.net/s/xZtPE6dMa4Sac4i
Password: `NETworkManager#2021`

**Comment by Erfanciknik** [comment]
add-code-of-conduct-1
