### ISSUE TITLE
Web Consoles

### ISSUE THREAD

**Issue by abasitali** [BornToBeRoot/NETworkManager#244]
Dear Team,

as like RDP I can create profiles and make my groups and save RDP, can you also please add similar section where we can do for the devices which we access through web consoles which would be great also no need to use book marks or open browser tabs.

Regards,
Abdul

**Comment by BornToBeRoot** [comment]
This should be possible. I like the idea... This could be great for sites like iLO/iDRAC

**Comment by abasitali** [comment]
Yes exactly, thank you if it be added and than i dont think so I would even need to go any place else to manage all the consoles even.

**Comment by BornToBeRoot** [comment]
I use [CefSharp - Chromium](https://github.com/cefsharp/CefSharp) for the Browser. Internet Explorer is to old... and the new [WebView](https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/wpf-winforms/webview) (Microsoft Edge) doesn't allow to access websites with an invalid/untrusted certificate... 

CefSharp needs about 180 MB in the installation folder... (before 32 MB where 22 MB are from the icon pack...). WebView would be better to reduce the size... 

![image](https://user-images.githubusercontent.com/16019165/72212804-ddb3f380-34e3-11ea-9d99-a78c60f72cf0.png)

![image](https://user-images.githubusercontent.com/16019165/72212807-05a35700-34e4-11ea-88d6-3f61a6e0178b.png)

![image](https://user-images.githubusercontent.com/16019165/72212805-f7edd180-34e3-11ea-8778-c24197d6ce4c.png)

![image](https://user-images.githubusercontent.com/16019165/72212808-0c31ce80-34e4-11ea-9093-05de9fa2ca7d.png)


Known Issues:
- Site is not shown when the certificate is untrusted and the checkbox "Ignore Certificate Errors" is not set

Pull Request: https://github.com/BornToBeRoot/NETworkManager/pull/250

**Comment by BornToBeRoot** [comment]
I think i will use the webview, even if you cannot connect to a website with an invalid certificate. CefSharp ist to large in my opinion for only displaying a website in my tool... And i also don't want to patch it every time chromium gets a security update (daily/weekly?). The WebView control uses Microsoft Edge which is patched with Windows updates. 

Pull Request for WebView: #251

**Comment by BornToBeRoot** [comment]
The option "Ignore certificate errors" has no effect and can be ignored... 

Preview: [NETworkManager_2020.1.0_Portable_WebConsole.zip](https://github.com/BornToBeRoot/NETworkManager/files/4050188/NETworkManager_2020.1.0_Portable_WebConsole.zip)

**Comment by BornToBeRoot** [comment]
Feature is in the next release...

**Comment by abasitali** [comment]
Thank you so much I will download the updated version

Edited : when will this new release will come =) I am so happy to have this feature.

**Comment by BornToBeRoot** [comment]
Maybe friday... i need some time to create the packages.

**Comment by BornToBeRoot** [comment]
https://github.com/BornToBeRoot/NETworkManager/issues/252

**Comment by abasitali** [comment]
how can I update my current running version to get this new feature

**Comment by BornToBeRoot** [comment]
The new version is not available yet...

Once this https://github.com/BornToBeRoot/NETworkManager/issues/227 is done, i publish a new version.

I also need to update the translation...

**Comment by abasitali** [comment]
Oh ok no problem I will wait for it appreciated.

**Comment by BornToBeRoot** [comment]
The new version is available!

**Comment by abasitali** [comment]
Thank you so much for your effort and support been waiting for this new version like some series episode.
