### ISSUE TITLE
[Feature Request]: NetBIOS Hostname Resolution

### ISSUE THREAD

**Issue by Hammerfest** [BornToBeRoot/NETworkManager#2441]
Basically, if you have a locked down network (work/lab) or an adblock network (home), Hostnames are not resolved as NETworkManager only attempts to get this info from the detected or manually entered DNS and not the systems that respond to scanning.

This looks to be in relation to or probably is https://github.com/BornToBeRoot/NETworkManager/issues/209
It was closed as resolved but it doesn't seem to be the case and it wont let me post to reopen.

https://user-images.githubusercontent.com/396831/253780462-00ea49f5-cf89-4f1f-9e57-20f807257423.PNG

Pictured as an example of a 3rd party utility that works without issue on both of these network configurations but its not limited to that one 3rd party utility, all the ones I can download pull the hostnames without issue, its ONLY NETworkManager that does not.

**Comment by BornToBeRoot** [comment]
WIP #2590 -  might be included in the next version

**Comment by Hammerfest** [comment]
Sweet, im there, I run a 0 inbox with notification for release's on so soon as I see it go up for testing ill be happy to do so.

TYTYTY

**Comment by BornToBeRoot** [comment]
@Hammerfest here is a preview with NetBIOS: https://github.com/BornToBeRoot/NETworkManager/releases/tag/2023.12.28.0

Maybe you can test it and give me some feedback. Thanks!

**Comment by Hammerfest** [comment]
Looking good so far, but it looks like only Windows hosts are resolving, my HP Printer is not.

Annoyingly, I decided to redo my network so only have a few devices online at the moment (critical only).

Screenshot attached to show comparative results.


As a side note, is there a way to hide results that dont reply? I thought the toggle to show unresponsive ip/ports being off would hide them but it does not.


![image](https://github.com/BornToBeRoot/NETworkManager/assets/396831/6952f464-c444-4ea0-84f1-547c66749321)

**Comment by BornToBeRoot** [comment]
@Hammerfest  The toggle should hide devices that are not responding to anything (ICMP, Port Scan, NetBIOS). You can open/expand the row to see more details.

**Comment by Hammerfest** [comment]
> @Hammerfest The toggle should hide devices that are not responding to anything (ICMP, Port Scan, NetBIOS). You can open/expand the row to see more details.

Ok, then I think I will make a new bug report when I have the time and have re-re-re confirmed.
Otherwise the only issue I have found is non windows device hostnames not resolving.

I see you launched a new version and I will test that when I have a moment, I got really busy really fast :(
