### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by chinaljp** [BornToBeRoot/NETworkManager#2445]
I git clone this project , and open it in visual studio 2022, and git clone referenced project Dragablz, then I start to build the solution, 12 of 13 projects build successfully , but Project NetManager faild, there is an error ""命令“PowerShell.exe -ExecutionPolicy Bypass -NoProfile -File "E:\Projects\NETworkManager\Source\NETworkManager\..\..\Scripts\PreBuildEventCommandLine.ps1" "E:\Projects\NETworkManager\Source\NETworkManager\bin\Debug\net6.0-windows10.0.17763.0\win10-x64\"”已退出，代码为 -196608。what's the problem , please help me solve this problem.

**Comment by BornToBeRoot** [comment]
Hi,

did you install all dependencies? 

You need `.NET desktop development` and `Universal Windows Platform development` (and .NET SDK 6).

Does this work inside a PowerShell 7 (Windows PowerShell doesn't work)? 

```PowerShell
# Clone the repository
git clone https://github.com/BornToBeRoot/NETworkManager

# Change directory
cd NETworkManager

# Clone the submodules
git submodule update --init --recursive

# Allow the execution of the build script
Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass

# Build the binaries
& .\build.ps1
```

Can you post a screenshot of the error message? If the build hangs, cancel the script with `CTRL+C` and start the `.\build.ps1` again.

**Comment by BornToBeRoot** [comment]
Cannot be verified. Closed because no response.
