### ISSUE TITLE
Connections - DNS lookup, process ID/name

### ISSUE THREAD

**Issue by PCAssistSoftware** [BornToBeRoot/NETworkManager#247]
1) Add option to do DNS look up to show name as well as IP address for the Remote IP Address, in a separate column

This will make tool so much more useful in a big network as can quickly see devices connected by name rather than then having to look up the IP myself each time

Hopefully as DNS look up integrated in lots of other places this won't be too add?

2) Show process ID and process name for each connection (where relevant)

Basically in same way as 'netstat -abo' does e.g. example output below

Active Connections

  Proto  Local Address          Foreign Address        State           PID
  TCP    127.0.0.1:5354         XPSDESKTOP:0           LISTENING       5788 [mDNSResponder.exe]
  TCP    127.0.0.1:5939         XPSDESKTOP:0           LISTENING       5996 [TeamViewer_Service.exe]
  TCP    127.0.0.1:12025        XPSDESKTOP:0           LISTENING       4512 Can not obtain ownership information
  TCP    192.168.1.65:2869      bthub:51890            TIME_WAIT       0
  TCP    192.168.1.65:5040      Galaxy-A7-2018:50386   CLOSE_WAIT      7100 CDPSvc [svchost.exe]
  TCP    192.168.1.65:5040      Galaxy-A7-2018:50500   CLOSE_WAIT      7100
  TCP    192.168.1.65:61681     40.67.251.132:https    ESTABLISHED     37580 [OneDrive.exe]
  TCP    192.168.1.65:61682     40.67.251.132:https    ESTABLISHED     39460
  TCP    192.168.1.65:64906     52.109.28.2:https      ESTABLISHED     12436 [onenoteim.exe]

**Comment by BornToBeRoot** [comment]
DNS should be possible, but i need to test if the performance is ok when automatically refreshing the view... or somehow cache the result...

I don't know if i get the process name/id from the .NET API. This could be possible with the resource monitor...

**Comment by PCAssistSoftware** [comment]
You can get the process name and ID using this apparently - https://docs.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-getextendedtcptable?redirectedfrom=MSDN

**Comment by BornToBeRoot** [comment]
@PCAssistSoftware Done via #2587

It now resolves the hostname of the remote IP. And it displays the process info like pid, name and path.

IPs/hostnames in the connections view are cached until the applications restarts. This significantly improves performance, especially if the view is automatically updated every x seconds.

![image](https://github.com/BornToBeRoot/NETworkManager/assets/16019165/0973a901-4b91-41f7-a29e-2ce347e334c1)

**Comment by PCAssistSoftware** [comment]
Excellent - thank you!
