### ISSUE TITLE
Add "Release & Renew" to the Interface Information tab

### ISSUE THREAD

**Issue by wolph** [BornToBeRoot/NETworkManager#248]
**Describe your feature request**:

It's a bit weird that you can view the IP address at the Information tab but need to go to Configure tab to renew the IP. And after you've done that, you need to go back to Information to see the current values.

I would personally even opt for merging these tabs entirely.

**Comment by BornToBeRoot** [comment]
I moved also the "Clear  DNS cache"-Button to the other view.

![image](https://user-images.githubusercontent.com/16019165/74597571-d4c5bd00-5061-11ea-84ce-65ccf4572996.png)

![image](https://user-images.githubusercontent.com/16019165/74597586-1c4c4900-5062-11ea-9e95-0f80bc510d0c.png)
