### ISSUE TITLE
Extension to Ping Monitor

### ISSUE THREAD

**Issue by rsnetadmin** [BornToBeRoot/NETworkManager#2530]
Hello,

first of all, i love your Tool awesome job well done good Sir or Mam or Team ! My Work is now much easier. Now to my request would it be possible to integrate a range ping like 192.168.10.0/24

BR Roman

**Comment by BornToBeRoot** [comment]
@rsnetadmin I can test it. The code already exists for the IP/Port Scanner. It might be a bit slow, a /24 subnet would generate 256 graphs.

**Comment by BornToBeRoot** [comment]
@rsnetadmin Done via #2573 - will be in the next release!

**Comment by BornToBeRoot** [comment]
Available in the Pre-release https://github.com/BornToBeRoot/NETworkManager/releases/tag/2023.12.9.0
