### ISSUE TITLE
Enables the remote desktop to customize ports

### ISSUE THREAD

**Issue by guowenju** [BornToBeRoot/NETworkManager#2542]
**Describe your feature request**:
hello:
I've noticed that your open source project's remote desktop feature is excellent, but only the default port is currently supported. I would like to make a suggestion to add support for custom ports to enhance the flexibility and security of the project.

**Comment by BornToBeRoot** [comment]
Hi @sfwwslm,

you have multiple options to overwrite the port (and other settings).

In the Tab / New Connection you can specify the port with `<HOST>:<PORT>` (See:  https://borntoberoot.net/NETworkManager/Documentation/Application/RemoteDesktop#connect)

![image](https://github.com/BornToBeRoot/NETworkManager/assets/16019165/dd1de019-f477-4390-8ad9-a3845bd2fb07)


Or you can overwrite it in the settings (default for all connections):
https://borntoberoot.net/NETworkManager/Documentation/Application/RemoteDesktop#settings
https://borntoberoot.net/NETworkManager/Documentation/Application/RemoteDesktop#port-2

![image](https://github.com/BornToBeRoot/NETworkManager/assets/16019165/44c33dc4-8c10-4bf4-adb7-aa888c4afb20)

Or per group:
https://borntoberoot.net/NETworkManager/Documentation/Application/RemoteDesktop#group
https://borntoberoot.net/NETworkManager/Documentation/Application/RemoteDesktop#port-1

![image](https://github.com/BornToBeRoot/NETworkManager/assets/16019165/5fbeb695-418b-415b-9b37-bd7723a51647)

Or per profile:
https://borntoberoot.net/NETworkManager/Documentation/Application/RemoteDesktop#profile
https://borntoberoot.net/NETworkManager/Documentation/Application/RemoteDesktop#port

![image](https://github.com/BornToBeRoot/NETworkManager/assets/16019165/de512e4e-dea8-4430-a824-445281b85f52)

**Comment by guowenju** [comment]
@BornToBeRoot 

Thank you. Now I know how to use it properly.
