### ISSUE TITLE
Add Telnet Option to Putty Profile

### ISSUE THREAD

**Issue by GitDizzle** [BornToBeRoot/NETworkManager#259]
On NETworkManager v 2019.12, when I go to PuTTY, and then Add profile, all profiles are saved as SSH. I have a few devices that are telnet only. Can you please add an option to save telnet profiles under PuTTY? Thanks.

**Comment by BornToBeRoot** [comment]
![image](https://user-images.githubusercontent.com/16019165/73021761-80e00380-3e28-11ea-909b-28a1094768ac.png)

**Comment by GitDizzle** [comment]
You're right, I was just putting a checkmark on PuTTY, I wasn't clicking on it. Because I didnt click on the word PuTTY, it stayed on the General tab.

![image](https://user-images.githubusercontent.com/60235398/73027014-79e4d100-3de7-11ea-9e51-d7e0f0284075.png)
