### ISSUE TITLE
Get MAC Address / Vendor when scanning different subnets of same network

### ISSUE THREAD

**Issue by PCAssistSoftware** [BornToBeRoot/NETworkManager#260]
Hi

The abiltiy to get MAC Address and Vendor in IP scanner works really well when scanning across the same subnet as I am on e.g. (192.168.20.0/24), but if I try and scan another office (192.168.30.0/24) then I get results for other fields but the MAC Address and Vendor fields are blank

Can this be changed to work across all subnets of a domain when doing IP Scans?

**Comment by BornToBeRoot** [comment]
This is not possible... to get the mac address of the other device, you have to read the arp table entries. ARP only works in the same subnet. If you connect to hosts in another subnet (ping with the ip scanner), you only have the arp entry from your gateway / router.

Here is a good explanation:
https://serverfault.com/questions/397350/what-happens-when-arp-request-comes-from-a-different-subnet
and
https://superuser.com/questions/763371/arp-requesting-to-another-subnet-how

**Comment by BornToBeRoot** [comment]
For windows devices it could be possible via WMI: https://github.com/BornToBeRoot/NETworkManager/issues/149

**Comment by PCAssistSoftware** [comment]
Okay thanks
