### ISSUE TITLE
2024.1.7.0 keeps asking for .net desktop runtime 8.0.0

### ISSUE THREAD

**Issue by sunilkalra123** [BornToBeRoot/NETworkManager#2619]
**Describe your issue**:
installed 2024.1.7.0 but when opening it keeps prompting to install .NET desktop runtime 8.0.0 x64. I already have 8.0.1 installed and downgraded to 8.0.0 just in case, neither worked.

Downgraded to 2024.1.6.0 without an issue

**Steps to reproduce the issue**:

1. install .net desktop runtime 8.0.1 
2. install NETworkManager 2024.1.7.0
3. run NETworkManager

**NETworkManager version**:
2024.1.7.0
- [ ] Portable

**Windows version** (like 10.0.x.x):
11 22H2
**.NET version** (like 6.0.x): 
8.0.1
**Screenshots**

<details>
<summary>Eventlog (if application crashes)</summary>

</details>

**Comment by BornToBeRoot** [comment]
did you install the **Desktop** Runtime for .NET 8?

See https://github.com/BornToBeRoot/NETworkManager/issues/1364#issuecomment-1813271389

**Comment by sunilkalra123** [comment]
yep, got it from here https://download.visualstudio.microsoft.com/download/pr/f18288f6-1732-415b-b577-7fb46510479a/a98239f751a7aed31bc4aa12f348a9bf/windowsdesktop-runtime-8.0.1-win-x64.exe

had v8 for a while

**Comment by BornToBeRoot** [comment]
@sunilkalra123 i can't reproduce it. Can you post the output of `dotnet --info` (PowerShell or cmd) here.

**Comment by sunilkalra123** [comment]
Host:
  Version:      8.0.1
  Architecture: x64
  Commit:       bf5e279d92
  RID:          win-x64

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download


Sunil Kalra
Senior Consultant
t:  01223 921 000
m: 07908 545 946
e:  ***@***.***
w: cambridgesupport.com
Cambridge: 01223 921 500     Huntingdon: 01480 570 500     Stevenage: 01438 535 500 
A Personal Touch in Everything We do...
              
We've Moved! our new address is: 6 Eaton Court, Eaton Socon, Saint Neots PE19 8ER
           
​
​This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited. Although the company has taken reasonable precautions to ensure no viruses are present in this email, the company cannot accept responsibility for any loss or damage arising from the use of this email or attachments. No employee or agent is authorized to conclude any binding agreement on behalf of Cambridge Support Ltd with another party by email without express written confirmation of the appropriate Director.
​
​Cambridge Support Ltd, 6 Eaton Court, Eaton Socon, Saint Neots PE19 8ER. Registered in England and Wales number 11599396

**Comment by sunilkalra123** [comment]
Just a note,

I did have desktop runtime 6 and 8.0.1 installed when I initially installed the update.

Then I removed 8.0.1 and installed 8.0.0 – still prompted the same

Reinstalled NETworkmanager – same issue

Removed runtime 6 – same issue

Reinstalled 8.0.1 – same issue

Reverted back to previous version of NETworkManager

I have now reinstalled the latest version of NETworkManager and it appears to be working.

I have also reinstalled runtime 6 and reinstalled NETworkmanager and its still working.

So I guess it’s a non issue


Sunil Kalra
Senior Consultant
t:  01223 921 000
m: 07908 545 946
e:  ***@***.***
w: cambridgesupport.com
Cambridge: 01223 921 500     Huntingdon: 01480 570 500     Stevenage: 01438 535 500 
A Personal Touch in Everything We do...
              
We've Moved! our new address is: 6 Eaton Court, Eaton Socon, Saint Neots PE19 8ER
           
​
​This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited. Although the company has taken reasonable precautions to ensure no viruses are present in this email, the company cannot accept responsibility for any loss or damage arising from the use of this email or attachments. No employee or agent is authorized to conclude any binding agreement on behalf of Cambridge Support Ltd with another party by email without express written confirmation of the appropriate Director.
​
​Cambridge Support Ltd, 6 Eaton Court, Eaton Socon, Saint Neots PE19 8ER. Registered in England and Wales number 11599396

**Comment by BornToBeRoot** [comment]
Strange issue. But luckily it works now 😄
