### ISSUE TITLE
Geolocation is bugged

### ISSUE THREAD

**Issue by PtDragon** [BornToBeRoot/NETworkManager#2622]
**Describe your issue**:
Geolocation is wrong
For example:
for ip address 109.200.131.170 it gives invalid data: 
    ip to domain is valid: ip170-131-200-109.crelcom.ru.
    **ip to country is invalid**: Ukraine, since 2014 there was enough time to update geoip.
    region(Crimea) and city(Simferopol) are valid.

Second example:
    ip address 62.140.239.113:
    ip to domain is valid: msk-m9-b6-ae1-vlan12.fiord.net.
    Country(Ukraine),region(Kiev) and city(Kiev) are invalid, that server is located in Moscow, Russia, that is indicated in domain name.

**NETworkManager version**:
2024.1.7.0
- [ ] Portable

**Windows version** (like 10.0.x.x):
11
**.NET version** (like 6.0.x): 
8
**Screenshots**
![image](https://github.com/BornToBeRoot/NETworkManager/assets/5212271/5c69a335-5079-4507-9f66-ab6035e0cb2f)

<details>
<summary>Eventlog (if application crashes)</summary>

</details>

**Comment by BornToBeRoot** [comment]
Hi @PtDragon, 

the api and the data is not maintained by this repo / me.

You can correct the data here: https://ip-api.com/docs/correction
