### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by TheLordOfTheKings** [BornToBeRoot/NETworkManager#2637]
Can we have a regex-based Syntax highlighting engine for CLI outputs like putty, ps, ...?

**Comment by BornToBeRoot** [comment]
Hey @arash88 can you please describe in more detail what you mean? For which tools / view exactly?

The PowerShell & PuTTY windows are only integrated here. This means that all syntax highlighting is available that also works in the normal PowerShell or PuTTY window.

Example (PowerShell):

![image](https://github.com/BornToBeRoot/NETworkManager/assets/16019165/37eca3f7-d2c8-4479-ae28-8d924945e47d)

**Comment by TheLordOfTheKings** [comment]
Hey @BornToBeRoot 
I want something like this for putty, syntax highlighting based on regex rules:
https://github.com/rmerzlyakov/putty_hlsyn

Is it already possible? can I have colors in Cisco outputs?

**Comment by BornToBeRoot** [comment]
Yeah. This should work. You have 2 options:

1) Overwrite the setting they explain here (https://github.com/rmerzlyakov/putty_hlsyn) in the default PuTTY profile that is used by NETworkManager

    Load the NETworkManager profile, change the settings, and save it:
    ![image](https://github.com/BornToBeRoot/NETworkManager/assets/16019165/311a5cc8-81ad-485d-8e8d-6f13e4fdf3e0)


2) Create your own PuTTY profile (e.g. CISCO) and use it in NETworkManager
    2.1) You can set it global (for all connections)
          https://borntoberoot.net/NETworkManager/docs/application/putty#profile-4
2.2) per group
https://borntoberoot.net/NETworkManager/docs/application/putty#profile-3
2.3) or per host
https://borntoberoot.net/NETworkManager/docs/application/putty#profile-2

Example:
![image](https://github.com/BornToBeRoot/NETworkManager/assets/16019165/939d2824-f7d9-429a-94d8-0adc6d417eb8)
