### ISSUE TITLE
IP-Scanner: Copy\MAC-Address - Copies Vendor instead of MAC-Address

### ISSUE THREAD

**Issue by nhwCoder** [BornToBeRoot/NETworkManager#2642]
When I use `Copy\MAC-Address` in IP-Scanner it copies "Vendor" instead of "MAC-Address" top clipboard.

**Steps to reproduce the issue**:

1. Open IP-Scanner
2. RightMouse-click any entry row
3. Copy\MAC-Address
4. Content in clipboard is "Vendor" and not "MAC-Address"

**NETworkManager version**: 2024.1.7.0 (= newest)

- [x ] Portable

**Windows version** (like 10.0.x.x): 10.0.22631 Build 22631(= newest)

**.NET version** (like 6.0.x): 8.x

### ADDITIONAL
* In RightMouse-click menu there should be also an entry "Copy all" since Ctrl+C is already working!

**Comment by BornToBeRoot** [comment]
Thanks @nhwCoder for the report.

Fixed via #2644 for the next release!

I'm not sure if it makes sense to implement the copy all by myself if you Ctrl+C already works out of the box for the coloumns.

**Comment by nhwCoder** [comment]
>I'm not sure if it makes sense to implement the copy all by myself if you Ctrl+C already works out of the box for the coloumns.
Not implementing by yourself, but adding it to the menu to see this feature & and in C# trigger a SendKey Ctrl+C would solve it.
