### ISSUE TITLE
give options to  check the network and fix network abnormality problem

### ISSUE THREAD

**Issue by kang888888** [BornToBeRoot/NETworkManager#2673]
**Describe your feature request**:
I want to check the network if it has something error occurred. 
It would be best if you could give me some suggestions or provide options for automatically repairing the network.

**Comment by BornToBeRoot** [comment]
@kang888888 what exactly do you want to check and repair automatically?

The dashboard should give you an overview if you get an IP address, gateway, etc. and if the dns and internet connection  is working.
I want to add some custom checks (e.g. ping, dns, http requests to internal servers) to the dashboard in the future #481 

There are too many different devices and configurations in networks to automatically "repair" a problem with this tool. Even within one manufacturer, this is hardly possible, if at all.
This tool can at best help you to solve the problem on your own (e.g. ping, dns, traceroute or connect to a server/switch via ssh, rdp, etc.) with some basic knowledge about networks (and servers).
