### ISSUE TITLE
MAC address listed in IP Scan 

### ISSUE THREAD

**Issue by jesse-liberty** [BornToBeRoot/NETworkManager#269]
**Describe your feature request**:
It would be great if the IP Scanner section could also report the MAC address when you scan a range/subnet.

**Comment by BornToBeRoot** [comment]
You need to enable it in the settings... see: https://github.com/BornToBeRoot/NETworkManager/issues/143

and there are some limitations: https://github.com/BornToBeRoot/NETworkManager/issues/260
