### ISSUE TITLE
wifi模块一直提示“搜索wifi适配器”

### ISSUE THREAD

**Issue by zuming-zhang** [BornToBeRoot/NETworkManager#2703]
**Describe your issue**:
在软件wifi界面（左侧第3个）中，一直提示“搜索wifi适配器”，若干秒后卡死，崩溃，退出。
**Steps to reproduce the issue**:

1.打开软件
2.点击左侧第三个模块
3.一直提示“搜索wifi适配器”

**NETworkManager version**:2024.4.21.0

- [ ] Portable

**Windows version** (like 10.0.x.x):11 23H2 26002.1000

**.NET version** (like 6.0.x): 8.0.4

**Screenshots**
![image](https://github.com/BornToBeRoot/NETworkManager/assets/118090766/837d8f04-0342-4673-b0f5-a72198a87a87)

<details>
<summary>Eventlog (if application crashes)</summary>

</details>

**Comment by BornToBeRoot** [comment]
Windows Insider Build - Might be related to this: https://github.com/BornToBeRoot/NETworkManager/issues/2561

**Comment by BornToBeRoot** [comment]
@zuming-zhang can you test the current build?

CI: https://ci.appveyor.com/project/BornToBeRoot/networkmanager/builds/49851602/artifacts
Download: https://ci.appveyor.com/api/buildjobs/hy3n7ympwrarca31/artifacts/Artifacts.zip
