### ISSUE TITLE
悬浮提示不可见

### ISSUE THREAD

**Issue by CloverAn** [BornToBeRoot/NETworkManager#2710]
最新版本中，鼠标悬浮到左侧栏时，较长时间才会出现提示性信息，这中间的时间明显过长。同时对于提示内容，应当相对远离鼠标，因为在现在的版本中，提示文字是出现在鼠标底层的，已经被鼠标遮挡到看不见了。

**Comment by BornToBeRoot** [comment]
I'm not sure if the translation is correct, but I think you mean the ToolTip for the applications on the left.

Nothing has changed here in the last few versions. Nevertheless, I think it would be good to reduce the time until it is displayed and to always show a custom tooltip to the right of the application. Just like VSCode does, for example.
