### ISSUE TITLE
New msi installer doesn't work.

### ISSUE THREAD

**Issue by BluePT** [BornToBeRoot/NETworkManager#2732]
"ATTENTION
The MSI installer published on 24.05.2024 (preview) had an error in the uninstall routine. If you have problems with the uninstallation or the current update, first reinstall the version [2024.4.21.0 (direct download of the setup)](https://github.com/BornToBeRoot/NETworkManager/releases/download/2024.4.21.0/NETworkManager_2024.4.21.0_Setup.exe). You can then run the MSI installation programme to update to the latest version."

That is not true. Latest msi installer doesn't work even following the above procedure!
My system:  Windows 10 Pro 22H2 with latest updates + NET Runtime 8.05

**Comment by BornToBeRoot** [comment]
Do you get an error message?

Something in the eventlogs?

**Comment by BornToBeRoot** [comment]
The MSI installer is looking for the old InnoSetup uninstaller (in the registry under `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{8028080F-B785-4A74-A243-3D63467880A6}_is1`

and executes the uninstall string that will point to 

`C:\Program Files\NETworkManager\unins000.exe` (InnoSetup)

If this is not available, the uninstall fails with the MSI from 24.05.2024.

Can you check if the registry key & unins000.exe is available when you run the new MSI installer

**Comment by BluePT** [comment]
I found the problem. NerworkManager is not installed in my system in program files, but in a custom folder (d:\webtools).

**Comment by BluePT** [comment]
Now trying a "clean" install with the new installer.

**Comment by BluePT** [comment]
Same error! 
Log: 
Product: NETworkManager 2024.5.27.0 -- Error 1721. There is a problem with this Windows Installer package. A program required for this install to complete could not be run. Contact your support personnel or package vendor. Action: UninstallInnoSetup, location: C:\Program Files\NETworkManager\, command: PowerShell.exe -NoProfile -WindowStyle Hidden -EncodedCommand "dAByAHkAIAB7AEcAZQB0AC0ASQB0AGUAbQAgACIASABLAEwATQA6AFwAUwBPAEYAVABXAEEAUgBFAFwATQBpAGMAcgBvAHMAbwBmAHQAXABXAGkAbgBkAG8AdwBzAFwAQwB1AHIAcgBlAG4AdABWAGUAcgBzAGkAbwBuAFwAVQBuAGkAbgBzAHQAYQBsAGwAXAB7ADgAMAAyADgAMAA4ADAARgAtAEIANwA4ADUALQA0AEEANwA0AC0AQQAyADQAMwAtADMARAA2ADMANAA2ADcAOAA4ADAAQQA2AH0AXwBpAHMAMQAiACAALQBFAHIAcgBvAHIAQQBjAHQAaQBvAG4AIABTAHQAbwBwACAAfAAgAEYAbwByAEUAYQBjAGgALQBPAGIAagBlAGMAdAAgAHsAUwB0AGEAcgB0AC0AUAByAG8AYwBlAHMAcwAgAC0ARgBpAGwAZQBQAGEAdABoACAAJAAoACQAXwAuAEcAZQB0AFYAYQBsAHUAZQAoACIAVQBuAGkAbgBzAHQAYQBsAGwAUwB0AHIAaQBuAGcAIgApACkAIAAtAEEAcgBnAHUAbQBlAG4AdABMAGkAcwB0ACAAIgAvAFYARQBSAFkAUwBJAEwARQBOAFQAIAAvAFMAVQBQAFAAUgBFAFMAUwBNAFMARwBCAE8AWABFAFMAIAAvAE4ATwBSAEUAUwBUAEEAUgBUACIAIAAtAFcAYQBpAHQAfQB9ACAAYwBhAHQAYwBoACAAewB9ACAAZgBpAG4AYQBsAGwAeQAgAHsAZQB4AGkAdAAgADAAfQA="

**Comment by BluePT** [comment]
For now, the solution is using the portable version.

**Comment by BornToBeRoot** [comment]
If you install the [old InnoSetup setup](https://github.com/BornToBeRoot/NETworkManager/releases/download/2024.4.21.0/NETworkManager_2024.4.21.0_Setup.exe) version to `D:\webtool\NETworkManager` (exact path where it is installed) and then run the latest msi it should work.

Sorry for the inconvenience.

**Comment by MaxL-hub** [comment]
When attempting to uninstall NETworkManager version 2024.5.24.0 to perform a clean installation of version 2024.5.27.0, the same error occurs as when trying to install version 2024.5.27.0.
![ApplicationFrameHost_Hafjs2Dsv2](https://github.com/BornToBeRoot/NETworkManager/assets/76598655/16fa0a7d-b1bd-46dc-ae7f-c0fd542cc5b2)

**Comment by BornToBeRoot** [comment]
@MaxL-hub  did you install / overwrite the installation with Version [2024.4.21.0](https://github.com/BornToBeRoot/NETworkManager/releases/download/2024.4.21.0/NETworkManager_2024.4.21.0_Setup.exe) and then run the MSI for 2024.5.27.0 ?

**Comment by Vince2019** [comment]
![WeCom20240612-165356](https://github.com/BornToBeRoot/NETworkManager/assets/46521989/bba84b44-136a-468a-b705-dd60f5f822a6)
Same issue...

**Comment by BornToBeRoot** [comment]
I will publish an installer without this uninstall routine... in some cases (Windows Sanbox & Winget Azure CI) i also face this issue.

I'm still not sure what's causing this...

**Comment by MaxL-hub** [comment]
> @MaxL-hub did you install / overwrite the installation with Version [2024.4.21.0](https://github.com/BornToBeRoot/NETworkManager/releases/download/2024.4.21.0/NETworkManager_2024.4.21.0_Setup.exe) and then run the MSI for 2024.5.27.0 ?

Here's my list of actions:
1. Attempted to install version 2024.5.27.0 -> installer error.
2. Tried to uninstall the version I had, 2024.4.21.0 -> uninstaller error.
3. Posted the error window from step two here.
4. Initially installed 2024.4.21.0 as indicated in [the message above](https://github.com/BornToBeRoot/NETworkManager/issues/2732#issuecomment-2134701539), then installed 2024.5.27.0 -> success.

[In my previous message](https://github.com/BornToBeRoot/NETworkManager/issues/2732#issuecomment-2155535084), I wanted to point out that the issue is not only with installation but also with uninstallation: the error seems to be the same.

**Comment by BornToBeRoot** [comment]
Thanks for the details. It looks like the install program also calls the uninstall before it causes the error (I had suspected that too).

**Comment by zzangae** [comment]
![netWorker24](https://github.com/BornToBeRoot/NETworkManager/assets/3909532/ad64c572-edc3-4828-9207-ada656c6d76b)

BuildNumber     Caption                                       OSArchitecture        Version
22631                 Microsoft Windows 11 Pro         64-bit                      10.0.22631

**Comment by BornToBeRoot** [comment]
I published a new installer without the uninstall routine that cause this issue (it was trying to uninstall NETworkManager 2024.4.21.0 and below via InnoSetup...).

Here is the release: https://github.com/BornToBeRoot/NETworkManager/releases/tag/2024.6.15.0

---

If any of you still have the problem. You can remove the faulty version with the troubleshooter from Microsoft. Simply click on problems during uninstallation and then select NETworkManager <VERSION> in the list of programmes.

https://support.microsoft.com/en-us/topic/fix-problems-that-block-programs-from-being-installed-or-removed-cca7d1b6-65a9-3d98-426b-e9f927e1eb4d
