### ISSUE TITLE
Hope to add the left function bar custom sort function

### ISSUE THREAD

**Issue by SixXue** [BornToBeRoot/NETworkManager#2758]
**Describe your feature request**:
I hope to enhance the custom sorting function of the left function bar, allowing users to select their frequently used functions for easy access at the top of the left side.
 Thanks.

**Comment by BornToBeRoot** [comment]
@SixXue the feature is available as pre-release: https://github.com/BornToBeRoot/NETworkManager/releases/tag/2024.8.1.0
