### ISSUE TITLE
Support macOS & Linux

### ISSUE THREAD

**Issue by windowshome** [BornToBeRoot/NETworkManager#2776]
**Describe your feature request**:
This net-tools What time support macos platform Run

**Comment by BornToBeRoot** [comment]
Hi @windowshome, 

the application is based on WPF (Windows Presentation Foundation) and uses some Windows libraries such as mstscax for Remote Desktop or embedded PuTTY/PowerShell/etc., which means that it is unfortunately not possible to port the application to macOS or Linux without further ado.

Mono now supports WPF and the application can be started there if .NET 8 is installed. However, some libraries such as mstscax (which Mono does not emulate) are also missing here. However, most of the features should work (I have not tested all of them).

There is also a solution from Avalonia called XPS, which makes WPF applications run on macOS and Linux. However, this solution costs quite a bit of money and would also have the problems with the libs / embedded programs. Open source applications are recommended to migrate to Avalonia UI, which would take a lot of time with this size of application and all the theming. If I were to start from scratch now, I would use avalonia.
