### ISSUE TITLE
Ability to reorder visible applications

### ISSUE THREAD

**Issue by 54m4d** [BornToBeRoot/NETworkManager#2798]
Hello! I'm looking for a way to reorder visible applications without actually hiding them in the settings, but currently, this is not possible.

E.g. Move all the applications that are used less frequently to the bottom.

E.g. The user wants the ARP Table to be placed under the Dashboard.

I hope this is an easy modification and that it will be implemented in the future.

Thanks!

**Comment by BornToBeRoot** [comment]
I currently work on this in #2781. I hope i can publish a preview next week including this change.

**Comment by 54m4d** [comment]
That’s fantastic! With this feature and the ability to adjust the font and text, it’s hard to imagine finding a better tool!

I’ll close this request as soon as I’ve tested the preview.

Thanks!

**Comment by BornToBeRoot** [comment]
@54m4d the feature is available as pre-release: https://github.com/BornToBeRoot/NETworkManager/releases/tag/2024.8.1.0

**Comment by 54m4d** [comment]
Hi, I've just tested it now and it's a great addition. Thanks!
