### ISSUE TITLE
Ability to access application's settings with a right-click

### ISSUE THREAD

**Issue by 54m4d** [BornToBeRoot/NETworkManager#2808]
**Describe your feature request**:
As we use applications, we often need to adjust their settings to experiment with different results. Therefore, I believe allowing access to an application's settings with a right-click would save users several clicks, especially when they need to access the settings multiple times in a short period.

For example, the current behavior involves navigating to Settings, then checking the list for the desired application's settings.

Expected behavior after the feature implementation: Right-clicking any application and selecting "Settings" will take the user directly to that application's settings.

Thanks!

**Comment by BornToBeRoot** [comment]
Hi @54m4d,

if you click on the settings icon, the settings from the current selected tool is opened. If a tool doesn't have settings, the last selected or first setting is opened.

![settings](https://github.com/user-attachments/assets/a354d339-ad05-470c-9cda-fc328d092630)

**Comment by 54m4d** [comment]
Indeed, I discovered this just today, and it's pretty good, this makes my request invalid, and you can feel free to close :)
Thanks!
