### ISSUE TITLE
Support IPv6 for IP- and Port-Scanner

### ISSUE THREAD

**Issue by TechInterMezzo** [BornToBeRoot/NETworkManager#283]
Would it be possible to allow IPv6 addresses for the scanners?

**Comment by BornToBeRoot** [comment]
I will add IPv6 support for single hosts (which can be separated by `;`).

I currently don't know how to handle the large ranges like /52 or /64...

**Comment by BornToBeRoot** [comment]
IP Scanner
![image](https://user-images.githubusercontent.com/16019165/79926363-0598e880-843d-11ea-8617-26d533bd5720.png)

Port Scanner
![image](https://user-images.githubusercontent.com/16019165/79926380-121d4100-843d-11ea-858f-18adb6beddbe.png)

**Comment by BornToBeRoot** [comment]
Will be available in the next relase.
