### ISSUE TITLE
Possibility to add multiple IP-addresses on single Interface

### ISSUE THREAD

**Issue by ShiftedRy** [BornToBeRoot/NETworkManager#2836]
Possibility to add multiple IP-addresses on single Interface

**Comment by BornToBeRoot** [comment]
Hi,

if you go to `Network Interface > Configure > Additional config...`, you can add/remove IP addresses.

https://borntoberoot.net/NETworkManager/docs/application/network-interface#configure

**Comment by ShiftedRy** [comment]
Sorry, I missed that! Thanks for your effort! Really great work you are doing with NETworkManager!
