### ISSUE TITLE
Ping 监控，当电脑没有网络时，无法ping通127.0.0.1以及其他局域网

### ISSUE THREAD

**Issue by Youngolo** [BornToBeRoot/NETworkManager#2875]
Ping 监控，当电脑没有网络时，无法ping通127.0.0.1以及其他局域网，重新连上网络则可以ping通局域网。

**Comment by BornToBeRoot** [comment]
Thanks! I could reproduce the issue. It crashes because the DNS server is not reachable. Will be fixed in the next version

**Comment by BornToBeRoot** [comment]
Fixed in https://github.com/BornToBeRoot/NETworkManager/releases/tag/2024.11.11.0
