### ISSUE TITLE
MAC address column for IP and Port Scanner

### ISSUE THREAD

**Issue by TechInterMezzo** [BornToBeRoot/NETworkManager#288]
Could you show the MAC address next to the IP address and the hostname in the scanner results?

This way I wouldn't have to cross check with other sources for MAC addresses.

**Comment by BornToBeRoot** [comment]
see #269

It's not available in the Port Scanner...

**Comment by TechInterMezzo** [comment]
Okay, thank you for the hint.
Would it be theoretically possible to use the ARP cache for port scanner results as well?

**Comment by BornToBeRoot** [comment]
This would be possible, but I don't want to mix these functions.

The port scanner should only be there to scan ports... not to find hosts in a network.
