### ISSUE TITLE
Error scanning wifi adapter

### ISSUE THREAD

**Issue by konn-neko** [BornToBeRoot/NETworkManager#2884]
**Describe your issue**:
my wifi adapter fails to load on the app with this error 
![image](https://github.com/user-attachments/assets/69fd222a-c5a5-4926-925d-0411d1d077d6)

**Steps to reproduce the issue**:

1. load up app
2. go to wifi scanner
3. error

**NETworkManager version**:
 Version: 2024.6.15.0

**Windows version** (like 10.0.x.x):
Edition	Windows 11 Pro for Workstations
Version	24H2
Installed on	‎11/‎8/‎2024
OS build	26100.2033
Experience	Windows Feature Experience Pack 1000.26100.23.0

**.NET version** (like 6.0.x): 
unknown
**Screenshots**
![image](https://github.com/user-attachments/assets/9965499b-e610-423f-8210-a6f069d72b24)

**Comment by BornToBeRoot** [comment]
Hi @konn-neko,

i just published a new pre-lease where i also implemented logging for your problem. 

You can download the portable version here:
https://github.com/BornToBeRoot/NETworkManager/releases/tag/2024.11.11.0

In the folder is a file `log4net.config` where you need to change the log level in line 4 from `INFO` to `DEBUG`.

Can you test again and send me the crash log + 2-3 lines before it happens. The log is under:
 
 `%LocalAppData%\NETworkManager\NETworkManager.log` 

Thanks!

**Comment by konn-neko** [comment]
> Hi @konn-neko,
> 
> i just published a new pre-lease where i also implemented logging for your problem.
> 
> You can download the portable version here: https://github.com/BornToBeRoot/NETworkManager/releases/tag/2024.11.11.0
> 
> In the folder is a file `log4net.config` where you need to change the log level in line 4 from `INFO` to `DEBUG`.
> 
> Can you test again and send me the crash log + 2-3 lines before it happens. The log is under:
> 
> `%LocalAppData%\NETworkManager\NETworkManager.log`
> 
> Thanks!

[NETworkManager.log](https://github.com/user-attachments/files/17699518/NETworkManager.log)
log after both portable and normal install worked again
unsure if it will help

**Comment by BornToBeRoot** [comment]
Thank you. I assume that it could have detected a WIFI network (channel frequency) which is causing the error (either due to a bug in my code or because the device is using a non-standard frequency). If the network is no longer available/accessible, the error (currently) no longer occurs.

If the problem occurs again, please send me the current log (error message + 2-3 lines before it are sufficient).

**Comment by konn-neko** [comment]
> Thank you. I assume that it could have detected a WIFI network (channel frequency) which is causing the error (either due to a bug in my code or because the device is using a non-standard frequency). If the network is no longer available/accessible, the error (currently) no longer occurs.
> 
> If the problem occurs again, please send me the current log (error message + 2-3 lines before it are sufficient).

i have a delivery for you
[log.log](https://github.com/user-attachments/files/17758958/log.log)
this is what happens, i did see the quick console lauch then close, but that was about it

**Comment by BornToBeRoot** [comment]
Thanks! Looks like it detected a 6 GHz network and the view cannot display that. I will fix it in the next release!

**Comment by konn-neko** [comment]
> Thanks! Looks like it detected a 6 GHz network and the view cannot display that. I will fix it in the next release!

is it adding a 6g option?

**Comment by BornToBeRoot** [comment]
@konn-neko the new pre-release should fix that bug: https://github.com/BornToBeRoot/NETworkManager/releases/tag/2024.11.19.0

The 6GHz networks should be available in the list. I may add the overview for the channel later.
