### ISSUE TITLE
The welcome window will enter an infinite loop and cannot enter the program

### ISSUE THREAD

**Issue by MonoLogueChi** [BornToBeRoot/NETworkManager#2908]
**Describe your issue**:

The boot interface will enter an infinite loop when it is first started.

The Continue button is outside the screen. You cannot enter the program without clicking Continue. You cannot adjust the window position without entering the program. You cannot click the Continue button without adjusting the window position.

You can only enter the program after adjusting the screen ratio

![PixPin_2024-11-12_21-44-54](https://github.com/user-attachments/assets/4d369098-89e4-49e4-ae3c-13457ae56c7d)

**Steps to reproduce the issue**:

1. First Startup

**NETworkManager version**:
[2024.11.11.0](https://github.com/BornToBeRoot/NETworkManager/releases/tag/2024.11.11.0)
- [x] Portable

**Windows version** (like 10.0.x.x):
26100.2161
**.NET version** (like 6.0.x): 
9.0.100-rc.2
**Screenshots**
2880x1880  200%
<details>
<summary>Eventlog (if application crashes)</summary>

</details>

**Comment by BornToBeRoot** [comment]
Can you press `Enter` in the dialog to confirm it?

Edit: you can also try to resize the window by dragging it in the corner.

**Comment by MonoLogueChi** [comment]
> Can you press `Enter` in the dialog to confirm it?
> 
> Edit: you can also try to resize the window by dragging it in the corner.

I have entered the program by adjusting the screen zoom.

I have not tried using the enter key.

The window size cannot be adjusted. When the welcome window is open, the entire window cannot be selected.

**Comment by BornToBeRoot** [comment]
You should be able to resize the window with the corner with the mouse. But i know that the problem is the position of the window, that the button is hidden behind the windows taskbar... I am not sure if i can fix this, or if this is handled by the library i use. I will check it...

![image](https://github.com/user-attachments/assets/60cde0b3-4851-4f9c-9440-661086230ccf)

![image](https://github.com/user-attachments/assets/249c22c3-9446-4499-a086-07f2ad536089)

**Comment by BornToBeRoot** [comment]
@MonoLogueChi fixed in the next release. You can now drag & resize the window

**Comment by BornToBeRoot** [comment]
@MonoLogueChi Should be fixed in https://github.com/BornToBeRoot/NETworkManager/releases/tag/2024.11.19.0
