### ISSUE TITLE
NETManager WebConsole issuse

### ISSUE THREAD

**Issue by gmeishaide** [BornToBeRoot/NETworkManager#314]
**Describe your issue**:
When trying to add a new connection or profile in the WebConsole section it causes the NETManager to totally freeze up and it is unresponsive.  When try and close the app I get no response and when I go into taskmanger 
to kill it, this causes a major issue and it completely crashes my whole browser session (This my second time typing this all over again) and I have to do a total restart of the system in order for NETManager to launch again.

**Steps to reproduce the issue**:

1. Goto WebConsole Section
2. Add either a New Connection or Profile then it freezes.
3.  Open a Taskmanager session and kill process for NETManager*32.exe and watch it close out the session for NETManager and any browser session you have open. 

**NETworkManager version**: 2020.5 Patch 1

**Windows version**:Version: 10.0.18363

**.NET-Framework version**: 4.8.03752

**Screenshots**
![2020-07-19_11-24-02](https://user-images.githubusercontent.com/25092381/87879948-da7e5080-c9bb-11ea-8e68-ec91f7951885.png)

<details>
<summary>Eventlog (if application crashes)</summary> N/A

</details>

**Comment by BornToBeRoot** [comment]
@gmeishaide i couldn't reproduce the issue. Can you share me a gif/video with the steps to reproduce?

**Comment by BornToBeRoot** [comment]
Closed. Please reopen if you have more informations like a video with steps to reproduce.
