### ISSUE TITLE
SMTP Option required

### ISSUE THREAD

**Issue by ayazcancer** [BornToBeRoot/NETworkManager#320]
Kindly add SMTP option in the software to get alerts of our Ping failed and restore.

![ping](https://user-images.githubusercontent.com/69971527/90772921-a1b0fe80-e30e-11ea-83df-92f2ddba78d7.PNG)

**Comment by BornToBeRoot** [comment]
@ayazcancer I don't know exactly what you want. Who should receive the snmp? Maybe a montitoring solution like centreon/checkmk/incinga would be better for your requirements. My software doesn't replace a montitoring system. This feature is intended to check multiple hosts if they are reachable for e.g. when you do updates, change configurations, etc.
