### ISSUE TITLE
IP Scanner: Application closes after copy Hostname (or IP Address) via right-click  menu.

### ISSUE THREAD

**Issue by Paesce80** [BornToBeRoot/NETworkManager#323]
**Describe your issue**:
If i want to copy the Hostname or the IP address of a Host in the ip scanner via right-click, the Network Manager window closes after a few seconds.

**Steps to reproduce the issue**:

1. Open IP Scanner
2. Search the local network (192.168.1.0/24)
3. Rightclick on a Host
4. Choose Copy->Hostname

**NETworkManager version**: 
2020.5 Patch 1

**Windows version**:
WIndows 10 version 2004 Build 19041.450

**.NET-Framework version**:
don't know how to find out.

**Comment by BornToBeRoot** [comment]
If the application crashes, there is an entry in the eventvwr.msc > Windows Logs > Application
Can you send me the Stacktrace of the crash.

**Comment by Paesce80** [comment]
1st ERROR Event in LOG:

Anwendung: NETworkManager.exe Frameworkversion: v4.0.30319 Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet. Ausnahmeinformationen: System.Runtime.InteropServices.COMException bei System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32, IntPtr) bei System.Windows.Clipboard.Flush() bei System.Windows.Clipboard.CriticalSetDataObject(System.Object, Boolean) bei NETworkManager.ViewModels.IPScannerViewModel.CopySelectedHostnameAction() bei NETworkManager.ViewModels.IPScannerViewModel.<get_CopySelectedHostnameCommand>b__94_0(System.Object) bei NETworkManager.Utilities.RelayCommand.Execute(System.Object) bei MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(System.Windows.Input.ICommandSource, Boolean) bei System.Windows.Controls.MenuItem.InvokeClickAfterRender(System.Object) bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32) bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate) bei System.Windows.Threading.DispatcherOperation.InvokeImpl() bei System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object) bei MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object) bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) bei MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object) bei System.Windows.Threading.DispatcherOperation.Invoke() bei System.Windows.Threading.Dispatcher.ProcessQueue() bei System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef) bei MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef) bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object) bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32) bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate) bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32) bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr) bei MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef) bei System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame) bei System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame) bei System.Windows.Application.RunDispatcher(System.Object) bei System.Windows.Application.RunInternal(System.Windows.Window) bei System.Windows.Application.Run(System.Windows.Window) bei NETworkManager.App.Main()


2nd Error Event in LOG:
Name der fehlerhaften Anwendung: NETworkManager.exe, Version: 2020.5.1.0, Zeitstempel: 0x5ebb0ea4
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.423, Zeitstempel: 0x09cf3bbe
Ausnahmecode: 0xe0434352
Fehleroffset: 0x00129962
ID des fehlerhaften Prozesses: 0x5f74
Startzeit der fehlerhaften Anwendung: 0x01d68576ad410842
Pfad der fehlerhaften Anwendung: C:\Program Files (x86)\NETworkManager\NETworkManager.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\KERNELBASE.dll
Berichtskennung: 45fa927b-401d-4f52-9bac-4f1945857535
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:

**Comment by BornToBeRoot** [comment]
I don't know why this happens and i cannot reproduce the issue. Maybe something like AV is preventing the app to access the clipboard?! 
You could test the latest version 2020.12.x and also test if you can copy data from other views like whois, port scanner, etc. all are using the same method.

For now i close this issue. If you (or someone else has more infos) please reopen!
