### ISSUE TITLE
Add an option to hide the splashscreen

### ISSUE THREAD

**Issue by edmael** [BornToBeRoot/NETworkManager#331]
When starting the application at Windows startup it's kind of annoying to see the splashscreen.
There should be an option (in the "Appearance" or "Startup" tab) to hide the splashscreen when the app starts.

**Comment by BornToBeRoot** [comment]
Thanks for the feedback. I just checked it and it is possible (without much effort). I will add an option under Settings>Window>SplashScreen

**Comment by BornToBeRoot** [comment]
Here is your button 😄 

Will be in the next release.

![image](https://user-images.githubusercontent.com/16019165/92813425-6cee0f80-f3c1-11ea-8902-9f9c3e4c5cc5.png)

**Comment by edmael** [comment]
Thanks man ;)
