### ISSUE TITLE
Crash if Ribbon is collapsed (after Update to Version 8.0.1)

### ISSUE THREAD

**Issue by spapst1986** [BornToBeRoot/NETworkManager#376]
**Describe your issue**:
Programm crashed if the Ribbon is collapsed and any TabItem Header is clicked (Menu is working).
Tried to refresh project and reload Nuget Packages.
If IsCollapsed = False is setted Ribbon works as expected.

Fluent Ribbon Version 8.0.1
ControlzEx Version 4.4

**Steps to reproduce the issue**:

1. Minizmie Ribbon
2. Click on any TabItem Header

**Windows version**: Win 10

**.NET-Framework version**: .net 4.7

<details>
<summary>
System.TypeLoadException: Der Typ "ControlzEx.Standard.MONITORINFO" in der Assembly "Fluent, Version=8.0.0.0, Culture=neutral, PublicKeyToken=3e436e32a8c5546f" konnte aufgrund eines Werttypenkonflikts nicht geladen werden.

   bei Fluent.RibbonTabControl.CustomPopupPlacementMethod(Size popupsize, Size targetsize, Point offset) 
   bei System.Windows.Controls.Primitives.Popup.UpdatePosition() 
   bei System.Windows.Controls.Primitives.Popup.OnWindowResize(Object sender, AutoResizedEventArgs e) 
   bei System.Windows.Interop.HwndSource.Resize(Size newSize) 
   bei System.Windows.Interop.HwndSource.OnLayoutUpdated(Object obj, EventArgs args)
   bei System.Windows.ContextLayoutManager.fireLayoutUpdateEvent() 
   bei System.Windows.ContextLayoutManager.UpdateLayout() 
   bei System.Windows.Interop.HwndSource.SetLayoutSize() 
   bei System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value) 
   bei System.Windows.Controls.Primitives.Popup.SetRootVisualToPopupRoot() 
   bei System.Windows.Controls.Primitives.Popup.CreateWindow(Boolean asyncCall)
   bei System.Windows.Controls.Primitives.Popup.OnIsOpenChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)

   bei System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e) 
   bei System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e) 
   bei System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args) 
   bei System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry

</summary>

</details>

**Comment by BornToBeRoot** [comment]
Does this happen in NETworkManager or did you post the issue to the wrong repo?

**Comment by spapst1986** [comment]
OMG! I am so sorry, this was meant to be posted in Fluent Ribbon Repo not in NewWorkManager. Not sure how this happens. I'm terrible sorry about. Sorry again.
