### ISSUE TITLE
RDP Profile & different users and passwords

### ISSUE THREAD

**Issue by AndyHeinz** [BornToBeRoot/NETworkManager#378]
Hi,
I was wondering if I can safe rdp-profiles with several specific user-logins. Or do I always have to connect via "right-click on profile -> connect as"?
Thanks!

**Comment by BornToBeRoot** [comment]
Hi,

it's currently not possible. But i will try to implement it in the profiles.

Greetings

**Comment by BornToBeRoot** [comment]
I will try to add profile encrpytion https://github.com/BornToBeRoot/NETworkManager/issues/226 and then we can securely save  Username and Password in den Profiles.

**Comment by BornToBeRoot** [comment]
@AndyHeinz @evilbaschdi  @nik0chan @graphik55

You can now add the username and password for remote desktop in the profile. The profile file can be encrypted on disk with a master password (Settings > Profile). See [this](https://borntoberoot.net/NETworkManager/FAQ#how-to-enable-profile-file-encryption) for more details.

Would be nice if you could test it... find bugs... etc.

**Download (Portable build)**
URL: https://cloud.borntoberoot.net/s/fg4ATgS3YXng28k
PW: `NETworkManager/378`

You could also copy some of you existing profiles into the `Profiles` folder in the portable version to see if there are some issues. I had to do some adjustments in the profile file. 

![image](https://user-images.githubusercontent.com/16019165/111921039-badf8080-8a92-11eb-8dea-9cb92c931627.png)
