### ISSUE TITLE
Logging for Ping-Monitor

### ISSUE THREAD

**Issue by evilbaschdi** [BornToBeRoot/NETworkManager#389]
It would be genuinely nice to have the possibility to log responses returned by the Ping-Monitor into a log file to be able to have a protocol about downtimes of one or more hosts (by profile maybe).

**Comment by BornToBeRoot** [comment]
Will be in the next release. I also need this feature :)

**Comment by BornToBeRoot** [comment]
How about a context menu? 

![image](https://user-images.githubusercontent.com/16019165/102000531-ad269c00-3ce8-11eb-9145-45b2fffcc9bf.png)

Export dialog would be the same as in other dialogs (CSV, XML, JSON).

![image](https://user-images.githubusercontent.com/16019165/102000548-cc252e00-3ce8-11eb-974e-4784ee0c64bd.png)

**Comment by BornToBeRoot** [comment]
@evilbaschdi Here is a release with the export feature. You can try it and give some feedback if you want. 

https://cloud.borntoberoot.net/s/7WH9Ze7ysQkyxKc
PW: `2020Issue#389`

It will be available in the next release!

**Comment by evilbaschdi** [comment]
I had a look in it yesterday. Looks good as a first step. A "living log file" that is filled parallel to the responses in the GUI would have been nicer, but I can work with it :-)
(Maybe I now can stop spending thoughts on my halfhearted developed PingResponseLog - https://github.com/evilbaschdi/PingResponseLog)
