### ISSUE TITLE
Update language stats in GUI 

### ISSUE THREAD

**Issue by bovirus** [BornToBeRoot/NETworkManager#396]
@BornToBeRoot 

**Describe your issue**:

Language status inside program seems not update (compared with Transiflex). Example

Here there are some big differences

Italian - 75.8% (Transiflex) - 30.49% (GUI) - More than 50% in GUI!
Russian -  70.3% (Transiflex) - 70.88% (GUI) - Small differences (0.5%)
Polish (Poland) -  30.5% (Transiflex) - 76.44% (GUI) - Big differences (strange: GUI is more updated than Transiklex).

**Steps to reproduce the issue**:

1.
2.
3.

**NETworkManager version**: 

**Windows version**:

**.NET-Framework version**:

**Screenshots**

<details>
<summary>Eventlog (if application crashes)</summary>

</details>

**Comment by BornToBeRoot** [comment]
Looks like i switched Italian and Polish.

I will update it in the next release. 

There might be a difference since I updated the language resources with version 2020.12.0.

Can you send me a PR for the inno setup file?

**Comment by bovirus** [comment]
Hello.

I had already made a PR for the Inno Setup but it seems disapearred.

I finalized the Italian translation.
Now is translated at 100% (on Transiflex).

**Comment by bovirus** [comment]
@BornToBeRoot 

Update Inno Setup script

https://github.com/BornToBeRoot/NETworkManager/pull/397

[Languages]
Name: "brasilian";  MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"
Name: "czech";      MessagesFile: "compiler:Languages\Czech.isl"
Name: "dutch";      MessagesFile: "compiler:Languages\Dutch.isl"
Name: "french";     MessagesFile: "compiler:Languages\French.isl"
Name: "italian";    MessagesFile: "compiler:Languages\Italian.isl"
Name: "japanese";   MessagesFile: "compiler:Languages\Japanese.isl"
Name: "polish";     MessagesFile: "compiler:Languages\Polish.isl"
Name: "spanish";    MessagesFile: "compiler:Languages\Spanish.isl"
Name: "turkish";    MessagesFile: "compiler:Languages\Turkish.isl"

**Comment by BornToBeRoot** [comment]
@bovirus great. I will update the language files with the next release and add your username to the translators list.

**Comment by bovirus** [comment]
@BornToBeRoot 

Thanks.
I hope to see an important improvemnts like program vesion in main window.
Example in top left of main windowss.

**_NETworkManager 2020.12.1_**

**Comment by BornToBeRoot** [comment]
I had the version in previous versions in the status bar. But does it really make sense? If an update is available it is disaplayed in the title bar:

![image](https://user-images.githubusercontent.com/16019165/102140377-6dce8b80-3e5f-11eb-94e3-1ad970c88489.png)

**Comment by BornToBeRoot** [comment]
@bovirus Can i close the issue? 

Update for the stats: https://github.com/BornToBeRoot/NETworkManager/issues/396

PR https://github.com/BornToBeRoot/NETworkManager/pull/397 is merged.

**Comment by bovirus** [comment]
@BornToBeRoot 

Yes sure.
Please if you can make a new build with new language (Italian) to test the new installer/language.

**Comment by bovirus** [comment]
@BornToBeRoot 

New build of installer but seems that there are some issues

https://github.com/BornToBeRoot/NETworkManager/issues/401

**Comment by BornToBeRoot** [comment]
I will update the language files.
