### ISSUE TITLE
README - Add info about localization

### ISSUE THREAD

**Issue by bovirus** [BornToBeRoot/NETworkManager#399]
**Describe your feature request**:

@BornToBeRoot 

Please add in README and in the text of main page the info about localization

How to add a new language
How to revise a language
How to compile localization
etc

Thanks.

**Comment by BornToBeRoot** [comment]
How about this? https://github.com/BornToBeRoot/NETworkManager/commit/085cee8836d6cd48e769254021a8b18eec177580

Compile is not possible. Only the maintainer can request a download in transifex.

**Comment by bovirus** [comment]
Thanks for the info about localization.
You can close this toicket.
Thanks.
