### ISSUE TITLE
Update language file, fix translation für settings/context menu

### ISSUE THREAD

**Issue by bovirus** [BornToBeRoot/NETworkManager#401]
@BornToBeRoot 

**Describe your issue**:

**_- Installer with only three languages_**
I downloaded the enw instalelr build yesterday (14.12.2020)

It seems that contains only rìthree language for the instalelr (English/German/Russian).
Not include all enw languages of my PR.
I rebuild the instalelr from source on github and I checked that include 12 languages.
Please check

- Italian language update (100%) but seems many strings are untranslated
With new installer (Italian language translated 100%) I chedcked that 
in main menu many comamnd on left strip are untranslated.
in the settings many option (on left strip) are untranslated.
I checked thats oame problem appera with other language (ex. German)
Please check the screenshots

![NETworkManager - 01](https://user-images.githubusercontent.com/1262554/102191327-8cfa0700-3eb9-11eb-8764-86d4e62b2d20.jpg)

![NETworkManager - 02](https://user-images.githubusercontent.com/1262554/102191331-8d929d80-3eb9-11eb-9b2e-2e476b9f5882.jpg)

Could be possible that is not get right the language file from Transiflex.
I transalted "About" as "Informazioni programma" but I found it in new instalelr as old translation ("Informazioni su").

Thanks.

**Steps to reproduce the issue**:

1.
2.
3.

**NETworkManager version**: 

**Windows version**:

**.NET-Framework version**:

**Screenshots**

<details>
<summary>Eventlog (if application crashes)</summary>

</details>

**Comment by BornToBeRoot** [comment]
I update the language files so you can test it.

Thanks for confirming #279
I will add a converter to translate the names.

**Comment by bovirus** [comment]
@BornToBeRoot 

I didn't see changes in source code about language files

Pelase take care that here 

https://github.com/BornToBeRoot/NETworkManager/commit/947fd30cb15b26ae4742ca5dc4e190dfdc73b5a2

some languages are not included in stats in this file. Ex. 

Chinese (China)
Chinese (Taiwan)
Portoguese (Brasil)

**Comment by BornToBeRoot** [comment]
@bovirus here is the update for the language files. https://github.com/BornToBeRoot/NETworkManager/pull/406

There is only a diff for `it-IT` and `pl-PL`.

I only update the language files on a new (major) release, because it takes some time to prepare the files / adjust the stats. 2020.12.1 had only some bugfixes a few days after i released 2020.12.0.

**Comment by bovirus** [comment]
@BornToBeRoot 

Ok. Thanks.
