### ISSUE TITLE
NETwork Manager - Add version info on top left and version numbering

### ISSUE THREAD

**Issue by bovirus** [BornToBeRoot/NETworkManager#402]
@BornToBeRoot 

**Describe your feature request**:

I beleiev that could be suefull show the program version on top left afetr NETworkManager name

Please check the screenshoots.
I highghted the add etxt in red. 

![NETworkManager - 03](https://user-images.githubusercontent.com/1262554/102191657-00037d80-3eba-11eb-912f-87d160a9004d.jpg)

Note for future versiuon numbering.

I suggest to use scheme like YYYY.MM.DD (ex. 2020.12.15) with always two digits for DD MM

Thanks.

**Comment by BornToBeRoot** [comment]
Like this? https://github.com/BornToBeRoot/NETworkManager/pull/407

![image](https://user-images.githubusercontent.com/16019165/102278096-81debf80-3f29-11eb-9763-d7c6533fb8f1.png)

Version is year.month.build , if i should publish 2 or more builds one day (e.g. hotfix), i cannot increase the number to trigger an update.

**Comment by bovirus** [comment]
@BornToBeRoot 

Perfect. Thank you.
