### ISSUE TITLE
Change language list ordered by % of transation to alphabetical 

### ISSUE THREAD

**Issue by bovirus** [BornToBeRoot/NETworkManager#403]
@BornToBeRoot 

**Describe your feature request**:

I propose to change the order of language names in Settings fron current system (% of translation) to alphabetical order.

I believe is more clear and natural.

Thanks.

**Comment by BornToBeRoot** [comment]
Done! 

Sort by:
- Official/Community
- Name

![image](https://user-images.githubusercontent.com/16019165/102269753-5fdf4000-3f1d-11eb-8723-09ec31399d18.png)

**Comment by bovirus** [comment]
@BornToBeRoot 

Thanks for the improvemnt.

I belieeve that could be another ipmprovemnt to have a language list ordered alphabetically without difference bewteen Official and Community language.
