### ISSUE TITLE
Build issue - why can't I build project?

### ISSUE THREAD

**Issue by PCAssistSoftware** [BornToBeRoot/NETworkManager#413]
Hi

Just downloaded source and trying to build, but having issues which I hope you can advise on:-

1) Even though I have the .NET 5 SDK installed

![image](https://user-images.githubusercontent.com/10872799/102996404-ff529300-451a-11eb-964d-2721098ce55e.png)

it won't build, it shows 205 errors in VS

![image](https://user-images.githubusercontent.com/10872799/102996551-36c13f80-451b-11eb-87d7-5f226918d29d.png)

What am I missing?

2) When trying to open any of the views e.g. PowerShellHostView.xaml I get Invalid Markup error

![image](https://user-images.githubusercontent.com/10872799/102996635-5d7f7600-451b-11eb-9a1d-4922515a22b1.png)

Really want to be able to build and learn from this great project but just don't understand what I am missing here - thanks

**Comment by BornToBeRoot** [comment]
Is there an error in the Output tab?

**Comment by PCAssistSoftware** [comment]
Yeah several - output shown below in full, but in summary:-

5>EXEC : error : Could not find the Windows SDK

error MSB3073: The command "C:\Users\darre\.nuget\packages\microsoft.windows.cswinrt\1.1.0\cswinrt.exe @"C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager.Models\obj\Debug\net5.0-windows10.0.17763.0\Generated Files\cswinrt.rsp"" exited with code 1.

error CS0006: Metadata file 'C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager.Models\bin\Debug\net5.0-windows10.0.17763.0\ref\NETworkManager.Models.dll' could not be found **(this one appears multiple times)**

error NU1201: Project NETworkManager.Update is not compatible with net5.0-windows7.0 (.NETCoreApp,Version=v5.0). Project NETworkManager.Update supports: net5.0-windows10.0.17763 (.NETCoreApp,Version=v5.0) **(this one appears multiple times)**

`1>------ Rebuild All started: Project: NETworkManager.Utilities, Configuration: Debug Any CPU ------
2>------ Rebuild All started: Project: NETworkManager.Controls, Configuration: Debug Any CPU ------
3>------ Rebuild All started: Project: NETworkManager.Utilities.WPF, Configuration: Debug Any CPU ------
4>------ Rebuild All started: Project: NETworkManager.Update, Configuration: Debug Any CPU ------
NuGet package restore failed. Please see Error List window for detailed warnings and errors.
2>NETworkManager.Controls -> C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager.Controls\bin\Debug\net5.0-windows10.0.17763.0\NETworkManager.Controls.dll
4>NETworkManager.Update -> C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager.Update\bin\Debug\net5.0-windows10.0.17763.0\NETworkManager.Update.dll
3>NETworkManager.Utilities.WPF -> C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager.Utilities.WPF\bin\Debug\net5.0-windows10.0.17763.0\NETworkManager.Utilities.WPF.dll
1>NETworkManager.Utilities -> C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager.Utilities\bin\Debug\net5.0-windows10.0.17763.0\NETworkManager.Utilities.dll
5>------ Rebuild All started: Project: NETworkManager.Models, Configuration: Debug Any CPU ------
**5>EXEC : error : Could not find the Windows SDK**
5>C:\Users\darre\.nuget\packages\microsoft.windows.cswinrt\1.1.0\build\Microsoft.Windows.CsWinRT.targets(98,5): **error MSB3073: The command "C:\Users\darre\.nuget\packages\microsoft.windows.cswinrt\1.1.0\cswinrt.exe @"C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager.Models\obj\Debug\net5.0-windows10.0.17763.0\Generated Files\cswinrt.rsp"" exited with code 1.**
5>Done building project "NETworkManager.Models.csproj" -- FAILED.
6>------ Rebuild All started: Project: NETworkManager.Settings, Configuration: Debug Any CPU ------
6>CSC : **error CS0006: Metadata file 'C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager.Models\bin\Debug\net5.0-windows10.0.17763.0\ref\NETworkManager.Models.dll' could not be found**
6>Done building project "NETworkManager.Settings.csproj" -- FAILED.
7>------ Rebuild All started: Project: NETworkManager.Profiles, Configuration: Debug Any CPU ------
7>CSC : error CS0006: Metadata file 'C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager.Models\bin\Debug\net5.0-windows10.0.17763.0\ref\NETworkManager.Models.dll' could not be found
7>CSC : error CS0006: Metadata file 'C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager.Settings\bin\Debug\net5.0-windows10.0.17763.0\ref\NETworkManager.Settings.dll' could not be found
7>Done building project "NETworkManager.Profiles.csproj" -- FAILED.
8>------ Rebuild All started: Project: NETworkManager.Localization, Configuration: Debug Any CPU ------
8>CSC : error CS0006: Metadata file 'C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager.Models\bin\Debug\net5.0-windows10.0.17763.0\ref\NETworkManager.Models.dll' could not be found
8>CSC : error CS0006: Metadata file 'C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager.Profiles\bin\Debug\net5.0-windows10.0.17763.0\ref\NETworkManager.Profiles.dll' could not be found
8>CSC : error CS0006: Metadata file 'C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager.Settings\bin\Debug\net5.0-windows10.0.17763.0\ref\NETworkManager.Settings.dll' could not be found
8>Done building project "NETworkManager.Localization.csproj" -- FAILED.
9>------ Rebuild All started: Project: NETworkManager.Converters, Configuration: Debug Any CPU ------
10>------ Rebuild All started: Project: NETworkManager.Validators, Configuration: Debug Any CPU ------
11>------ Rebuild All started: Project: NETworkManager.Documentation, Configuration: Debug Any CPU ------
10>CSC : error CS0006: Metadata file 'C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager.Localization\bin\Debug\net5.0-windows10.0.17763.0\ref\NETworkManager.Localization.dll' could not be found
10>CSC : error CS0006: Metadata file 'C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager.Models\bin\Debug\net5.0-windows10.0.17763.0\ref\NETworkManager.Models.dll' could not be found
10>CSC : error CS0006: Metadata file 'C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager.Profiles\bin\Debug\net5.0-windows10.0.17763.0\ref\NETworkManager.Profiles.dll' could not be found
10>CSC : error CS0006: Metadata file 'C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager.Settings\bin\Debug\net5.0-windows10.0.17763.0\ref\NETworkManager.Settings.dll' could not be found
11>CSC : error CS0006: Metadata file 'C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager.Localization\bin\Debug\net5.0-windows10.0.17763.0\ref\NETworkManager.Localization.dll' could not be found
11>CSC : error CS0006: Metadata file 'C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager.Models\bin\Debug\net5.0-windows10.0.17763.0\ref\NETworkManager.Models.dll' could not be found
11>CSC : error CS0006: Metadata file 'C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager.Profiles\bin\Debug\net5.0-windows10.0.17763.0\ref\NETworkManager.Profiles.dll' could not be found
11>CSC : error CS0006: Metadata file 'C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager.Settings\bin\Debug\net5.0-windows10.0.17763.0\ref\NETworkManager.Settings.dll' could not be found
11>Done building project "NETworkManager.Documentation.csproj" -- FAILED.
10>Done building project "NETworkManager.Validators.csproj" -- FAILED.
9>CSC : error CS0006: Metadata file 'C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager.Localization\bin\Debug\net5.0-windows10.0.17763.0\ref\NETworkManager.Localization.dll' could not be found
9>CSC : error CS0006: Metadata file 'C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager.Models\bin\Debug\net5.0-windows10.0.17763.0\ref\NETworkManager.Models.dll' could not be found
9>CSC : error CS0006: Metadata file 'C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager.Profiles\bin\Debug\net5.0-windows10.0.17763.0\ref\NETworkManager.Profiles.dll' could not be found
9>CSC : error CS0006: Metadata file 'C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager.Settings\bin\Debug\net5.0-windows10.0.17763.0\ref\NETworkManager.Settings.dll' could not be found
9>Done building project "NETworkManager.Converters.csproj" -- FAILED.
12>------ Rebuild All started: Project: NETworkManager, Configuration: Debug Any CPU ------
12>C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager\NETworkManager.csproj : **error NU1201: Project NETworkManager.Update is not compatible with net5.0-windows7.0 (.NETCoreApp,Version=v5.0). Project NETworkManager.Update supports: net5.0-windows10.0.17763 (.NETCoreApp,Version=v5.0)**
12>C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager\NETworkManager.csproj : error NU1201: Project NETworkManager.Models is not compatible with net5.0-windows7.0 (.NETCoreApp,Version=v5.0). Project NETworkManager.Models supports: net5.0-windows10.0.17763 (.NETCoreApp,Version=v5.0)
12>C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager\NETworkManager.csproj : error NU1201: Project NETworkManager.Documentation is not compatible with net5.0-windows7.0 (.NETCoreApp,Version=v5.0). Project NETworkManager.Documentation supports: net5.0-windows10.0.17763 (.NETCoreApp,Version=v5.0)
12>C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager\NETworkManager.csproj : error NU1201: Project NETworkManager.Settings is not compatible with net5.0-windows7.0 (.NETCoreApp,Version=v5.0). Project NETworkManager.Settings supports: net5.0-windows10.0.17763 (.NETCoreApp,Version=v5.0)
12>C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager\NETworkManager.csproj : error NU1201: Project NETworkManager.Profiles is not compatible with net5.0-windows7.0 (.NETCoreApp,Version=v5.0). Project NETworkManager.Profiles supports: net5.0-windows10.0.17763 (.NETCoreApp,Version=v5.0)
12>C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager\NETworkManager.csproj : error NU1201: Project NETworkManager.Controls is not compatible with net5.0-windows7.0 (.NETCoreApp,Version=v5.0). Project NETworkManager.Controls supports: net5.0-windows10.0.17763 (.NETCoreApp,Version=v5.0)
12>C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager\NETworkManager.csproj : error NU1201: Project NETworkManager.Converters is not compatible with net5.0-windows7.0 (.NETCoreApp,Version=v5.0). Project NETworkManager.Converters supports: net5.0-windows10.0.17763 (.NETCoreApp,Version=v5.0)
12>C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager\NETworkManager.csproj : error NU1201: Project NETworkManager.Validators is not compatible with net5.0-windows7.0 (.NETCoreApp,Version=v5.0). Project NETworkManager.Validators supports: net5.0-windows10.0.17763 (.NETCoreApp,Version=v5.0)
12>C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager\NETworkManager.csproj : error NU1201: Project NETworkManager.Localization is not compatible with net5.0-windows7.0 (.NETCoreApp,Version=v5.0). Project NETworkManager.Localization supports: net5.0-windows10.0.17763 (.NETCoreApp,Version=v5.0)
12>C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager\NETworkManager.csproj : error NU1201: Project NETworkManager.Utilities.WPF is not compatible with net5.0-windows7.0 (.NETCoreApp,Version=v5.0). Project NETworkManager.Utilities.WPF supports: net5.0-windows10.0.17763 (.NETCoreApp,Version=v5.0)
12>C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager\NETworkManager.csproj : error NU1201: Project NETworkManager.Utilities is not compatible with net5.0-windows7.0 (.NETCoreApp,Version=v5.0). Project NETworkManager.Utilities supports: net5.0-windows10.0.17763 (.NETCoreApp,Version=v5.0)
12>Done building project "NETworkManager.csproj" -- FAILED.
========== Rebuild All: 4 succeeded, 8 failed, 0 skipped ==========
`

**Comment by PCAssistSoftware** [comment]
Some of them about not finding Windows SDK which confuses me because as per screenshot above it is installed

**Comment by BornToBeRoot** [comment]
Hi, sry for my late reply.

You could try to clone/download the repo and try to build it via command line:

```
dotnet restore .\Source\NETworkManager.sln
dotnet build .\Source\NETworkManager.sln --configuration Release --no-restore
```

This is the same AppVeyor CI is using to build the tool: https://github.com/BornToBeRoot/NETworkManager/blob/master/appveyor.yml


Or run the ".\build.ps1" script with PowerShell inside the folder.

---

Which VS Studio version are you using? .NET 5.0 requires Visual Studio 16.8.3 or later

**Comment by PCAssistSoftware** [comment]
Hi

Firstly I have Visual Studio 16.8.3

Just done a fresh download from your GitHub and tried building using the .\build.ps1 script

Still issues, 4 warnings - 2 errors - copied below:-

EXEC : error : Could not find the Windows SDK [C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager.Models\NETworkManager.Models.csproj]

C:\Users\darre\.nuget\packages\microsoft.windows.cswinrt\1.1.0\build\Microsoft.Windows.CsWinRT.targets(98,5): error MSB3073: The command "C:\Users\darre\.nuget\packages\microsoft.windows.cswinrt\1.1.0\cswinrt.exe @"C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager.Models\obj\Release\net5.0-windows10.0.17763.0\Generated Files\cswinrt.rsp"" exited with code 1. [C:\Users\darre\Downloads\NETworkManager-master\NETworkManager-master\Source\NETworkManager.Models\NETworkManager.Models.csproj]

**Comment by BornToBeRoot** [comment]
What does the command `dotnet --info` show? 

Edit: I use PowerShell 5.1

![image](https://user-images.githubusercontent.com/16019165/103108250-61f47d80-4646-11eb-9dc0-b6b63f9ec7f1.png)

**Comment by PCAssistSoftware** [comment]
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by PCAssistSoftware** [comment]
Solved!!

You need to have Universal Windows Platform development installed as well - might be worth mentioning that..

![image](https://user-images.githubusercontent.com/10872799/103111050-9402e100-4640-11eb-930f-3bd3fd295f47.png)

**Comment by BornToBeRoot** [comment]
Great! I will add it to the readme.
