### ISSUE TITLE
Fix Slovenian flag 

### ISSUE THREAD

**Issue by BornToBeRoot** [BornToBeRoot/NETworkManager#438]
Hi, 

Sorry, but last Portable  version have not Slovenian language integrated. Last setup have incorrect Slovenian Flag integrated :-(((
![Incorrect Slovenian Flag](https://user-images.githubusercontent.com/53031490/104120142-ca28ac00-5334-11eb-85f7-970fe4e4aeac.jpg)
![Slovenia flag](https://user-images.githubusercontent.com/53031490/104120145-cb59d900-5334-11eb-8875-88a4beb64530.png)
![Slovenian_Flag](https://user-images.githubusercontent.com/53031490/104120146-cb59d900-5334-11eb-96da-f5924f1e9957.png)

With respect,

Jadran

_Originally posted by @JadranR in https://github.com/BornToBeRoot/NETworkManager/issues/433#issuecomment-757450204_

**Comment by BornToBeRoot** [comment]
https://github.com/lipis/flag-icon-css/blob/master/flags/4x3/si.svg

**Comment by BornToBeRoot** [comment]
Wtf. This happens if i convert the icon with ImageMagick...


![image](https://user-images.githubusercontent.com/16019165/104226379-fd0f9480-5447-11eb-85c8-5ef10fdb708d.png)

**Comment by BornToBeRoot** [comment]
I need a flag with the size 64x48 as .png

**Comment by JadranR** [comment]
Here is Slovenian flag64x48 in png format

**Comment by JadranR** [comment]
Here is Slovenian flag64x48 in png format
![Slovenian-flag 64-48](https://user-images.githubusercontent.com/53031490/104228421-1ebe4b00-544b-11eb-9530-54bdb81b7b93.png)
![Zastava-Republike-Slovenije](https://user-images.githubusercontent.com/53031490/104228423-1fef7800-544b-11eb-9513-9e0c07a75bf0.png)

**Comment by JadranR** [comment]
Here is ling for Foreign web page::

https://www.gov.si/teme/drzavni-simboli/

link to Flag (png):
https://www.gov.si/assets/vladne-sluzbe/PROTOKOL/Foto-splosno-Protokol/Zastava/Zastava-Republike-Slovenije.png

Resizing with Paint Shop Pro 9 app Format isn't changed.

Best Regards,

Jadran

V V pon., 11. jan. 2021 ob 20:05 je oseba BornToBeRoot <
notifications@github.com> napisala:
