### ISSUE TITLE
NetworkManager 2021.1.0 - Strings untranslated in About window

### ISSUE THREAD

**Issue by bovirus** [BornToBeRoot/NETworkManager#440]
@BornToBeRoot 

There are some strings untranslated in About window.
Please modify source code and add these strings to the language files

1) I propose you to change "Update" text string control in "About window" in "Check Update"

2) **_GNU General Public License 3.0_**

3) **_Developed and maintaned by BornTobeRoot with the help of Community_**

Thanks.

**Comment by BornToBeRoot** [comment]
1) You mean this? This should be the "Update" section. I might implement an auto update feature later. 

![image](https://user-images.githubusercontent.com/16019165/107074496-1c040b00-67e9-11eb-996e-403e5d12c517.png)


2) This is the name of the license, so no translation needed

3) I will add a translation string.

**Comment by bovirus** [comment]
@BornToBeRoot 

"Update" (on the left) for me is not right because "Update" is like for a button then is not the scope because is a title.

Then could be "Program Update" (not only "Update")

![image](https://user-images.githubusercontent.com/1262554/107113195-b1d97d80-685d-11eb-9954-e27b381e731c.png)

Then please check also

"Developed and maintaned..." is untranslated. Please  add to the language file.
License type are untranslated. Please add to langaueg files.
The tool descripttion are untranslated. Please add to langaueg files.

**Comment by BornToBeRoot** [comment]
@bovirus i added the strings (except for the update section). I don't know what to rename this to...

Might take one day to sync with transifex.
