### ISSUE TITLE
Download gets flagged by Windows SmartScreen

### ISSUE THREAD

**Issue by SirMrDexter** [BornToBeRoot/NETworkManager#442]
After I download the installer windows warns me against running the application. It also popups up the Windows SmartScreen warning if I force it to run.

Is there anything you can do it avoid these warnings?

**Comment by SirMrDexter** [comment]
Also noticed, when installing updates, it doesn't remove previous version. The shortcut I had in task bar still opens the older version, while the shortcut from start menu opens the newer version.

**Comment by BornToBeRoot** [comment]
1) I think there is nothing i can do about it. Maybe sigining it with a code signing certificate would help (and costs money...). I think programs like Notepad++ have the same issue ([Thread](https://community.notepad-plus-plus.org/topic/17184/remove-code-signing-from-notepad)), but these setups are downloaded much more often. I think Microsoft smart screen works with reputation, so how often is the setup in use and scanned by Microsoft... 

2) I know. With 2021.1.0 i changed the App from x86 to x64, so the new version is installed next to the old one. 
I added a note to the [Changelog](https://borntoberoot.net/NETworkManager/Changelog#version-202110) and the release page, but it is easily overlooked.

**Comment by BornToBeRoot** [comment]
I close this. 

There is a SHA256 hash for each file you can download and you can check the files on virustotal or compile it yourself to be absolutely sure.

Feel free to reopen if you have any questions.
