### ISSUE TITLE
Profiles not loading

### ISSUE THREAD

**Issue by RafalNiewinski** [BornToBeRoot/NETworkManager#444]
**NETworkManager version**:  2021.1.0

**Windows version**: 10 2004

**.NET-Framework version**: 5.0.101

I have same situation mentioned here https://github.com/BornToBeRoot/NETworkManager/issues/442#issuecomment-764138527 with 2 versions installed (2020.12.2 for x86) (2021.1.0 for x64).

When `2020.12.2` are launched all my connection profiles are loaded properly but when `2021.1.0` are launched there is none of it visible.

When I launched `2021.1.0` for the first time my application profile selector (in title bar) was empty and there was no connection profiles in apps. I changed selection from nothing to 'Default' profile and my connections appeared but only for current runtime...
Next time when I launched `2021.1.0` profile selector remembered my last used profile 'Default' and it were selected automatically but none of the apps profiles are available.

Profiles still works on `2020.12.2`

I think it may be related with #432

**Comment by BornToBeRoot** [comment]
Did you changed the profile folder in 2020.12.2 and before? 

The default location is `%AppData%\NETworkManager\Profiles` or `ApplicationRoot\Profiles` if you use the portable version. It shouldn't matter if it's x86 or x64.

You can change it in the Settings > General > Profile

**Comment by RafalNiewinski** [comment]
No, both versions have it's default profile location in `AppData`.
Also they are both installed as stand-alone.

When i change profile name in `2020` it also appeared with this name in `2021` version so it is looking for the same profiles.
I also observed the same behaviour again. When I started version `2021` after profile rename, the profile selector were empty, I changed profile to my new name 'Test' and application profiles appeared like before only for this single run.

App profiles does not showing up when profile is loaded at startup.

**Comment by BornToBeRoot** [comment]
Could you post a video/gif with the behavior? Maybe with [ScreenToGif](https://github.com/NickeManarin/ScreenToGif)
Unfortunately I can't quite understand it.

**Comment by RafalNiewinski** [comment]
Sorry for late response, I didn't have time to make recording.
Now I see you are probably on the way with this bug so you know what is it about?

**Comment by BornToBeRoot** [comment]
The initial loading won't work. I will fix it when i have some time...

**Comment by BornToBeRoot** [comment]
New release should fix the issue. Can you test it?

**Comment by RafalNiewinski** [comment]
Now it works properly.
Thanks
