### ISSUE TITLE
Remote Desktop - Not saving Servers on exit? (Close or ignore... Self Solved)

### ISSUE THREAD

**Issue by DieLaughing** [BornToBeRoot/NETworkManager#446]
**Edit: Figured out what was wrong. Close issue or ignore. Sorry!!**

I'm new to this software, but I've dug through the settings to see if I'm just missing something. I've come up with no answer.

I will set up all my Remote Desktop>I'll turn off my computer at the end of the day>I start work the next day and open the software>Servers are gone. It seems like it's not saving the profile. 

I apologize if I'm just not seeing something, or confused about it. I appreciate any help.

**Comment by DieLaughing** [comment]
![notepad_KBYskvfq1f](https://user-images.githubusercontent.com/56925044/105716343-aea0d200-5eec-11eb-9ea8-e8fd4df0a19e.png)

But when I check the profile XML, the info is there...

**Comment by BornToBeRoot** [comment]
There is currently an issue. #444 i could finally reproduce it. 

I try to fix it asap.

Workaround: create a second profile file in the settings and switch  them to load the profile

**Comment by BornToBeRoot** [comment]
New release should fix the issue. Can you test it?
