### ISSUE TITLE
Application not responsive & crashing 

### ISSUE THREAD

**Issue by m0k0ut** [BornToBeRoot/NETworkManager#458]
**Describe your issue**:

Application crashes on clicking "network Interfaces" on the left side toolbar

**Steps to reproduce the issue**:

1. Click on the "network Interfaces"  icon in the left side toolbar
2. Wait for  5 secs after clicking

**NETworkManager version**: NETworkManager 2021.1.2

**Windows version**: Windows 10 Pro - version 20H2 - build 19042.746

**.NET-Framework version**: 5.0.2

**Screenshots**

![image](https://user-images.githubusercontent.com/24792559/107001357-d6d1e000-67cc-11eb-9e75-64827d211239.png)

<details>
<summary>
Log Name:      Application
Source:        Application Error
Date:          2/5/2021 4:03:46 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-FTOFQFG
Description:
Faulting application name: NETworkManager.exe, version: 2021.1.2.0, time stamp: 0x5fd43c92
Faulting module name: KERNELBASE.dll, version: 10.0.19041.662, time stamp: 0xec58f015
Exception code: 0xe0434352
Fault offset: 0x000000000002d759
Faulting process id: 0x1710
Faulting application start time: 0x01d6fb8c6ef7f876
Faulting application path: C:\Program Files\NETworkManager\NETworkManager.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 23377883-21cb-431b-9e42-3150547b5da3
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-02-05T07:03:46.0127127Z" />
    <EventRecordID>9928</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-FTOFQFG</Computer>
    <Security />
  </System>
  <EventData>
    <Data>NETworkManager.exe</Data>
    <Data>2021.1.2.0</Data>
    <Data>5fd43c92</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.19041.662</Data>
    <Data>ec58f015</Data>
    <Data>e0434352</Data>
    <Data>000000000002d759</Data>
    <Data>1710</Data>
    <Data>01d6fb8c6ef7f876</Data>
    <Data>C:\Program Files\NETworkManager\NETworkManager.exe</Data>
    <Data>C:\Windows\System32\KERNELBASE.dll</Data>
    <Data>23377883-21cb-431b-9e42-3150547b5da3</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

</summary>

</details>

**Comment by BornToBeRoot** [comment]
Are there any other logs in den eventvwr? KERNELBASE.dll could be anything :)

**Comment by BornToBeRoot** [comment]
Fixed. I could reproduce the issue on one of my systems. Will be updated in the next release.
