### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by AGene1234** [BornToBeRoot/NETworkManager#563]
Sometime ago i came across multiple disconnections from a tp-link router i was using as an access point connecting to the modem-router (a little research made me assume that it could not handle a lot of wifi devices simultaneously connected -with 3 devices was okay with 6 was disconnecting-), where, when i was flushing the dns, releasing and renew the ip either of the ethernet or my main computer of its wifi, it was able to reconnect without much problem. i have to say that the tiny tp link router (the size of a matchbox) was first released in 2012 or 2013 (old and it could contribute to the problem as far i could know).

- My suggestion has to do with monitoring the connectivity of a selected interface (or multiple) to an access point locally (wifi connection to a modem router, just router or extender in ap mode) and automating the process the moment your program detects a disconnection to automatically reconnect without me having to do anything further, [in the end i upgraded to an netgear repeater in ap mode and the problem got completely resolved without disconnections. Regardless I believe it would be a nice addition for anyone that cannot spare more money than inexpensive products]

- Another suggestion that i do not know if you would like it, it's if you could add extra functionality to show the actual external public ip from an internet service that reports what ip it sees (i have a vpn but i noticed that sometimes it shows a wrong ip, thus mistaken connection per country, unless i disconnect and reconnect). currently i have a few standalone little apps on the tray testing them to see what fits me better, so i thought to ask you if you would consider integrating this feature too)

thanks in advance
(also sorry for the long post)

**Comment by BornToBeRoot** [comment]
Hi,

thanks for you suggestion.

I already monitor if a network connection is up/down or the ip changes. It's should be possible to implement "custom actions", maybe with a powershell script (there was already a similar request a few month ago). But there are also cases where the disconnect/connect is wanted (Connect from WiFi to LAN, Switch Network/VLAN from Client to Server or Switches/ ect.). Maybe as optional feature. 


The public ip is visible in the dashboard. You can also change the api provider: https://borntoberoot.net/NETworkManager/Application/Dashboard#use-custom-api

I may update the notification window and add the public IP there as well.

**Comment by AGene1234** [comment]
Possibly the similar suggestion came from me if you have in mind a suggestion from twitter (i found out how to communicate in github just yesterday by accident, even though you had said to contact you on github and i was thinking like "yeah sure.. how??" lol). Either way I am just a user, very far from coding and the only thing i could contribute to you is UI & UX feedback (would you accept a donation at some point later? i am a little tight now, but i consider your program very good even for basic users)

as far as the external ip in the dashboard, either it says that i am not connected to the internet when i am connected or it is showing errors showing only local ips but nothing further. i must mention that i connect through vpn (expressvpn) to the web, if that's important to be aware of. it doesn't cause any connectivity issues by a longshot. i am telling you this in comparison to a small standalone external ip lookup app that doesn't have any issues regardless of my connection going through an access point and then through a vpn (it's a annual paid subsription, it's not a misconfigured free vpn as most are).

consider all of the above as a simple user's feedback

thanks
alex

**Comment by BornToBeRoot** [comment]
1) I will not implement custom actions that will be executed, for example, after a reconnection. I have never had the use case and I don't know of any. Most will / should be properly updated by default from Windows 10/11.

2) The dashboard & status window was revised some time ago and the public IP should now be displayed correctly or after a reload. Also when a VPN is used.

If you have any other improvements, feel free to let me know.
