### ISSUE TITLE
Ping fail email update

### ISSUE THREAD

**Issue by vviraj-lk** [BornToBeRoot/NETworkManager#564]
Hi Dude,

Wish to see if there is a function to get an email from ping failures. Appreciate your work Great Job.

Thank you,

**Comment by BornToBeRoot** [comment]
Hi,

my tool is not a classic montitoring software. I may add desktop notifications if ping is up/down, but i think you should take a look at Icinga, Centreon or CheckMK for something like Mail notifcations.

Greetings

**Comment by BornToBeRoot** [comment]
Closed. Desktop notifications will be implemented here: https://github.com/BornToBeRoot/NETworkManager/issues/194
