### ISSUE TITLE
How can I switch from dark theme/GUI to light theme/GUI

### ISSUE THREAD

**Issue by pstein** [BornToBeRoot/NETworkManager#582]
I don't like the dark/black theme/GUI

How can I switch to light theme/GUI?

**Comment by BornToBeRoot** [comment]
Hi, you can change it in the settings.

![image](https://user-images.githubusercontent.com/16019165/111078522-23a88500-84f6-11eb-9dde-6a4175c476e2.png)

**Comment by BornToBeRoot** [comment]
Some labels may be hard to read. I try to improve the light UI in the future
