### ISSUE TITLE
Korean (KO) translation

### ISSUE THREAD

**Issue by VenusGirl** [BornToBeRoot/NETworkManager#584]
Transifex requested a Korean (KO) translation.
Please accept it.

**Comment by BornToBeRoot** [comment]
Done. I added "ko_KR". You can join the translation team now

**Comment by VenusGirl** [comment]
I'm trying to start translating Korean, but I can't see Korean (Korea) on the list of Join team.

**Comment by BornToBeRoot** [comment]
![image](https://user-images.githubusercontent.com/16019165/111355339-8e3cfa80-8687-11eb-9509-f3eaa35c076d.png)

**Comment by VenusGirl** [comment]
![FmKorean](https://user-images.githubusercontent.com/53147200/111357834-04b01b80-86cd-11eb-99d3-a16084450b3b.png)


View resources and translation buttons are not activated.
Is it because Korean (KO) was rejected in the reply mail when I first requested for translation?

**Comment by BornToBeRoot** [comment]
I added you on Transifex. If you want, you can add your name/username to the contributors list:
https://github.com/BornToBeRoot/NETworkManager/blob/master/Contributors.md

I will add the language file and flag to the program with the next update.

**Comment by BornToBeRoot** [comment]
@VenusGirl i added the translation file + flag. Is the native language correct? 

![image](https://user-images.githubusercontent.com/16019165/111888083-a8edd700-89d9-11eb-8a08-fdf813b40740.png)
