### ISSUE TITLE
Update Download

### ISSUE THREAD

**Issue by Sam1285** [BornToBeRoot/NETworkManager#598]
Hi,

if you download the new version 2021.3.14 you'll get the 2021.2.17 version instead.

Greetings 
Sam

![Picture](https://user-images.githubusercontent.com/39922005/111428481-d72c9780-86f7-11eb-9b7c-81d8da424f62.JPG)

![Pic2](https://user-images.githubusercontent.com/39922005/111428696-2246aa80-86f8-11eb-8c4a-9d9764129676.JPG)

**Comment by BornToBeRoot** [comment]
Done. Sorry, i forgot to update the URL :)
