### ISSUE TITLE
Add in github home a section/note for the translation

### ISSUE THREAD

**Issue by bovirus** [BornToBeRoot/NETworkManager#629]
**Describe your feature request**:

Please add in github repostiory home a section/note that inform that translation are hosted on transiflex and put the link to the Transiflex home page translations,.

I know that it's available an icon about Transiflex but a specfic isection could be more clear and visible.

Thanks.

**Comment by BornToBeRoot** [comment]
I moved it to the [CONTRIBUTING](https://github.com/BornToBeRoot/NETworkManager/blob/master/CONTRIBUTING.md) file some time ago. 

![image](https://user-images.githubusercontent.com/16019165/111914681-3c271b00-8a73-11eb-95d0-d6b9de32a1f0.png)

**Comment by bovirus** [comment]
@BornToBeRoot 
For me the block "Translate/Transiflex" is not so easy to understand.

For me is better to have a section after "How to report an issues" that could be "Program translation" where you mentioned that program translation are hosted on Transiflx and put them the link to Transiflex page.

**Comment by BornToBeRoot** [comment]
OK. I changed the text.
