### ISSUE TITLE
Ping Statistics menu collapse button

### ISSUE THREAD

**Issue by Swiftzn** [BornToBeRoot/NETworkManager#70]
Pretty simple issue to fix, but it seems the arrow to collapse and expand is the wrong way round depending on if stats are shown/hidden.

When Stats are shown it should be an arrow pointing down to signify you want to collapse
When stats are hidden it should be pointing up to signify you want to expand.

Or maybe it's just me but hey

**Comment by BornToBeRoot** [comment]
This is the default:
https://www.wpftutorial.net/Expander.html

But i think you are right, because the statistic is unfold from the bottom.

**Comment by BornToBeRoot** [comment]
I think the icons are correct, they show the current status (collapsed / unfolded) of the expander.

The default expander from Microsoft works the same way and in the examples of my libary (mahapps.metro) the expander looks the same.

Please correct me if I'm wrong 😄 

I close the issue for now.
