### ISSUE TITLE
Discovery Protocol crashes after scanning network for lldp

### ISSUE THREAD

**Issue by Plumperquatsch** [BornToBeRoot/NETworkManager#707]
**Describe your issue**:
The application crashes after scanning Ethernet for LLDP. The app shuts down after the duration time elapses.
The windows event log shows a .NET core exception.

**Steps to reproduce the issue**:

1. Choose Ethernet as interface
2. Choose protcol LLDP or LLDP/CDP
3. Record

**NETworkManager version**: 201.3.28.0

**Windows version**: 20H2 Bild 19042.928

**.NET-Framework version**: 5.0.5

<details>
<summary>
 <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1026</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2021-04-18T08:54:11.4089345Z" /> 
  <EventRecordID>39228</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>Keppler.roemer.dc</Computer> 
  <Security /> 
  </System>
  <EventData>
  <Data>Application: NETworkManager.exe CoreCLR Version: 5.0.521.16609 .NET Version: 5.0.5 Description: The process was terminated due to an unhandled exception. Exception Info: System.InvalidOperationException: A TwoWay or OneWayToSource binding cannot work on the read-only property 'Device' of type 'NETworkManager.Models.Network.DiscoveryProtocolPackageInfo'. at MS.Internal.Data.PropertyPathWorker.CheckReadOnly(Object item, Object info) at MS.Internal.Data.PropertyPathWorker.ReplaceItem(Int32 k, Object newO, Object parent) at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange) at MS.Internal.Data.PropertyPathWorker.RefreshValue() at MS.Internal.Data.ClrBindingWorker.ScheduleTransferOperation(Object arg) at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests() at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs) at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) at System.Windows.Threading.DispatcherOperation.InvokeImpl() at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj) at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location --- at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state) at System.Windows.Threading.DispatcherOperation.Invoke() at System.Windows.Threading.Dispatcher.ProcessQueue() at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o) at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs) at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs) at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam) at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg) at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame) at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame) at System.Windows.Threading.Dispatcher.Run() at System.Windows.Application.RunDispatcher(Object ignore) at System.Windows.Application.RunInternal(Window window) at System.Windows.Application.Run() at NETworkManager.App.Main()</Data> 
  </EventData>
  </Event>

</summary>

</details>

**Comment by BornToBeRoot** [comment]
Thank you for reporting the problem. I will try to fix it, but it may take some time (because I am a bit busy at the moment). I also need to set up a test environment for this.

I will also update the script then #241

**Comment by BornToBeRoot** [comment]
@Plumperquatsch Fixed in the next release!

**Comment by BornToBeRoot** [comment]
Test build

URL: https://cloud.borntoberoot.net/s/xZtPE6dMa4Sac4i
Password: `NETworkManager#2021`
