### ISSUE TITLE
Feature request: Choco package

### ISSUE THREAD

**Issue by unquietwiki** [BornToBeRoot/NETworkManager#84]
- https://chocolatey.org/packages
- https://chocolatey.org/docs/create-packages

The uptake / management of using this software; might be better achieved with distribution via Chocolatey.

**Comment by BornToBeRoot** [comment]
Or updates via nUpdate.

https://www.nupdate.net/

But then i need to host a webserver.

**Comment by unquietwiki** [comment]
@BornToBeRoot TIL about NUpdate. Looks cool.

As for Choco dev, I've wanted to make use of it for internal app distribution. You don't need an actual server to maintain packages: only for internal distribution. If you're submitting directly to the main Choco rep, then you should be fine. Since it looks like both this and NUpdate have reliance on nuget, the process may be similar for both.

[Example_7-Zip.zip](https://github.com/BornToBeRoot/NETworkManager/files/1940317/Example_7-Zip.zip)

**Comment by BornToBeRoot** [comment]
I created a choco package with the msi-package i published with the latest version. Can you try it before i publish it to the world? It's my first package, but installing and uninstalling works...

It's contained in the zip package i attached.

![image](https://user-images.githubusercontent.com/16019165/40131737-1add0610-593b-11e8-84f3-6862f59d958c.png)

[NETworkManager.1.6.2.zip](https://github.com/BornToBeRoot/NETworkManager/files/2010097/NETworkManager.1.6.2.zip)

**Comment by BornToBeRoot** [comment]
`choco install networkmanager --version 1.6.2`

**Comment by unquietwiki** [comment]
@BornToBeRoot painless! 🥇

**Comment by BornToBeRoot** [comment]
You can leave this open... There was an issue with the automated test and i added a dependency for the .net-framework.

I wait until the package is approved by a moderator.
https://chocolatey.org/packages/NETworkManager/1.6.2

**Comment by BornToBeRoot** [comment]
It just got approved, you can now install with:

`choco install networkmanager`

**Comment by unquietwiki** [comment]
That's awesome news. Thanks! 😊
