### ISSUE TITLE
Wrong public IP indication

### ISSUE THREAD

**Issue by leonidts** [BornToBeRoot/NETworkManager#841]
**Describe your issue**:
Public IP in Internet section of Dashboard is showing truncated: last group of IPv4 address shows only first digit.
For example, address 100.100.100.100 is showing 100.100.100.1.
api.ipify.org returns correct address

**Steps to reproduce the issue**:
1. Just open Dashboard.

**NETworkManager version**: 
2021.5.9.0

**Windows version**:
Windows 10 Pro 64bit 20H2 19042.985 and 21H1 19043.985

**.NET-Framework version**:
5.0.6

**Comment by BornToBeRoot** [comment]
@leonidts  Thanks for reporting the issue. Will be fixed in the next release.
