### ISSUE TITLE
Remote Desktop

### ISSUE THREAD

**Issue by Alduma08** [BornToBeRoot/NETworkManager#845]
**Describe your issue**:
I trie to create a new Remote Destop session but I get the error: `Disconnet reason 4 not foud in resources!`

**Steps to reproduce the issue**:

1. Introduce the DNS domain name of IP address of the computer I want to connect to.
2. Click enter and get the error message.
3.

**NETworkManager version**: NETworkManager 2021.5.9.0

**Windows version**: Windows 10 Pro 20H2. Compilation 19042.985

**.NET-Framework version**: .Net Framework 4.8 (528372)

**Screenshots**

IP address:
![imagen](https://user-images.githubusercontent.com/38432205/121154970-ae73f400-c847-11eb-95f2-283dbfeb9873.png)

Error message:
![imagen](https://user-images.githubusercontent.com/38432205/121154986-b2a01180-c847-11eb-8f08-6489312a9b3b.png)

.NET Framework version:
![imagen](https://user-images.githubusercontent.com/38432205/121155001-b5026b80-c847-11eb-980e-cf539dc70816.png)

<details>
<summary>Eventlog (if application crashes)</summary>

</details>

**Comment by BornToBeRoot** [comment]
Hi,

it looks like this is something you have to configure on your server/network.

> Extended Reason: The remote session ended because the total login time limit was reached. This limit is set by the server administrator or by network policies.

https://social.technet.microsoft.com/wiki/contents/articles/37870.remote-desktop-client-troubleshooting-disconnect-codes-and-reasons.aspx

---

I will add the disconnect reason 4 as message - thanks for reporting it
