### ISSUE TITLE
Feature request: IPv6 subnet calculator

### ISSUE THREAD

**Issue by unquietwiki** [BornToBeRoot/NETworkManager#85]
- https://github.com/ygvn/IPv6-Subnet-Calculator-Tool-JavaFX
- https://github.com/beardedlinuxgeek/ipv6-subnet-calculator
- https://github.com/aipi/IPv6-subnet-calculator

There are several implementations to reference; and its possible code from the first example may be [license-compatible](https://www.gnu.org/licenses/license-list.en.html#ModifiedBSD).

**Comment by BornToBeRoot** [comment]
Or maybe this...

https://github.com/lduchosal/ipnetwork

Available via Nuget. BSD 2

**Comment by BornToBeRoot** [comment]
Subnet calculator for ipv6 added (no ipv6 splitter)

Commit: https://github.com/BornToBeRoot/NETworkManager/commit/0f46f587af7844f73dd66544c2074b071f88505a

**Comment by unquietwiki** [comment]
@BornToBeRoot I was assuming you wanted me to build & test that on my end. My build environment doesn't seem to like building it. I tried to improvise, but results were mixed. Here's from my abortive attempt to make it work: using VS Code, .NET 4.7.2, and .NET Core 2.1 SDKs.

- [App.config.txt](https://github.com/BornToBeRoot/NETworkManager/files/2070632/App.config.txt)
- [build.bat.txt](https://github.com/BornToBeRoot/NETworkManager/files/2070628/build.bat.txt)
- [NETworkManager.csproj.txt](https://github.com/BornToBeRoot/NETworkManager/files/2070629/NETworkManager.csproj.txt)
- [Directory.Build.props.txt](https://github.com/BornToBeRoot/NETworkManager/files/2070631/Directory.Build.props.txt)

**Comment by BornToBeRoot** [comment]
Hi,

which VS and Windows version do you use?

There is a Pre Build script which generates the `AxMSTSCLib.dll` and `MSTSCLib.dll`, but you can also copy these files from one of the other releases into the programfolder.
https://github.com/BornToBeRoot/NETworkManager/blob/master/Scripts/PreBuildEventCommandLine.ps1

I plan to add the subnetting and supernet feature this weekend: https://github.com/lduchosal/ipnetwork
This will be the last feature for the version 1.6.3.0, then I will publish it

The subnet calculator for IPv6 is working (this libary is tested and used by many others), I attached a build of the current master.

[NETworkManager_v1.6.3.0_BETA.zip](https://github.com/BornToBeRoot/NETworkManager/files/2071100/NETworkManager_v1.6.3.0_BETA.zip)

**Comment by unquietwiki** [comment]
@BornToBeRoot build spec already provided; funny enough, VS Code was saying I didn't have the stuff for 4.6 SDK installed; which I thought I did. (shrugs) You may want to try re-targeting to 4.7.2 anyway, given the recent update + support for .NET Standard 2.0 content.

The calculator works, though one thought: if I put in **2001:DB8::** , I should get a **/32** result; not a half-hearted **/64**. From my experience  with IPv6, a lot of calculation is going to take place above /64; so use-cases of /32, /48, and /56 may be more common than past /64. You may even want to do some soliciting of potential users for more feedback.

- https://en.wikipedia.org/wiki/IPv6_address
- https://www.reddit.com/r/ipv6/

**Comment by BornToBeRoot** [comment]
There is an open issue in the IPNetwork libary (7 days ago), let's wait what for a response from the maintainer.

https://github.com/lduchosal/ipnetwork/issues/29

I think it would make sense if the user always have to enter the cidr 2001:db8:**/xx**. I have to change the validator that no IPv6 without CIDR can be entered...

Btw. The Subnetting feature looks good, but the application freezes on large subnets (like 0/ to /128 😄 )

![image](https://user-images.githubusercontent.com/16019165/41002697-d3fe546c-6914-11e8-9df5-4b59f333b472.png)


I will make this async and add a warning/note.

**Comment by unquietwiki** [comment]
@BornToBeRoot Awesomesauce. And yeah, a warning would be good. :p

**Comment by BornToBeRoot** [comment]
Subnet Calculator / Subnetting / Supernetting with IPv6 support added!

Version 1.6.3.0 released: https://github.com/BornToBeRoot/NETworkManager/releases/latest

**Comment by unquietwiki** [comment]
@BornToBeRoot I saw you posted an updated choco package too. May want to look into using https://chocolatey.org/packages/dotnetfx as a dependency, instead of the version-specific one.
