### ISSUE TITLE
IP Scanner - Custom DNS server

### ISSUE THREAD

**Issue by helgehegg** [BornToBeRoot/NETworkManager#90]
**Describe your issue or feature request**:
I often ip-scan various labs within my company and then it would be a super feature to be able to specify another (lab)DNS server to use for the lookup. 

**Steps to reproduce the issue**:

1.
2.
3.

**NETworkManager version**:

**Windows version**:

**.NET-Framework version**:

**Screenshots**

<details>
<summary>Eventlog (if application crashes)</summary>

</details>

**Comment by BornToBeRoot** [comment]
You can define one or multiple dns server (if not --> system default)

![image](https://user-images.githubusercontent.com/16019165/40682892-35a2d8f6-638d-11e8-838c-ecae85191bca.png)

As you can see, it will iterate through all dns server until it gets an answer (Google DNS cannot resolve 192.168.178.1)...

![image](https://user-images.githubusercontent.com/16019165/40682871-2487c39c-638d-11e8-9038-5e81cd62cab1.png)

Code is merged into master. The feature will be released with the next version...
