### ISSUE TITLE
Allow IP address scanning based on hostname.

### ISSUE THREAD

**Issue by corbob** [BornToBeRoot/NETworkManager#93]
**Describe your issue or feature request**: Allow IP address scanning based on hostname.
ie: server1.example.com/24 would lookup the IP for server1.example.com and scan the /24 subnet.

**Steps to reproduce the issue**: None

**NETworkManager version**: NETworkManager_v1.6.2.0_Portable

**Windows version**: Windows 10 1803

**.NET-Framework version**: 4.7? Whatever comes with Win 10 1803...

**Comment by corbob** [comment]
Could we change this from a Feature Request to a Bug? I just found the setting turned on that to me implies that it should be supported: 
![image](https://user-images.githubusercontent.com/30301021/40156535-ef096754-594e-11e8-8f13-7ea48c6b6e5c.png)

**Comment by BornToBeRoot** [comment]
Nope. Because it's not a bug 😄 

This option toggles the "Resolve Hostname" for the scanned IPs.

![image](https://user-images.githubusercontent.com/16019165/40167562-a32779ca-59c1-11e8-9e7e-524e46c40488.png)

**Comment by corbob** [comment]
Seems reasonable. I was clearly reading that option as being the other way around.

**Comment by BornToBeRoot** [comment]
Here is your requested feature (PR #94)

![image](https://user-images.githubusercontent.com/16019165/40259447-6f2feb8a-5af6-11e8-8455-4a791077dca1.png)

You can try it by compiling the current master.

Or wait for the next release!
